'use client';
import {useState} from 'react';
import {Link2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {useWorkspace} from './context';
import {Button,Callout,DataTable,Row,Cell,Money,Status} from './shared';
import {suggestedBankMatches} from '@/lib/accounting/engine';
export function BatchMatching(){const {company,state,month,send,saving}=useWorkspace(),[open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]);const used=new Set<string>();const proposals=company.bank.filter(r=>r.date.startsWith(month)&&!state.bankMatches[r.id]).flatMap(row=>{const matches=suggestedBankMatches(company,state,row.id).filter(j=>j.sourceId===row.reference&&j.date===row.date&&!used.has(j.id));if(matches.length!==1)return [];used.add(matches[0].id);return [{row,journal:matches[0]}];});return <><Button variant="outline" onClick={()=>{setSelected(proposals.map(p=>p.row.id));setOpen(true);}}><Link2 size={16}/>Review clear matches</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="journal-dialog"><DialogHeader><DialogTitle>Review suggested bank matches</DialogTitle><DialogDescription>These entries have the same date, source reference and amount, with one unambiguous cash-book candidate. Check the list before confirming.</DialogDescription></DialogHeader>{proposals.length===0?<Callout>No unambiguous matches are available. Post missing cash-book entries or match the remaining items individually.</Callout>:<><DataTable headers={['Use','Date','Bank reference','Cash-book entry','Amount']}><>{proposals.map(p=><Row key={p.row.id}><Cell><Checkbox aria-label={`Match ${p.row.id}`} checked={selected.includes(p.row.id)} onCheckedChange={v=>setSelected(ids=>v?[...ids,p.row.id]:ids.filter(id=>id!==p.row.id))}/></Cell><Cell>{p.row.date}</Cell><Cell>{p.row.reference}<p>{p.row.description}</p></Cell><Cell>{p.journal.id}</Cell><Cell className="number"><Money value={p.row.amount}/></Cell></Row>)}</></DataTable><div className="form-actions"><Status>{selected.length} selected</Status><Button disabled={saving||!selected.length} onClick={async()=>{const matches=proposals.filter(p=>selected.includes(p.row.id)).map(p=>({bankId:p.row.id,journalIds:[p.journal.id]}));if(await send({type:'matchBankBatch',matches}))setOpen(false);}}>Confirm {selected.length} matches</Button></div></>}</DialogContent></Dialog></>;}
