'use client';
import {taskSchedule,closePackDate} from '@/lib/accounting/workday-calendar';
import {MonthReviewPanel} from './month-review';
import {useEffect,useMemo,useState} from 'react';
import {BriefcaseBusiness,ArrowRight,FileText,Download,LockKeyhole,Check,NotebookPen,Plus} from 'lucide-react';
import {useWorkspace} from './context';
import {Button,Input,SelectField,Panel,PageHeading,Stat,Status,Callout,DataTable,Row,Cell,Money,SearchField} from './shared';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {CAREER_MONTHS,careerKey} from '@/lib/accounting/career';
import {careerTasks,careerMetrics,careerEvidenceChecks,blankForecast,forecastSchedule,FORECAST_FIELDS} from '@/lib/accounting/career-work';
import {careerPortfolioHTML,careerForecastCSV} from '@/lib/accounting/career-exports';
import {gradeExercise} from '@/lib/accounting/engine';
import {downloadFile,sourcePack} from '@/lib/accounting/exports';
import {money,monthEnd,parseMoney} from '@/lib/accounting/money';
import {InvoiceForm} from './invoice-form';
import {BalanceReconciliationView} from './balance-reconciliation';
import type {CareerRole,CareerScenario,CareerTask,CareerSubmission,CareerForecast} from '@/lib/accounting/career-types';
import type {SourceDocument} from '@/lib/accounting/types';

function monthLabel(month:string){return new Date(`${month}-15T12:00:00Z`).toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'});}
function useUnloadWarning(dirty:boolean){useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);}
function CareerSetup(){
 const {state,send,saving,loaded,go,notebook}=useWorkspace();
 const [startMonth,setStart]=useState('2025-07'),[role,setRole]=useState<CareerRole>('financial-manager'),[scenario,setScenario]=useState<CareerScenario>('messy'),[seed,setSeed]=useState(String(state.seed));
 const [confirm,setConfirm]=useState(false),[confirmation,setConfirmation]=useState('');
 async function start(){
  // Download the current saved state before the explicit replacement command; retain unsaved notebook separately.
  downloadFile(`LedgerLab-before-takeover-${state.seed}.json`,JSON.stringify({format:'LedgerLab backup',version:1,state},null,2),'application/json');
  if(notebook.text!==state.notes)downloadFile(`LedgerLab-unsaved-notebook-${state.seed}.txt`,notebook.text);
  if(await send({type:'startCareer',seed:Number(seed),startMonth,role,scenario,daily:true,confirmation})){setConfirm(false);go('career');}
 }
 return <><PageHeading eyebrow="From audit to ownership" title="Take over the accountant’s desk" description="Join an existing business. Inherit its books. Own the next close, the cash and the explanation."/>
 <section className="career-hero"><div><span className="career-kicker">YOUR FIRST DAY / HARBOUR & CO.</span><h2>The previous accountant has left.<br/>The work has not.</h2><p>Start in any month of 2025. Earlier transactions and bank reconciliations are inherited. From your start date, invoices, bank movements, payroll and month-end adjustments are yours to process.</p><div className="career-chips"><span>Source-led work</span><span>Real ledger consequences</span><span>Monthly progression</span><span>Management decisions</span></div></div><BriefcaseBusiness size={88} strokeWidth={1}/></section>
 <div className="grid-2"><Panel title="Choose your appointment" subtitle="The existing December drill remains available until you explicitly replace it."><div className="panel-body career-fields">
 <label>First working month<SelectField label="Takeover start month" value={startMonth} onChange={setStart} options={CAREER_MONTHS.map(m=>({value:m,label:monthLabel(m)}))}/></label>
 <label>Your role<SelectField label="Takeover role" value={role} onChange={v=>setRole(v as CareerRole)} options={[{value:'financial-accountant',label:'Financial accountant: books, close and reporting'},{value:'financial-manager',label:'Financial manager: plus liquidity and investment decisions'}]}/></label>
 <label>Handover condition<SelectField label="Handover condition" value={scenario} onChange={v=>setScenario(v as CareerScenario)} options={[{value:'messy',label:'Messy handover: inherited errors to resolve'},{value:'supported',label:'Supported handover: no planted legacy errors'}]}/></label>
 <label>Reproducible case seed<Input aria-label="Takeover seed" value={seed} onChange={e=>setSeed(e.target.value)} inputMode="numeric"/></label>
 {startMonth==='2025-01'&&<p className="text-sm text-muted-foreground">January starts from the agreed opening trial balance, so there are no planted inherited current-year errors.</p>}
 <Button disabled={saving||!loaded||!/^\d+$/.test(seed)||Number(seed)<1||Number(seed)>2147483647} onClick={()=>setConfirm(true)}><BriefcaseBusiness size={16}/>Set up my takeover</Button></div></Panel>
 <Panel title="What you will own"><div className="panel-body career-scope"><h3>Transaction processing</h3><p>Customer and supplier invoices, receipts, payments, tax coding, payroll and inventory entries.</p><h3>Control and close</h3><p>Bank and subledger reconciliations, cut-off, accruals, prepayments, fixed assets, leases, estimates and period locks.</p><h3>Reporting and decisions</h3><p>Monthly management accounts, budget explanations, collections, supplier priorities, a 13-week cash forecast, an investment appraisal and year-end AFS support.</p><Callout>Starts in on-the-job mode, without worked answers. Quantitative work is checked against independent evidence. Your written judgement is retained for review, not automatically certified.</Callout></div></Panel></div>
 <Callout tone="warning">Fictional single-entity AUD 2025 case with disclosed teaching tax and payroll inputs. Not a South African tax engine, statutory filing service or guarantee of job readiness. January to December is simulated; operating activity beyond December is not yet generated.</Callout>
 <Dialog open={confirm} onOpenChange={v=>!saving&&setConfirm(v)}><DialogContent><DialogHeader><DialogTitle>Replace the active practice with your takeover?</DialogTitle><DialogDescription>Your current saved work will be downloaded before the replacement request. Check that your browser permits the download; a download is not proof you have retained a backup.</DialogDescription></DialogHeader><p>{monthLabel(startMonth)} · {role} · {scenario} · seed {seed}</p><label>Type START TAKEOVER to confirm<Input aria-label="Confirm takeover replacement" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><Button onClick={start} disabled={saving||confirmation!=='START TAKEOVER'}>Download backup & start takeover</Button></DialogContent></Dialog>
 </>;
}

function TaskEditor({task}:{task:CareerTask}){
 const {state,company,send,saving,openDocument,go}=useWorkspace(),month=state.career!.activeMonth;
 const existing=state.career!.submissions[careerKey(month,task.id)];
 const [figures,setFigures]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(existing?.figures??{}).map(([k,v])=>[k,(v/100).toFixed(2)])));
 const [responses,setResponses]=useState<Record<string,string>>(existing?.responses??{}),[evidence,setEvidence]=useState<string[]>(existing?.evidence??[]),[dirty,setDirty]=useState(false),[error,setError]=useState('');
 const locked=!!state.career!.closed[month];useUnloadWarning(dirty);
 async function save(status:'draft'|'submitted'){setError('');try{
  const parsed=Object.fromEntries(Object.entries(figures).filter(([,v])=>v.trim()).map(([k,v])=>[k,parseMoney(v)]));
  const submission:CareerSubmission={month,taskId:task.id,status,figures:parsed,responses,evidence,updatedAt:''};
  if(await send({type:'saveCareerSubmission',submission}))setDirty(false);
 }catch(e){setError((e as Error).message);}}
 return <Panel title={task.title} subtitle={`${task.requestor} · internal target ${task.due} (calendar-day practice target)`}><div className="panel-body career-fields">
 <p>{task.brief}</p><div className="form-row"><Button variant="outline" onClick={()=>go(task.view==='career'?'career':task.view)}><ArrowRight size={15}/>Open working area</Button><Status tone={existing?.status==='submitted'?'success':'warning'}>{existing?.status??'Not started'}</Status></div>
 {task.figures.length>0&&<div className="career-answer-grid">{task.figures.map(f=><label key={f.id}>{f.label} (AUD)<Input aria-label={f.label} inputMode="decimal" placeholder="Your calculation" disabled={locked||saving} value={figures[f.id]??''} onChange={e=>{setFigures({...figures,[f.id]:e.target.value});setDirty(true);}}/></label>)}</div>}
 {task.responses.map(r=><label key={r.id}>{r.label}<span className="career-help">{r.guidance}</span><Textarea aria-label={r.label} rows={4} maxLength={5000} disabled={locked||saving} value={responses[r.id]??''} placeholder="Your conclusion, supporting facts and next actions…" onChange={e=>{setResponses({...responses,[r.id]:e.target.value});setDirty(true);}}/></label>)}
 <fieldset className="career-evidence"><legend>Evidence supporting your work</legend>{task.evidence.map(id=><label key={id}><input type="checkbox" checked={evidence.includes(id)} disabled={locked||saving} onChange={e=>{setEvidence(e.target.checked?[...evidence,id]:evidence.filter(v=>v!==id));setDirty(true);}}/><button type="button" onClick={()=>openDocument(id)}>{id} · {company.documents.find(d=>d.id===id)?.title}</button></label>)}</fieldset>
 {dirty&&<Callout tone="warning">Unsaved changes. Save this draft before changing tasks or leaving the desk. Reloading or navigating away may discard this form.</Callout>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 <div className="form-row"><Button variant="outline" disabled={saving||locked} onClick={()=>save('draft')}><NotebookPen size={15}/>Save draft</Button><Button disabled={saving||locked} onClick={()=>save('submitted')}><Check size={15}/>Submit for checks</Button></div>
 <small className="career-help">Submission checks amounts, evidence links and response completeness. It does not evaluate the correctness of your narrative, certify a real approval or make the AFS statutory-complete.</small>
 </div></Panel>;
}

function ForecastEditor(){
 const {state,company,send,saving,openDocument}=useWorkspace(),month=state.career!.activeMonth;
 const existing=state.career!.forecasts[month],initial=existing??blankForecast(month),locked=!!state.career!.closed[month];
 const [draft,setDraft]=useState<CareerForecast>(initial),[values,setValues]=useState(()=>initial.weeks.map(w=>Object.fromEntries(FORECAST_FIELDS.map(f=>[f.id,(w[f.id]/100).toFixed(2)]))));
 const [reserve,setReserve]=useState((initial.minimumCash/100).toFixed(2)),[dirty,setDirty]=useState(false),[error,setError]=useState('');useUnloadWarning(dirty);
 let calculated:CareerForecast|undefined;
 try{calculated={...draft,minimumCash:parseMoney(reserve),weeks:values.map(w=>Object.fromEntries(FORECAST_FIELDS.map(f=>[f.id,parseMoney(w[f.id]||'0')])) as CareerForecast['weeks'][number])};}catch{}
 const opening=careerMetrics(company,state,month).bank,baseline=calculated?forecastSchedule(opening,calculated):[],stress=calculated?forecastSchedule(opening,calculated,true):[];
 async function save(status:'draft'|'submitted'){setError('');if(!calculated){setError('Enter valid amounts in every week and the minimum cash reserve.');return;}if(await send({type:'saveCareerForecast',forecast:{...calculated,status,updatedAt:''}}))setDirty(false);}
 return <><div className="stats-grid"><Stat label="Opening operating bank" value={<Money value={opening}/>} detail="Live month-end ledger, not a forecast plug"/><Stat label="Lowest base-case cash" value={baseline.length?<Money value={Math.min(opening,...baseline.map(w=>w.closing))}/>: '—'}/><Stat label="Lowest stressed cash" value={stress.length?<Money value={Math.min(opening,...stress.map(w=>w.closing))}/>: '—'}/><Stat label="Base-case weeks below reserve" value={baseline.filter(w=>w.headroom<0).length} detail="Uses your minimum-cash assumption"/></div>
 <Panel title="13-week cash forecast" subtitle="Enter expected cash, not accrual profit. All inputs are positive inflows or positive payments; funding has separate columns."><div className="panel-body career-fields"><Callout>The stress case collects 85% of each forecast receipt two weeks later, with no automatic funding. Receipts shifted beyond week 13 are outside this window, not written off. Do not double-count supplier-paid overheads in both categories.</Callout><label>Minimum cash reserve (AUD)<Input value={reserve} disabled={locked||saving} onChange={e=>{setReserve(e.target.value);setDirty(true);}} aria-label="Minimum cash reserve" inputMode="decimal"/></label></div>
 <DataTable headers={['Week',...FORECAST_FIELDS.map(f=>f.label),'Closing','Stressed closing']}><>{values.map((w,i)=><Row key={i}><Cell>{i+1}<p>{baseline[i]?.date}</p></Cell>{FORECAST_FIELDS.map(f=><Cell key={f.id}><Input className="career-forecast-input" aria-label={`Week ${i+1} ${f.label}`} inputMode="decimal" value={w[f.id]} disabled={locked||saving} onChange={e=>{setValues(values.map((row,n)=>n===i?{...row,[f.id]:e.target.value}:row));setDirty(true);}}/></Cell>)}<Cell className="number">{baseline[i]&&<Money value={baseline[i].closing}/>}</Cell><Cell className="number">{stress[i]&&<Money value={stress[i].closing}/>}</Cell></Row>)}</></DataTable>
 <div className="panel-body career-fields"><label>Collection, timing and payment assumptions<Textarea rows={5} maxLength={5000} value={draft.assumptions} disabled={locked||saving} onChange={e=>{setDraft({...draft,assumptions:e.target.value});setDirty(true);}}/></label><label>Liquidity actions, decisions and funding approvals<Textarea rows={4} maxLength={5000} value={draft.actions} disabled={locked||saving} onChange={e=>{setDraft({...draft,actions:e.target.value});setDirty(true);}}/></label>
 <fieldset className="career-evidence"><legend>Forecast evidence</legend>{[`CEO-${month}`,`BANK-${month}`,`STMT-C7-${month}`].map(id=><label key={id}><input type="checkbox" disabled={locked||saving} checked={draft.evidence.includes(id)} onChange={e=>{setDraft({...draft,evidence:e.target.checked?[...draft.evidence,id]:draft.evidence.filter(v=>v!==id)});setDirty(true);}}/><button type="button" onClick={()=>openDocument(id)}>{id}</button></label>)}</fieldset>
 {dirty&&<p className="career-help">Unsaved forecast. Save before leaving this screen.</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 <div className="form-row"><Button variant="outline" disabled={locked||saving} onClick={()=>save('draft')}>Save forecast draft</Button><Button disabled={locked||saving} onClick={()=>save('submitted')}>Submit forecast</Button>{existing&&<Button variant="outline" onClick={()=>downloadFile(`cash-forecast-${month}.csv`,careerForecastCSV(company,state,month),'text/csv')}><Download size={15}/>Export saved forecast</Button>}</div><small>Changing the forecast reopens the linked liquidity recommendation. Posting journals reopens current-month submissions and the forecast so they cannot silently retain stale sign-offs.</small></div></Panel></>;
}

export function CareerCloseControls(){
 const {state,company,send,saving}=useWorkspace(),[reason,setReason]=useState('');if(!state.career)return null;
 const c=state.career,checks=careerEvidenceChecks(company,state),closed=!!c.closed[c.activeMonth],ready=checks.every(check=>check.remaining===0);
 return <Panel title={`Close control · ${monthLabel(c.activeMonth)}`} subtitle="Progress requires completed source processing, reconciliations and submitted role deliverables."><DataTable headers={['Control','Outstanding','What it checks']}><>{checks.map(check=><Row key={check.id}><Cell>{check.label}</Cell><Cell><Status tone={check.remaining?'warning':'success'}>{check.remaining||'Clear'}</Status></Cell><Cell>{check.detail}</Cell></Row>)}</></DataTable><div className="panel-body career-fields"><Callout tone="warning">A balanced trial balance is not proof of correct accounts. Closing records a training milestone; qualitative judgements and missing AFS evidence do not become independently approved.</Callout><label>Close conclusion / reopening reason<Textarea value={reason} rows={3} maxLength={1000} onChange={e=>setReason(e.target.value)} placeholder="State the conclusion, unresolved qualitative matters and ownership…"/></label><div className="form-row">{closed?<><Button variant="outline" disabled={saving||reason.trim().length<20} onClick={()=>send({type:'reopenCareerMonth',reason})}>Reopen latest close</Button><Button disabled={saving||c.activeMonth==='2025-12'} onClick={()=>send({type:'advanceCareerMonth'})}>Release next month<ArrowRight size={15}/></Button></>:<Button disabled={saving||!ready||reason.trim().length<20} onClick={()=>send({type:'closeCareerMonth',reason})}><LockKeyhole size={15}/>Close {monthLabel(c.activeMonth)}</Button>}</div>{closed&&c.activeMonth==='2025-12'&&<Callout tone="success">The 2025 takeover has reached its final close. Export the portfolio and full backup. No 2026 operating month has been generated.</Callout>}</div></Panel>;
}
export function CareerCloseView(){return <><PageHeading eyebrow="Own the close" title="Monthly close and supporting reconciliations" description="Save your work, check the month and submit for detailed feedback before closing."/><MonthReviewPanel/><CareerCloseControls/><BalanceReconciliationView/></>;}

function ActiveCareer(){
 const {state,company,go,send,saving,openDocument,openJournal,openExercise}=useWorkspace(),c=state.career!,month=c.activeMonth;
 const [tab,setTab]=useState('desk'),[taskId,setTaskId]=useState(''),[search,setSearch]=useState(''),[scope,setScope]=useState('all'),[page,setPage]=useState(0),[invoice,setInvoice]=useState<SourceDocument|null>(null);
 const tasks=careerTasks(company,state).filter(t=>!state.workday||taskSchedule(t.id,month,state.career!.startMonth).release<=state.workday.today),selected=tasks.find(t=>t.id===taskId)??tasks[0],metrics=careerMetrics(company,state,month);
 const work=useMemo(()=>company.exercises.filter(e=>e.expected.some(j=>j.date.startsWith(month))).map(e=>({exercise:e,grade:gradeExercise(e,state)})),[company,state,month]);
 const filtered=work.filter(w=>(scope==='all'||scope==='done'&&w.grade.correct||scope==='open'&&!w.grade.correct)&&`${w.exercise.title} ${w.exercise.module} ${w.exercise.documents.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const submitted=tasks.filter(t=>c.submissions[careerKey(month,t.id)]?.status==='submitted').length;
 const clean=work.filter(w=>w.grade.correct).length,closed=!!c.closed[month];
 function openTask(t:CareerTask){setTaskId(t.id);setTab('deliverables');}
 return <><PageHeading eyebrow={`APPOINTED ${c.startMonth}-01 · ${c.role.replaceAll('-',' ').toUpperCase()}`} title="Your finance desk" description={`${monthLabel(month)} · ${company.name} · ${closed?'Month closed; review and release the next month.':'You own the active month. The ledger only changes when you process the work.'}`} actions={<><Button variant="outline" onClick={()=>downloadFile(`LedgerLab-career-portfolio-${state.seed}.html`,careerPortfolioHTML(company,state),'text/html')}><Download size={16}/>Work portfolio</Button><Button variant="outline" onClick={()=>go('settings')}>Backup & notebook</Button></>}/>
 <div className="stats-grid"><Stat label="Source work units processed" value={`${clean} / ${work.length}`} detail="Source-linked, not tick-box completion"/><Stat label="Role deliverables submitted" value={`${submitted} / ${tasks.length}`} detail="Financial and written work"/><Stat label="Monthly profit before tax" value={<Money value={metrics.profitBeforeTax}/>} detail="Your current books; may be incomplete"/><Stat label="Operating bank in your ledger" value={<Money value={metrics.bank}/>} detail="Reconcile to the independent statement"/></div>
 <div className="career-periods" aria-label="Takeover months">{CAREER_MONTHS.filter(m=>m>=c.startMonth).map(m=><span key={m} data-active={m===month} data-closed={!!c.closed[m]}>{c.closed[m]?'✓ ':m>month?'🔒 ':''}{m.slice(-2)}</span>)}<span className="career-help">Future actuals release only after a completed close.</span></div>
 <Tabs value={tab} onValueChange={setTab} className="tab-section"><div className="tabs-scroll"><TabsList><TabsTrigger value="desk">Handover & priorities</TabsTrigger><TabsTrigger value="queue">Processing queue</TabsTrigger><TabsTrigger value="deliverables">Role deliverables</TabsTrigger><TabsTrigger value="forecast" data-career-forecast>13-week cash forecast</TabsTrigger><TabsTrigger value="close">Check answers & close</TabsTrigger></TabsList></div>
 <TabsContent value="desk"><section className="career-hero"><div><span className="career-kicker">INBOX / MANAGING DIRECTOR</span><h2>Keep the books right.<br/>Tell us what they mean.</h2><p>Process this month’s evidence, resolve exceptions and explain what management should do next. Start with cash, payroll and supply continuity, not the prettiest working paper.</p><div className="form-row"><Button onClick={()=>openDocument('HANDOVER')}><FileText size={16}/>Read the handover</Button><Button variant="outline" onClick={()=>openDocument(`CEO-${month}`)}>This month’s brief</Button></div></div></section>
 <div className="career-task-grid">{tasks.map(t=><button className="career-task-card" data-career-open={t.id} key={t.id} onClick={()=>openTask(t)}><div><span>{t.area}</span><Status tone={c.submissions[careerKey(month,t.id)]?.status==='submitted'?'success':'neutral'}>{c.submissions[careerKey(month,t.id)]?.status??'To do'}</Status></div><h3>{t.title}</h3><p>{t.requestor} · target {t.due}</p><ArrowRight size={17}/></button>)}</div>
 <Callout>Internal targets are fictional company deadlines, not legal filing dates. In daily mode they use Monday–Friday without public holidays. On-the-job mode hides worked answers. Switching to guided mode is allowed, but assistance remains visible in your portfolio.</Callout><Button variant="outline" disabled={saving} onClick={()=>send({type:'setMode',mode:state.mode==='exam'?'guided':'exam'})}>{state.mode==='exam'?'Enable guided support':'Return to on-the-job mode'}</Button>
 </TabsContent>
 <TabsContent value="queue"><Panel title="Unprocessed evidence and monthly work" subtitle="A source work unit can contain an invoice plus later settlements, or several related payroll postings. Process the facts, not an answer template." action={<Button variant="outline" onClick={()=>downloadFile(`takeover-source-${month}.zip`,sourcePack(company,state,month),'application/zip')}><Download size={15}/>Source pack</Button>}><div className="toolbar"><SearchField value={search} onChange={v=>{setSearch(v);setPage(0);}} placeholder="Search source, party or work area…"/><SelectField label="Work status" value={scope} onChange={v=>{setScope(v);setPage(0);}} options={[{value:'all',label:'All work'},{value:'open',label:'Not complete'},{value:'done',label:'Processed correctly'}]}/><Button variant="outline" disabled={closed} onClick={()=>openJournal({date:state.workday?[state.workday.today,monthEnd(month)].sort()[0]:monthEnd(month)})}><Plus size={15}/>Blank journal</Button></div>
 <DataTable headers={['Source / work unit','Area','Status','Process']}><>{filtered.slice(page*20,page*20+20).map(({exercise:e,grade})=>{
  const source=company.documents.find(d=>d.id===e.expected[0].sourceId),capture=source&&source.date.startsWith(month)&&['Sales invoice','Supplier invoice','Credit note','Supplier credit note'].includes(source.kind);
  return <Row key={e.id}><Cell><button className="reference" onClick={()=>openDocument(e.documents[0])}>{e.documents[0]}</button><p>{source?.title}</p></Cell><Cell>{e.module}</Cell><Cell><Status tone={grade.correct?'success':grade.started?'warning':'neutral'}>{grade.correct?'Processed':grade.started?'Part processed / needs review':'Not processed'}</Status>{grade.assisted&&<p>Assisted</p>}</Cell><Cell><div className="form-row">{capture&&<Button variant="outline" size="sm" disabled={closed} onClick={()=>setInvoice(source!)}>Capture invoice</Button>}<Button variant="outline" size="sm" disabled={closed} onClick={()=>openJournal({sourceId:e.expected[0].sourceId,date:e.expected[0].date,description:source?.title})}>Journal / cash entry</Button>{state.mode==='guided'&&<Button variant="ghost" size="sm" onClick={()=>openExercise(e.id)}>Guidance</Button>}</div></Cell></Row>;
 })}</></DataTable><div className="table-footer"><span>{filtered.length} work units · page {page+1}</span><div className="form-row"><Button variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={(page+1)*20>=filtered.length} onClick={()=>setPage(page+1)}>Next</Button></div></div></Panel>
 <Callout>Invoices may be captured from source data, but you select the ledger coding. Receipts and payments are separate entries. Linking the source is sufficient for checks; no exercise ID is required. Capture must not duplicate an invoice already inherited or posted.</Callout></TabsContent>
 <TabsContent value="deliverables"><div className="career-work-layout"><nav className="career-deliverable-list" aria-label="Role deliverables">{tasks.map(t=><button key={t.id} data-active={t.id===selected?.id} onClick={()=>setTaskId(t.id)}>{t.title}<small>{c.submissions[careerKey(month,t.id)]?.status??'Not started'}</small></button>)}</nav><>{selected?<TaskEditor key={`${month}|${selected.id}|${c.submissions[careerKey(month,selected.id)]?.updatedAt??''}`} task={selected}/>:<p>No formal deliverable has been requested yet. Use Today for current work.</p>}</></div></TabsContent>
 <TabsContent value="forecast">{!state.workday||state.workday.today>=closePackDate(month)?<ForecastEditor key={`${month}|${c.forecasts[month]?.updatedAt??''}`}/>:<p>The formal forecast opens on {closePackDate(month)}. Use the weekly cash assignments in Today first.</p>}</TabsContent>
 <TabsContent value="close"><MonthReviewPanel/><CareerCloseControls/></TabsContent></Tabs>
 <Callout tone="warning">2025 AUD teaching case. Inherited errors, source processing, quantitative outputs and close controls are checked. Written recommendations, forecast realism and statutory completeness are not independently assessed. Full-year comparative AFS evidence is deliberately incomplete.</Callout>
 {invoice&&<InvoiceForm source={invoice} onClose={()=>setInvoice(null)}/>}</>;
}
export function CareerView(){const {state}=useWorkspace();return state.career?<ActiveCareer key={`${state.career.startedAt}|${state.career.activeMonth}`}/>:<CareerSetup/>;}
