'use client';
import {useState} from 'react';
import {FileText,Save,ArrowUpRight,Check,PenLine} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Textarea} from '@/components/ui/textarea';
import {useWorkspace} from './context';
import {Panel,Status,Button,DataTable,Row,Cell,Amount,Callout,Completion} from './shared';
import {financialNotes,type FinancialNote} from '@/lib/accounting/financial-notes';

export function FinancialNotesView({to}:{to:string}){
 const {company,state}=useWorkspace(),[selected,setSelected]=useState('01'),notes=financialNotes(company,state,to),note=notes.find(n=>n.id===selected)??notes[0],completed=notes.filter(n=>state.disclosures?.[n.id]?.completed).length;
 if(!notes.length)return <Callout title="Year-end disclosure evidence is not released">Use the live statements and your management deliverables for this month. Annual notes, year-end estimates and the AFS evidence-gap assessment open in December; this interim pack is not a statutory set of accounts.</Callout>;
 return <><Callout title="Prepare a connected set of notes">The tables follow your posted ledger as at {to}. Source schedules and case assumptions are identified separately. Save an assessment for each note; your text is included in the AFS download. Posting another journal reopens completed assessments for review.</Callout><div className="notes-layout"><Panel title="Financial statement notes" subtitle="18 areas to prepare and assess"><div className="panel-body"><Completion done={completed} total={notes.length} label="Assessments completed"/></div><nav aria-label="Financial statement note index" className="note-index">{notes.map(n=><button key={n.id} className={n.id===selected?'active':''} onClick={()=>setSelected(n.id)}><span>{n.id}</span><strong>{n.title}</strong>{state.disclosures?.[n.id]?.completed?<Check size={16}/>:state.disclosures?.[n.id]?.text?<PenLine size={14}/>:null}</button>)}</nav></Panel><NoteDetail key={note.id} note={note}/></div></>;
}
function NoteDetail({note}:{note:FinancialNote}){
 const {state,send,saving,openDocument}=useWorkspace(),existing=state.disclosures?.[note.id],[text,setText]=useState(existing?.text??''),[completed,setCompleted]=useState(existing?.completed??false),dirty=text!==(existing?.text??'')||completed!==(existing?.completed??false);
 return <div><Panel title={`Note ${note.id} · ${note.title}`} action={<Status tone={existing?.completed?'success':'neutral'}>{existing?.completed?'Assessment complete':'Assessment open'}</Status>}><div className="panel-body prose-accounting">{note.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div>{note.tables.map((table,i)=><div className="note-table" key={i}><h3>{table.title}</h3><DataTable headers={['Line item',...table.columns]}><>{table.rows.map((r,index)=><Row className={r.total?'total-row':undefined} key={index}><Cell>{r.label}</Cell>{r.values.map((v,k)=><Cell className="number" key={k}><Amount value={v}/></Cell>)}</Row>)}</></DataTable></div>)}<div className="panel-body"><h3 className="section-label" style={{marginTop:0}}>Source evidence</h3><div className="quick-actions">{note.documents.map(id=><Button key={id} variant="outline" onClick={()=>openDocument(id)}><FileText size={15}/>{id}</Button>)}</div>{note.source&&<p className="mt-4 text-sm"><a className="small-link" href={note.source.url} target="_blank" rel="noreferrer">{note.source.label}<ArrowUpRight size={15}/></a></p>}</div></Panel><Panel title="Your disclosure assessment" subtitle="Document what is supported, what you concluded, and what remains outstanding"><div className="panel-body"><ul className="assessment-prompts">{note.prompts.map((p,i)=><li key={i}>{p}</li>)}</ul><label htmlFor={`note-${note.id}`} className="section-label">Draft note / assessment and outstanding evidence</label><Textarea id={`note-${note.id}`} rows={9} maxLength={15000} value={text} onChange={e=>{setText(e.target.value);setCompleted(false);}} placeholder="Supported disclosure wording…&#10;Significant judgments and reconciliations…&#10;Evidence still required…&#10;Conclusion and cross-reference to workpaper…"/><div className="form-row section-gap"><Checkbox id={`note-check-${note.id}`} checked={completed} onCheckedChange={v=>setCompleted(!!v)}/><label htmlFor={`note-check-${note.id}`}>I have completed my assessment of this note</label></div><div className="form-actions"><span className="text-sm text-muted-foreground">{dirty?'Unsaved changes':existing?'Saved to your financial statements':'No assessment saved yet'}</span><Button disabled={saving||!dirty||(completed&&!text.trim())} onClick={()=>send({type:'saveDisclosure',disclosure:{id:note.id,text,completed,updatedAt:''}})}><Save size={16}/>Save assessment</Button></div></div></Panel></div>;
}
