'use client';
import {useState,useRef} from 'react';
import {Upload,Download,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useWorkspace} from './context';
import {Button,Callout,DataTable,Row,Cell,Money} from './shared';
import {importJournalCSV} from '@/lib/accounting/imports';
import {csv,downloadFile} from '@/lib/accounting/exports';
import {sum} from '@/lib/accounting/money';
import type {Journal} from '@/lib/accounting/types';
export function ImportJournals(){const {company,state,journals,send,saving}=useWorkspace(),[open,setOpen]=useState(false),[preview,setPreview]=useState<Journal[]>([]),[error,setError]=useState(''),[filename,setFilename]=useState(''),file=useRef<HTMLInputElement>(null);
 async function read(f:File){setError('');setPreview([]);setFilename(f.name);try{if(f.size>1_000_000)throw new Error('Use a CSV smaller than 1 MB.');const result=importJournalCSV(await f.text(),company,new Set(journals.map(j=>j.id)),state.periodLocked);setPreview(result.journals);}catch(e){setError((e as Error).message);}}
 function template(){downloadFile('journal-import-template.csv',csv(['Journal ID','Date','Reference','Source document','Narration','Module','Account','Contact','Debit AUD','Credit AUD','Exercise'],[['IMPORT-001','2025-12-31','MY-SUPPORT','','Example office supplies accrual','CSV import','6220','','150.00','0.00',''],['IMPORT-001','2025-12-31','MY-SUPPORT','','Example office supplies accrual','CSV import','2100','','0.00','150.00','']]),'text/csv');}
 return <><Button variant="outline" onClick={()=>setOpen(true)}><Upload size={16}/>Import journal CSV</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="journal-dialog"><DialogHeader><DialogTitle>Import journals</DialogTitle><DialogDescription>Validate all rows before posting the batch. No entries are posted during preview.</DialogDescription></DialogHeader><div className="form-row"><Button variant="outline" onClick={template}><Download size={16}/>Download template</Button><Button variant="outline" onClick={()=>file.current?.click()}><Upload size={16}/>Choose CSV</Button><input ref={file} type="file" accept="text/csv,.csv" className="hidden" onChange={e=>{if(e.target.files?.[0])read(e.target.files[0]);e.target.value='';}}/></div><Callout>Use one row per debit or credit line. Rows with the same Journal ID form one entry. Amounts are in AUD dollars; account and contact codes must match the case. December 2025 and January 2026 are supported. Duplicate IDs, unbalanced journals and invalid dates are rejected.</Callout>{filename&&<span className="date-small">{filename}</span>}{error&&<div className="form-error" role="alert">{error}</div>}{preview.length>0&&<><DataTable headers={['Journal','Date','Narration','Lines','Debit total']}><>{preview.map(j=><Row key={j.id}><Cell>{j.id}</Cell><Cell>{j.date}</Cell><Cell>{j.description}</Cell><Cell>{j.lines.length}</Cell><Cell className="number"><Money value={sum(j.lines.map(l=>l.debit))}/></Cell></Row>)}</></DataTable><Callout tone="success">{preview.length} journals pass posting validation. This checks accounting structure; you still need to assess the substance and supporting evidence.</Callout><Button disabled={saving} onClick={async()=>{if(await send({type:'importJournals',journals:preview})){setOpen(false);setPreview([]);}}}><Check size={16}/>Post {preview.length} journals</Button></>}</DialogContent></Dialog></>;
}
