'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,ExternalLink} from 'lucide-react';
import {useWorkspace} from './context';
import {PageHeading,Panel,Button,SearchField,SelectField,Status,DataTable,Row,Cell,Amount,Callout} from './shared';
import {LESSONS} from '@/lib/accounting/lessons';
import {ACCOUNT_MAP} from '@/lib/accounting/accounts';
export function KnowledgeView(){const {openJournal}=useWorkspace(),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[selected,setSelected]=useState<string|null>(null),lesson=LESSONS.find(l=>l.id===selected),list=LESSONS.filter(l=>(category==='all'||l.category===category)&&`${l.title} ${l.objective} ${l.explanation.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 if(lesson)return <><Button variant="outline" onClick={()=>setSelected(null)} className="mb-6"><ArrowLeft size={16}/>Back to accounting desk</Button><PageHeading eyebrow={`${lesson.category} · ${lesson.level}`} title={lesson.title} description={lesson.objective}/><div className="grid-main"><Panel><div className="padded lesson-prose">{lesson.explanation.map((p,i)=><p key={i} style={{marginBottom:18}}>{p}</p>)}<h3>Worked journal example</h3><p>{lesson.example.narration}</p><DataTable headers={['Account','Debit','Credit']}><>{lesson.example.lines.map((l,i)=><Row key={i}><Cell>{l.account} · {ACCOUNT_MAP[l.account]?.name}</Cell><Cell className="number"><Amount value={l.debit}/></Cell><Cell className="number"><Amount value={l.credit}/></Cell></Row>)}</></DataTable><Callout>These examples are separate from the December task answers. Posting one adds an extra practice transaction to your case.</Callout><Button variant="outline" onClick={()=>openJournal({description:`Concept practice: ${lesson.title}`,lines:lesson.example.lines})}>Try the entry in your ledger<ArrowRight size={16}/></Button>{lesson.sourceUrl&&<p style={{marginTop:25}}><a className="small-link" href={lesson.sourceUrl} target="_blank" rel="noreferrer">{lesson.sourceLabel}<ExternalLink size={14}/></a></p>}</div></Panel><div><Panel title="Before you sign off"><div className="panel-body lesson-prose"><ul>{lesson.checklist.map(c=><li key={c}>{c}</li>)}</ul></div></Panel><Panel title="Common traps"><div className="panel-body lesson-prose"><ul>{lesson.pitfalls.map(p=><li key={p}>{p}</li>)}</ul></div></Panel></div></div></>;
 return <><PageHeading eyebrow="Your accounting desk reference" title="Understand the entry" description="Practical explanations, worked examples and review checklists across the accounting cycle."/><div className="toolbar toolbar-top"><SearchField value={search} onChange={setSearch} placeholder="Search accounting concepts…"/><SelectField value={category} onChange={setCategory} label="Knowledge category" options={[{value:'all',label:'All topics'},...[...new Set(LESSONS.map(l=>l.category))].map(c=>({value:c,label:c}))]}/><Status>{list.length} lessons</Status></div><div className="exercise-grid">{list.map(l=><button className="exercise-card lesson-card" key={l.id} onClick={()=>setSelected(l.id)}><div className="exercise-card-head"><span className="exercise-module">{l.category}</span><BookOpen size={18} color="#7595c0"/></div><h3>{l.title}</h3><p>{l.objective}</p><div className="exercise-card-footer"><Status>{l.level}</Status><ArrowRight size={16}/></div></button>)}</div></>;
}
