/** Second-pass regressions. These are isolated test fixtures, not distributable case answers. */
import assert from 'node:assert/strict';
import { parseMoney } from '../../lib/accounting/money';
import { initialState, applyCommand, journalsFor } from '../../lib/accounting/engine';
import { companyForState } from '../../lib/accounting/career';
import { daySummary } from '../../lib/accounting/workday';
import { filterQueue, nextAction, priorityQueue, needsAttention, followUpDue, pageOf, type TaskRow } from '../../lib/desktop/task-queue';
import { LocalWorkspaceStore, LocalStoreError, LOCAL_WORKSPACE_KEY, LOCAL_STATE_BYTE_LIMIT, validLocalEnvelope } from '../../lib/workspace/local-store';
import { MAX_STATE_BYTES } from '../../lib/workspace/service';
import { ledgerChecks } from '../../lib/desktop/ledger-checks';
import { incomingMail } from '../../lib/desktop/mail-desk';
import { workspaceSearchIndex, searchWorkspace } from '../../lib/desktop/search-index';
import type { Journal, WorkspaceEnvelope } from '../../lib/accounting/types';
let checks = 0;
const eq = (a: unknown, b: unknown, label: string) => { assert.deepEqual(a, b, label); checks++; };
const ok = (a: unknown, label: string) => { assert.ok(a, label); checks++; };
const rejects = (fn: () => unknown, label: string) => { assert.throws(fn, Error, label); checks++; };
for (const [input, cents] of [['0',0],['1',100],['1.',100],['1.2',120],['1,234.56',123456],['-1,234.56',-123456],[' 123.45 ',12345],['1,000,000.00',100000000],['1000000000.00',100000000000],['-0.01',-1]] as const)
    eq(parseMoney(input), cents, 'Exact parsing: ' + input);
for (const input of ['1,2','12,34','1,234,56','1.234,56','1234,567','1,,234','1,234.567','--1','NaN','Infinity','1e4','1 234.56','', '1000000000.01','-1000000000.01'])
    rejects(() => parseMoney(input), 'Reject ambiguous/invalid money: ' + input);
const now = '2026-09-18T08:00:00.000Z';
const state = applyCommand(initialState(271828), { type:'startCareer', seed:271828, startMonth:'2025-07', role:'financial-manager', scenario:'messy', daily:true, confirmation:'START TAKEOVER' }, now);
const company = companyForState(state), model = { state, company, journals:journalsFor(company,state), displayName:'Test', generation:0, saving:false, saveStatus:'Saved', error:'', reportingMonth:'2025-07' };
const initial:WorkspaceEnvelope = { state, revision:0, updatedAt:now };
const changed:WorkspaceEnvelope = { state:{...state,notes:'A confirmed notebook change'},revision:1,updatedAt:now };
let raw:string|null = null, quota=false, denied=false, writes=0;
const port = { getItem(key:string) { eq(key,LOCAL_WORKSPACE_KEY,'Stable storage key'); if(denied)throw Error('Denied'); return raw; }, setItem(_key:string,value:string) { if(quota)throw Error('Quota'); raw=value; writes++; } };
const store = new LocalWorkspaceStore(()=>port,initial);
eq(store.mode,'browser','Storage availability is explicit');
eq(store.read(),initial,'First run uses a seed without overwriting storage');
eq(writes,0,'Reading a first case does not write');
store.write(changed);eq(store.read(),changed,'Confirmed browser write roundtrip');
const previous=raw;quota=true;
rejects(()=>store.write({...changed,revision:2,state:{...state,notes:'unsaved'}}),'Quota rejects write');
eq(raw,previous,'Quota leaves original stored bytes intact');
eq(store.read(),changed,'Quota does not silently switch to memory state');
eq(store.mode,'browser','Quota does not masquerade as successful memory save');
quota=false;denied=true;rejects(()=>store.read(),'Late storage denial does not supply a fresh case');denied=false;
raw='{ broken';rejects(()=>store.read(),'Malformed storage blocks loading');eq(raw,'{ broken','Malformed data is not overwritten');
eq(store.recoveryText(),'{ broken','Original bytes remain downloadable');
rejects(()=>store.recover(initial,''),'Recovery requires exact confirmation');eq(raw,'{ broken','Rejected recovery preserves bytes');
store.recover(initial,'REPLACE SAVED DATA');eq(store.read(),initial,'Explicit confirmed recovery works');
raw=null;rejects(()=>store.read(),'Externally removed storage is a conflict, not a reset');
raw=JSON.stringify({...initial,revision:-1});rejects(()=>store.read(),'Invalid revisions fail validation');
const memory=new LocalWorkspaceStore(()=>{throw Error('Opaque origin');},initial);
eq(memory.mode,'memory','Unavailable initial storage is visibly memory-only');memory.write(changed);eq(memory.read(),changed,'Memory mode can export its session progress');
const returned=memory.read();returned.state.notes='mutated';eq(memory.read().state.notes,changed.state.notes,'Caller cannot mutate stored snapshot');
eq(LOCAL_STATE_BYTE_LIMIT,MAX_STATE_BYTES,'Offline and hosted state byte limits agree');
ok(!validLocalEnvelope({...initial,updatedAt:'wrong'}),'Envelope timestamp validated');
ok(!validLocalEnvelope({...initial,state:{}}),'Invalid state rejected');
ok(new LocalStoreError('message','quota') instanceof Error,'Typed storage errors remain ordinary errors');
const base=daySummary(state).tasks[0];
const rows:TaskRow[] = [
    {...base,task:{...base.task,id:'normal',due:'2025-06-30',priority:'Normal'},status:{state:'Not started',complete:false,detail:'',differences:[]}},
    {...base,task:{...base.task,id:'critical',due:'2025-07-02',priority:'Critical'},status:{state:'Not started',complete:false,detail:'',differences:[]}},
    {...base,task:{...base.task,id:'wait',due:'2025-06-29'},status:{state:'Waiting',complete:false,detail:'',differences:[]}},
    {...base,task:{...base.task,id:'done'},status:{state:'Complete',complete:true,detail:'',differences:[]}},
];
const queueState=structuredClone(state);
queueState.workday!.submissions.wait={taskId:'wait',status:'blocked',figures:{},decision:'',note:'',evidence:[],blocker:'missing records',owner:'Operations',followUp:'2025-07-04',updatedAt:now};
const before=JSON.stringify(rows);
eq(nextAction(rows,queueState)?.task.id,'critical','Critical controls beat routine overdue processing');
eq(priorityQueue(rows,queueState).at(-1)?.task.id,'done','Completed work sorts last');
eq(filterQueue(rows,queueState,'waiting').length,1,'Waiting filter');
eq(filterQueue(rows,queueState,'completed').length,1,'Completed filter');
eq(filterQueue(rows,queueState,'open').length,3,'Open includes blockers');
eq(filterQueue(rows,queueState,'overdue').length,2,'Overdue retains blocked deadline');
eq(filterQueue(rows,queueState,'all','Operations')[0]?.task.id,'wait','Owner is searchable');
ok(needsAttention(rows[0],queueState),'Overdue needs attention');
ok(!followUpDue(rows[2],queueState),'Future follow-up is not due');
eq(nextAction([rows[2]],queueState),undefined,'Waiting-only queue is not actionable');
queueState.workday!.submissions.wait.followUp='2025-07-01';
ok(followUpDue(rows[2],queueState),'Follow-up due on scenario date');
eq(nextAction([rows[2]],queueState)?.task.id,'wait','Due follow-up becomes actionable');
eq(JSON.stringify(rows),before,'Triage never mutates source task order');
eq(filterQueue([{...base,task:{...base.task,figures:[{id:'answer',label:'Test',expected:987654321}]}}],state,'all','987654321').length,0,'Queue search excludes expected figures');
eq(pageOf(Array.from({length:45},(_,i)=>i),900).rows,[40,41,42,43,44],'Pagination clamps to last page');
eq(pageOf([],20).from,0,'Empty list starts at zero');
eq(pageOf([1,2],NaN).page,0,'Invalid page defaults safely');
eq(pageOf([1,2],1,0).rows,[2],'Page size has a positive lower bound');
const sample=(id:string):Journal=>({id,date:'2025-07-01',reference:'SAME-REFERENCE',description:'Advisory duplicate fixture',module:'Manual journal',sourceId:'TB-OPEN',origin:'learner',lines:[{account:'1000',debit:1000,credit:0},{account:'4000',debit:0,credit:1000}]});
const a=sample('J-ONE'),b=sample('J-TWO');
const original=JSON.stringify(state);
let report=ledgerChecks({...model,journals:[a,b]});
ok(report.findings.some(f=>f.id==='duplicate:J-ONE'),'Exact-source duplicates get a review flag');
eq(report.findings.find(f=>f.id==='duplicate:J-ONE')?.severity,'review','Duplicates are not automatically declared errors');
report=ledgerChecks({...model,journals:[a,{...b,sourceId:'DIFFERENT',reference:'DIFFERENT'}]});
ok(!report.findings.some(f=>f.id.startsWith('duplicate:')),'Distinct sources do not produce false duplicates');
const reversal:Journal={...sample('J-REV'),reverses:a.id,date:'2025-07-01',lines:a.lines.map(l=>({...l,debit:l.credit,credit:l.debit}))};
report=ledgerChecks({...model,journals:[a,b,reversal]});
ok(!report.findings.some(f=>f.id.startsWith('duplicate:')),'Reversal and replacement are not duplicated work');
ok(ledgerChecks({...model,journals:[a,a]}).findings.some(f=>f.id==='duplicate-id:J-ONE'),'Duplicate identifiers flagged');
ok(ledgerChecks({...model,journals:[{...a,lines:[{account:'1000',debit:3,credit:0}]}]}).findings.some(f=>f.id==='amount:J-ONE'),'Unbalanced entries flagged');
ok(ledgerChecks({...model,journals:[{...a,lines:[{account:'INVALID',debit:1,credit:0},{account:'4000',debit:0,credit:1}]}]}).findings.some(f=>f.id==='account:J-ONE'),'Unknown accounts flagged');
ok(ledgerChecks({...model,journals:[{...a,lines:[{account:'1100',debit:1,credit:0},{account:'4000',debit:0,credit:1}]}]}).findings.some(f=>f.id==='account:J-ONE'),'Missing control contacts flagged');
const suspense={...a,lines:[{account:'6990',debit:12,credit:0},{account:'4000',debit:0,credit:12}]};
ok(ledgerChecks({...model,journals:[suspense]}).findings.some(f=>f.id==='suspense'),'Suspense uses actual posting balance');
eq(ledgerChecks({...model,journals:[{...a,date:'2025-08-01'}]}).journalCount,0,'Future journals excluded from selected available scope');
const bank={id:'B-TEST',date:'2025-07-01',reference:'B',description:'Next-working-day feed',amount:100,balance:100};
eq(ledgerChecks({...model,company:{...company,bank:[bank]}}).bankCount,0,'Unarrived bank data excluded even with a full company input');
const tomorrow={...state,workday:{...state.workday!,today:'2025-07-02'}};
ok(ledgerChecks({...model,state:tomorrow,company:{...company,bank:[bank]}}).findings.some(f=>f.id==='bank'),'Available unmatched bank rows flagged');
const forbidden={...company};Object.defineProperty(forbidden,'solutionJournals',{get(){throw Error('Worked solution was consulted');}});
ok(ledgerChecks({...model,company:forbidden}).journalCount>=0,'Diagnostics never consult the solution');
eq(JSON.stringify(state),original,'Ledger diagnostics are read-only');
ok(incomingMail({category:'Onboarding'}),'Incoming mail counted');
ok(!incomingMail({category:'Sent'}),'Sent mail not counted as unread');
ok(!incomingMail({category:'Draft'}),'Draft mail not counted as unread');
const index=workspaceSearchIndex(model);
ok(index.some(x=>x.ref==='ledger-checks'&&x.kind==='app'),'Ledger checks are discoverable in global search');
eq(searchWorkspace(index,'',-5).length,0,'Negative result limit clamped');
ok(searchWorkspace(index,'',NaN).length>0,'Invalid result limit has sensible default');
console.log(`Clarity/storage/triage/ledger checks: ${checks} assertions passed.`);
