/** Focused regression checks for the v2 workbook engine and source-backed templates. */
import {strict as assert} from 'node:assert';
import {writeFileSync,mkdirSync} from 'node:fs';
import {evaluateGrid,evaluateWorkbook,FORMULA_FUNCTIONS} from '../../lib/desktop/worksheet';
import {columnName,position,shiftFormula,renameSheet,insertDelete,syncWorkbook,parseDelimited,toTSV} from '../../lib/desktop/workbook-model';
import {workbookXLSX} from '../../lib/desktop/workbook-io';
import {desktopFileError,desktopStateError,DESKTOP_LIMITS,type DesktopUserFile,type DesktopWorksheet} from '../../lib/desktop/types';
import {createWorkingFile,filePayload,virtualFiles,type DesktopModel} from '../../lib/desktop/files';
import {WORKPAPER_TEMPLATES} from '../../lib/desktop/workpaper-templates';
import {initialState,applyCommand,journalsFor,validateBackup} from '../../lib/accounting/engine';
import {companyForState} from '../../lib/accounting/career';
let checks=0;const eq=(a:unknown,b:unknown,label:string)=>{assert.deepEqual(a,b,label);checks++;};const ok=(a:unknown,label:string)=>{assert.ok(a,label);checks++;};
const value=(formula:string,rows:string[][]=[])=>evaluateGrid([...rows,...Array.from({length:Math.max(0,10-rows.length)},()=>['']),[formula]])[10][0];
for(const [formula,expected] of Object.entries({'=SUM(1,2,3)':6,'=2+3*4':14,'=(2+3)*4':20,'=2^3':8,'=-2^2':4,'=10%':0.1,'=IF(1<2,"yes",1/0)':'yes','=IFERROR(1/0,"check")':'check','=ROUND(1.005,2)':1.01,'=ROUND(-1.235,2)':-1.24,'=ROUNDUP(-1.21,1)':-1.3,'=ROUNDDOWN(-1.29,1)':-1.2,'=INT(-1.2)':-2,'=MOD(-3,2)':1,'=AND(TRUE,1,2)':true,'=OR(FALSE,0,TRUE)':true,'=NOT(0)':true,'=TRIM(" a   b ")':'a b','=UPPER("ab")':'AB','=LOWER("Ab")':'ab','=LEN("cash")':4,'=LEFT("bank",2)':'ba','=RIGHT("bank",2)':'nk','=MID("bank",2,2)':'an','=VALUE("1,234.50")':1234.5,'=CONCAT("Bank", " ", 2)':'Bank 2','=ISNUMBER(2)':true,'=ISTEXT("")':true,'=ISBLANK("")':false,'=YEAR(DATE(2025,7,31))':2025,'=MONTH(EDATE(DATE(2025,1,31),1))':2,'=DAY(EDATE(DATE(2025,1,31),1))':28,'=DAY(EOMONTH(DATE(2024,2,1),0))':29,'=IFERROR(NA(),0)':0,'=1/0':'#DIV/0!','=WEBSERVICE("https://example.invalid")':'#NAME?','=HYPERLINK("javascript:alert(1)","x")':'#NAME?','=A11':'#CIRC!','=SUM(A1:ZZ1000)':'#REF!','=1e308*1e308':'#NUM!'}))eq(value(formula),expected,formula);
const data=[['North','100','2'],['South','200','3'],['North','50','4'],['text','', 'TRUE'],['=""','', '']];
for(const [f,v]of [['=SUM(B1:B5)',350],['=SUM(A4)',0],['=SUM("2",3)',5],['=SUM(C4)',0],['=COUNT(C1:C5)',3],['=COUNT(TRUE,"2")',2],['=COUNTA(A1:A5)',5],['=ISBLANK(A5)',false],['=ISBLANK(B5)',true],['=AVERAGE(B1:B5)',350/3],['=SUMIF(A1:A3,"North",B1:B3)',150],['=SUMIFS(B1:B3,A1:A3,"North",C1:C3,">2")',50],['=COUNTIF(A1:A3,"N*")',2],['=COUNTIFS(A1:A3,"North",B1:B3,">75")',1],['=AVERAGEIF(A1:A3,"North",B1:B3)',75],['=SUMPRODUCT(B1:B3,C1:C3)',1000],['=XLOOKUP("South",A1:A3,B1:B3)',200],['=XLOOKUP("West",A1:A3,B1:B3,"missing")','missing'],['=XLOOKUP("North",A1:A3,B1:B3,,0,-1)',50],['=VLOOKUP("South",A1:C3,2,FALSE)',200],['=INDEX(B1:C3,2,2)',3],['=MATCH("South",A1:A3,0)',2],['=AND(C1:C4)',true],['=SUBTOTAL(9,B1:B3)',350],['=COUNTBLANK(B1:B5)',2]] as const)eq(value(f,data),v,f);
const sheets:DesktopWorksheet[]=[{id:'main',name:'Main',cells:[['=SUM(\'Payroll data\'!$B$1:B3)'],['=\'Payroll data\'!B2']]},{id:'data',name:'Payroll data',cells:[['North','100'],['South','200'],['North','50']]}];
const file:DesktopUserFile={id:'UF-engine',name:'Engine.xlsx',folder:'Working papers/2025-07',kind:'workbook',text:'',cells:sheets[0].cells,sheets,activeSheetId:'main',createdAt:'2026-09-07T10:00:00Z',updatedAt:'2026-09-07T10:00:00Z',deleted:false};
eq(evaluateWorkbook(sheets)[0][0][0],350,'Cross-sheet SUM');renameSheet(file,'data',"Payroll O'Brien");eq(sheets[0].cells[0][0],"=SUM('Payroll O''Brien'!$B$1:B3)",'Rename escaped sheet updates qualified range');eq(evaluateWorkbook(sheets)[0][0][0],350,'Rename preserves calculation');
insertDelete(file,'data','row',1,1,false);eq(sheets[0].cells[0][0],"=SUM('Payroll O''Brien'!$B$1:B4)",'Insert expands a qualified range');eq(sheets[0].cells[1][0],"='Payroll O''Brien'!B3",'Absolute/relative refs follow inserted rows');eq(evaluateWorkbook(sheets)[0][0][0],350,'Insert preserves total');
insertDelete(file,'data','row',0,1,true);eq(sheets[0].cells[0][0],"=SUM('Payroll O''Brien'!$B$1:B3)",'Delete first range row shrinks range instead of REF');eq(evaluateWorkbook(sheets)[0][0][0],250,'Delete removes first amount');
insertDelete(file,'data','column',0,1,true);eq(sheets[0].cells[0][0],"=SUM('Payroll O''Brien'!$A$1:A3)",'Delete column updates qualified range');eq(evaluateWorkbook(sheets)[0][0][0],250,'Delete unrelated column preserves total');
eq(shiftFormula('=A1+$A1+A$1+$A$1+"A1"',2,3),'=D3+$A3+D$1+$A$1+"A1"','Relative, fixed, mixed and quoted text');eq(shiftFormula("=SUM('Pay data'!A1:B3)",1,1),"=SUM('Pay data'!B2:C4)",'Qualified range copied once');eq(shiftFormula('=A1',-1,0),'=#REF!','Copy outside grid shows REF');eq(shiftFormula('=LOG10(A1)',1,1),'=LOG10(B2)','Function name not rewritten');
for(let c=0;c<52;c++)eq(position(columnName(c)+'500'),[499,c],'Column roundtrip '+c);
for(let r=1;r<=40;r++){const dr=r%7,dc=r%9;eq(shiftFormula(`=B${r}+$C$4+C$5+$D${r}`,dr,dc),`=${columnName(1+dc)}${r+dr}+$C$4+${columnName(2+dc)}$5+$D${r+dr}`,'Mixed copy '+r);}
const fields=[['a\tb','line\nnext','"quoted"'],['1','2','']];eq(parseDelimited(toTSV(fields)),fields,'Quoted multiline clipboard roundtrip');eq(parseDelimited('a,b\n"x,y",2',','),[['a','b'],['x,y','2']],'CSV quote handling');let threw=false;try{parseDelimited('"unterminated');}catch{threw=true;}ok(threw,'Malformed pasted CSV is rejected');
eq(desktopFileError(file),null,'Multi-sheet file validates');eq(desktopFileError({...file,activeSheetId:'missing'})!==null,true,'Bad active sheet rejected');eq(desktopFileError({...file,cells:[['wrong']]})!==null,true,'Legacy mirror mismatch rejected');
const state=applyCommand(initialState(271828),{type:'startCareer',seed:271828,startMonth:'2025-07',role:'financial-manager',scenario:'messy',confirmation:'START TAKEOVER'}),company=companyForState(state);const model:DesktopModel={company,state,journals:journalsFor(company,state),displayName:'Finance team',saving:false,saveStatus:'Saved',error:'',generation:0};
let saved=state;for(const [template,title]of Object.entries(WORKPAPER_TEMPLATES)){
 const f=createWorkingFile(model,template,'2026-09-07T10:00:00Z','UF-template-'+template);eq(desktopFileError(f),null,title+' validates');const values=evaluateWorkbook(f.sheets!);ok(!values.flat(2).some(v=>typeof v==='string'&&/^#(?:REF!|VALUE!|CIRC!|NAME\?|ERROR!|DIV\/0!)/.test(v)),title+' formulas have no errors');
 saved=applyCommand(saved,{type:'saveDesktopFile',file:f,expectedUpdatedAt:null});eq(validateBackup(saved),null,title+' saves through production domain command');const raw=workbookXLSX(f);ok(raw[0]===80&&raw[1]===75,title+' exports genuine XLSX');
 if(process.env.LEDGERLAB_DESKTOP_TEST_OUTPUT&&['bank','afs','payroll'].includes(template)){mkdirSync(process.env.LEDGERLAB_DESKTOP_TEST_OUTPUT,{recursive:true});writeFileSync(`${process.env.LEDGERLAB_DESKTOP_TEST_OUTPUT}/v2-${template}.xlsx`,raw);}
}
eq(desktopStateError(saved.desktop),null,'All thirteen templates fit workspace storage');const sm={...model,state:saved},vf=virtualFiles(sm).find(f=>f.id==='UF-template-bank')!;const payload=filePayload(vf,sm);ok(new TextDecoder().decode(payload.content as Uint8Array).includes('sheet5.xml'),'Explorer exports all five bank workbook sheets');
const maxfile=createWorkingFile(model);delete maxfile.sheets;delete maxfile.activeSheetId;maxfile.cells=Array.from({length:DESKTOP_LIMITS.rows},()=>Array(DESKTOP_LIMITS.columns).fill(''));eq(desktopFileError(maxfile),null,'500 by 52 accepted');maxfile.cells.push(Array(DESKTOP_LIMITS.columns).fill(''));ok(desktopFileError(maxfile)!==null,'501 rows rejected');
console.log(`PASS: ${checks} workbook calculation, reference-editing, template, XLSX export and state-regression assertions; ${FORMULA_FUNCTIONS.length} supported function names.`);
