/** Workspace UX domain tests. Worked figures below are isolated test fixtures, never shipped in the app. */
import assert from 'node:assert/strict';
import { initialState, applyCommand, validateBackup, journalsFor } from '../../lib/accounting/engine';
import { companyForState } from '../../lib/accounting/career';
import { dayTasks, dayTaskStatus } from '../../lib/accounting/workday';
import { WORKSPACE_APPS, WORKSPACE_SECTIONS, FINANCE_APPS, appsForSection, isWorkspaceView } from '../../lib/workspace/app-registry';
import { workspaceSearchIndex, searchWorkspace } from '../../lib/desktop/search-index';
import { readReviewBook, reviewFingerprint, reviewStage, saveReviewResponse, reviewFileId } from '../../lib/desktop/review-notes';
import { taskGuidanceHTML } from '../../lib/desktop/task-guidance';
import { workspaceMenuHTML } from '../../lib/desktop/workspace-menu';
import type { PracticeState } from '../../lib/accounting/types';
let checks = 0;
const eq = (a: unknown, b: unknown, label: string) => { assert.deepEqual(a, b, label); checks++; };
const ok = (value: unknown, label: string) => { assert.ok(value, label); checks++; };
const rejects = (fn: () => unknown, pattern: RegExp, label: string) => { assert.throws(fn, pattern, label); checks++; };
const now = '2026-09-18T06:45:00.000Z', later = '2026-09-18T06:45:01.000Z';
const start = () => applyCommand(initialState(271828), { type: 'startCareer', seed: 271828, startMonth: '2025-07', role: 'financial-manager', scenario: 'messy', daily: true, confirmation: 'START TAKEOVER' }, now);
const fresh = start(), co = companyForState(fresh), model = { company: co, state: fresh, journals: journalsFor(co, fresh), displayName: 'Test', saving: false, saveStatus: 'Saved', error: '', generation: 0 };
eq(WORKSPACE_SECTIONS.map(s => s.name), ['Today', 'Work', 'Close', 'Reports', 'Files', 'Learn', 'Settings'], 'Seven clear sections');
eq(WORKSPACE_APPS.length, 19, 'All existing routes are preserved');
eq(FINANCE_APPS.length, 18, 'All existing accounting applications remain available');
eq(new Set(WORKSPACE_APPS.map(a => a.id)).size, 19, 'No duplicate route IDs');
for (const app of WORKSPACE_APPS) {
    ok(isWorkspaceView(app.id), 'Valid route ' + app.id);
    ok(appsForSection(app.section).includes(app), 'Route assigned to section ' + app.id);
}
ok(!isWorkspaceView('unknown'), 'Unknown routes rejected');
for (const section of WORKSPACE_SECTIONS)
    ok(workspaceMenuHTML(section.id).includes(section.name), 'Menu renders ' + section.name);
const original = JSON.stringify(fresh), index = workspaceSearchIndex(model);
eq(JSON.stringify(fresh), original, 'Building the search index is read-only');
ok(index.some(i => i.kind === 'file' && i.ref === 'DOC:TB-OPEN'), 'Opening evidence searchable');
ok(!index.some(i => i.ref === 'DOC:PAY-2025-07' || i.ref === 'LIVE:payroll:2025-07'), 'Unreleased payroll absent');
const welcome = dayTasks(fresh).find(t => t.id.endsWith('welcome'))!;
ok(index.some(i => i.kind === 'task' && i.ref === welcome.id), 'Released assignment indexed');
ok(!JSON.stringify(index.filter(i => i.kind === 'task')).includes('"expected"'), 'Search does not serialize expected-answer fields');
eq(searchWorkspace(index, 'TB-OPEN')[0]?.ref, 'DOC:TB-OPEN', 'Exact source reference ranks first');
eq(searchWorkspace(index, 'tB-oPeN')[0]?.ref, 'DOC:TB-OPEN', 'Case insensitive search');
ok(searchWorkspace(index, '1000').some(i => i.kind === 'account'), 'Account codes searchable');
ok(searchWorkspace(index, 'journal ledger').some(i => i.ref === 'ledger'), 'Multiple query terms');
eq(searchWorkspace(index, 'no-such-record-zzzz').length, 0, 'No match is explicit');
ok(searchWorkspace(index, '', 2).length <= 2, 'Results bounded');
ok(searchWorkspace(index, '').every(i => i.kind === 'app'), 'Empty search offers applications');
const guide = taskGuidanceHTML({ ...welcome, brief: '<script>untrusted</script>' });
ok(guide.includes('Why is this on my desk?'), 'Business context exposed');
ok(!guide.includes('<script>'), 'Task guidance escapes text');
ok(guide.includes('&lt;script&gt;'), 'Task guidance preserves escaped content');
const note = 'Reconciled the supplied evidence, recorded the outstanding difference and assigned follow-up ownership.';
eq(readReviewBook(fresh).book.notes, {}, 'Old cases need no migration');
rejects(() => saveReviewResponse(fresh, 'future-task', 'open', note, now), /available assignment/, 'Unavailable task rejected');
rejects(() => saveReviewResponse(fresh, welcome.id, 'open', 'short', now), /20 to/, 'Specific response required');
rejects(() => saveReviewResponse(fresh, welcome.id, 'open', note, 'not-a-date'), /timestamp/, 'Bad timestamp rejected');
rejects(() => saveReviewResponse(fresh, welcome.id, 'cleared', note, now), /underlying saved work/, 'Cannot clear failed work');
const first = saveReviewResponse(fresh, welcome.id, 'prepared', note, now);
let state = applyCommand(fresh, first, now);
eq(state.journals, fresh.journals, 'Review response creates no journal');
eq(state.bankMatches, fresh.bankMatches, 'Review response changes no matches');
eq(state.workday, fresh.workday, 'Review response submits no assignment and advances no date');
eq(validateBackup(state), null, 'Review notes valid in existing backup format');
eq(readReviewBook(JSON.parse(JSON.stringify(state))).book.notes[welcome.id].history.length, 1, 'History survives backup roundtrip');
eq(reviewFingerprint(state), reviewFingerprint(fresh), 'Saving a review response does not stale itself');
rejects(() => applyCommand(state, first, later), /changed|exists|reload/i, 'Create collision cannot overwrite saved responses');
const next = saveReviewResponse(state, welcome.id, 'open', note + ' Investigation continues.', later);
state = applyCommand(state, next, later);
eq(readReviewBook(state).book.notes[welcome.id].history.length, 2, 'History is appended, not replaced');
rejects(() => applyCommand(state, next, '2026-09-18T06:45:02.000Z'), /changed|reload/i, 'Stale file revision rejected');
const submission = { taskId: welcome.id, status: 'submitted' as const, figures: Object.fromEntries(welcome.figures.map(f => [f.id, f.expected])), decision: welcome.correctDecision ?? '', note, evidence: welcome.evidence.slice(0, 2), blocker: '', owner: '', followUp: '', updatedAt: '' };
state = applyCommand(state, { type: 'saveDailySubmission', submission }, later);
ok(dayTaskStatus(welcome, state).complete, 'Fixture passes real underlying task check');
state = applyCommand(state, saveReviewResponse(state, welcome.id, 'cleared', note, later), later);
const saved = readReviewBook(state).book.notes[welcome.id];
eq(reviewStage(saved, dayTaskStatus(welcome, state), reviewFingerprint(state)), 'cleared', 'Passing reviewed task may be cleared');
state = applyCommand(state, { type: 'saveDailySubmission', submission: { ...submission, note: note + ' New supporting conclusion.' } }, '2026-09-18T06:45:03.000Z');
eq(reviewStage(saved, dayTaskStatus(welcome, state), reviewFingerprint(state)), 'changes-requested', 'Changed work invalidates prior clearance');
eq(readReviewBook(state).book.notes[welcome.id].history.length, 3, 'Invalidation does not delete old response history');
const recycled = structuredClone(state);
recycled.desktop!.files.find(f => f.id === reviewFileId('2025-07'))!.deleted = true;
rejects(() => readReviewBook(recycled), /recycle bin/, 'Recycled review history cannot be silently replaced');
const bad = structuredClone(state);
bad.desktop!.files.find(f => f.id === reviewFileId('2025-07'))!.text = 'not valid json';
rejects(() => readReviewBook(bad), /invalid/, 'Malformed review history blocks destructive overwrite');
const closed = structuredClone(state);
closed.career!.closed['2025-07'] = { month: '2025-07', at: now, reason: 'Test', assisted: false, journalCount: 0 };
rejects(() => saveReviewResponse(closed, welcome.id, 'prepared', note, later), /period is closed/, 'Closed periods protected');
const big = structuredClone(state), book = readReviewBook(big);
const history = book.book.notes[welcome.id].history;
for (let i = 0; i < 30; i++)
    history.push({ at: now, stage: 'prepared', response: 'x'.repeat(1900) });
book.file!.text = JSON.stringify(book.book);
rejects(() => saveReviewResponse(big, welcome.id, 'prepared', note, later), /file limit/, 'Oversized history fails rather than silently truncating');
console.log(`Workspace navigation/search/review: ${checks} assertions passed.`);
