import {filterQueue, nextAction, needsAttention, followUpDue, pageOf, TASK_KINDS} from './task-queue';
import {preserveView} from './view-state';
import {taskGuidanceHTML} from './task-guidance';
/** Guided daily workflow. All durable mutations go through the existing command boundary. */
import type {Command} from '../accounting/types';
import type {DailySubmission,DayTask} from '../accounting/workday-types';
import {dayTasks,daySummary,dayMail,dayTaskStatus} from '../accounting/workday';
import {formatDay,addBusinessDays,closePackDate,workdayLimit,bankAvailableOn} from '../accounting/workday-calendar';
import {addDays,parseMoney} from '../accounting/money';
import {htmlEscape as e,csv,downloadFile} from '../accounting/exports';
import type {DesktopModel} from './files';
export type DayDeskHandle={refresh:()=>void;openTask:(id:string)=>void;calendar:()=>void;hasUnsaved:()=>boolean;saveDraft:()=>Promise<boolean>;discard:()=>void};
type Callbacks={model:()=>DesktopModel;send:(c:Command)=>Promise<boolean>;mail:(id?:string)=>void;source:(id:string)=>void;file:(id:string)=>void;app:(view:string,focusTask?:string)=>void;workbook:(template:string)=>void;capture:(id:string)=>void;journal:(id:string)=>void;dirtyElsewhere:()=>boolean;paired:(task:DayTask)=>void};
const btn=(a:string,text:string,attrs='')=>`<button type="button" data-day-action="${a}" ${attrs}>${e(text)}</button>`;
const money=(v:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v/100);
export function mountDayDesk(root:HTMLElement,c:Callbacks):DayDeskHandle{
 const caseIdentity=()=>[c.model().state.seed,c.model().state.career?.startedAt,c.model().state.career?.activeMonth,c.model().generation].join(':');
 let draftCase=caseIdentity(),draftBase='';
 let rawFigures:Record<string,string>={};
 let query='',kind='all',page=0,renderKey='';
 let tab='today',selected='',filter='open',draft:DailySubmission|null=null,dirty=false,pending=false,checked=false,feedback='',error='',date='',dayNote='',ack=false;
 const m=()=>c.model(),today=()=>m().state.workday!.today;
 const task=()=>dayTasks(m().state).find(t=>t.id===selected);
 const makeDraft=(t:DayTask):DailySubmission=>structuredClone(m().state.workday!.submissions[t.id]??{taskId:t.id,status:'draft',figures:{},decision:'',note:'',evidence:[],blocker:'',owner:'',followUp:'',updatedAt:''});
 const changeTask=(id:string)=>{if(dirty){if(id!==selected)error='Save or discard this response before opening another assignment.';tab='task';paint();return;}selected=id;rawFigures={};draftCase=caseIdentity();draftBase=m().state.workday?.submissions[id]?.updatedAt??'';draft=task()?.kind==='response'?makeDraft(task()!):null;tab='task';error='';feedback='';checked=false;paint();};
 const row=(t:DayTask)=>{const status=dayTaskStatus(t,m().state),follow=followUpDue({task:t,status},m().state),late=t.due<today()&&!status.complete,source=t.sourceId?m().company.documents.find(d=>d.id===t.sourceId):undefined,title=source&&t.kind==='processing'?(t.title.startsWith('Capture')?'Capture: ':'Process: ')+source.title:t.title;return `<button class="day-task" type="button" data-day-task="${e(t.id)}"><span class="day-state" data-state="${e(status.state)}">${e(status.state)}</span><span><strong>${e(title)}</strong><small>${source?e(source.id)+' · '+e(t.effectiveDate??source.date)+' · ':''}${e(t.requestor)} · ${e(t.kind==='processing'?'Source processing':t.kind==='bank'?'Bank reconciliation':t.role)}</small></span><span class="day-due ${late?'late':''}">${follow?'FOLLOW-UP DUE':late?'OVERDUE':t.due===today()?'DUE TODAY':'Due '+e(t.due)}<small>${e(t.priority)}</small></span></button>`;};
 function paint(){
  const model=m(),w=model.state.workday;if(!w){root.innerHTML='<div class="day-desk"><h2>Day-by-day mode is not enabled.</h2></div>';return;}
  const restore=renderKey===tab+':'+selected?preserveView(root):()=>{};renderKey=tab+':'+selected;
  const summary=daySummary(model.state),s={...summary,next:nextAction(summary.tasks,model.state)},mail=dayMail(model.state),unread=mail.filter(x=>!model.state.desktop?.readMail.includes(x.id)&&x.category!=='Sent'&&x.category!=='Draft');
  const conflict=dirty&&!pending&&(draftCase!==caseIdentity()||draftBase!==(w.submissions[selected]?.updatedAt??''));
  if(conflict)error='The saved case or this response changed since you started editing. Download your draft, then discard it to load the current saved version. No old response will overwrite the newer one.';
  let body='';
  if(tab==='today'){
   body=`<section class="day-hero"><div><span class="day-kicker">${s.next?'YOUR NEXT ACTION':s.open.length?'WAITING ON INFORMATION':'YOUR AVAILABLE TASKS ARE COMPLETE'}</span><h2>${e(s.next?.task.title??(s.open.length?'Open tasks are waiting on information.':'Review your work, then move to the next day.'))}</h2><p>${e(s.next?.task.brief??(s.open.length?'Check the named owners and follow-up dates below. Waiting tasks remain open and their original deadlines still apply.':'Later work will arrive when you advance the PC date. No work is completed automatically.'))}</p>${s.next?`${s.next.task.id.endsWith('-welcome')?btn('welcome','Read onboarding email','class="day-primary"'):''}${btn('next','Open this task',s.next.task.id.endsWith('-welcome')?'':'class="day-primary"')}`:btn('calendar','End day / change date','class="day-primary"')}${btn('mail','Read inbox ('+unread.length+' unread)')}</div><aside><strong>${e(w.today.slice(-2))}</strong><span>${e(new Date(w.today+'T12:00:00Z').toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}))}</span><small>Accounting month ${e(model.state.career!.activeMonth)}</small></aside></section>
    <div class="day-stats"><button data-day-action="overdue"><b>${s.overdue.length}</b>Overdue</button><button data-day-action="due"><b>${s.due.length}</b>Due today</button><button data-day-action="arrived"><b>${s.arrived.length}</b>Arrived today</button><button data-day-action="completed"><b>${s.completed.length}</b>Complete so far</button></div>

    <section><div class="day-section-head"><h3>Next on your desk</h3>${btn('tasks','See all available tasks ('+s.tasks.length+')')}</div>${filterQueue(s.tasks,model.state,'open').filter(x=>x.task.id!==s.next?.task.id).slice(0,4).map(x=>row(x.task)).join('')||'<p>No other open tasks from the evidence delivered so far.</p>'}</section>
    <section class="day-triage" aria-label="Available work by area">${Object.entries(TASK_KINDS).map(([id,label])=>{const all=s.tasks.filter(x=>x.task.kind===id),left=all.filter(x=>!x.status.complete).length;return all.length?btn('kind',label+' · '+left+' open / '+all.length+' arrived',`data-kind="${id}"`):'';}).join('')}${btn('attention','Needs attention ('+s.tasks.filter(x=>needsAttention(x,model.state)).length+')')}${btn('ledger-checks','Ledger checks')}</section>    <details class="day-routine"><summary>Your daily routine</summary><p><b>1.</b> Read new mail. <b>2.</b> Deal with urgent cash/control issues. <b>3.</b> Process and reconcile. <b>4.</b> Submit requested outputs. <b>5.</b> Check saved work and end the day.</p></details>
    ${s.open.some(x=>x.status.state==='Waiting')?`<section class="day-waiting"><div class="day-section-head"><h3>Waiting on others</h3>${btn('waiting','See waiting items')}</div>${s.open.filter(x=>x.status.state==='Waiting').slice(0,5).map(({task})=>{const response=w.submissions[task.id];return `<button class="day-waiting-item" type="button" data-day-task="${e(task.id)}"><strong>${e(task.title)}</strong><small>${e(response?.owner??'Owner not recorded')} · Follow up ${e(response?.followUp??'not recorded')}</small><span>${e(response?.blocker??'')}</span></button>`;}).join('')}</section>`:''}<details class="day-help"><summary>Tools, backups and getting started</summary><p>Every task links to evidence and the required workspace. Post invoices/journals in Accounting, calculate in a workbook, and submit the requested result. Reading an email does not complete a task.</p>${btn('welcome','Onboarding mail')}${btn('ledger','Post a journal')}${btn('bank','Bank reconciliation')}${btn('files','My working papers')}${btn('settings','Backup / case settings')}</details>`;
  }else if(tab==='tasks'){
   const list=filterQueue(s.tasks,model.state,filter,query,kind,Object.fromEntries(model.company.documents.map(d=>[d.id,d.title]))),slice=pageOf(list,page);page=slice.page;
   body=`<div class="day-section-head"><h2>My available work</h2>${btn('reset-filters','Reset filters')}</div>
    <div class="day-filters"><label>Search tasks<input type="search" name="day-query" value="${e(query)}" placeholder="Reference, task or person" maxlength="160"></label>
    <label>Status<select name="day-filter">${[['open','Open'],['attention','Needs attention'],['waiting','Waiting'],['due','Due today'],['overdue','Overdue'],['arrived','Arrived today'],['completed','Complete'],['all','All arrived']].map(([id,label])=>`<option value="${id}" ${filter===id?'selected':''}>${label}</option>`).join('')}</select></label>
    <label>Work area<select name="day-kind"><option value="all">All areas</option>${Object.entries(TASK_KINDS).map(([id,label])=>`<option value="${id}" ${kind===id?'selected':''}>${e(label)}</option>`).join('')}</select></label></div>
    <p class="day-queue-count" role="status">${slice.total} matching tasks. Only arrived work is included.</p>
    ${slice.rows.map(x=>row(x.task)).join('')||'<section class="day-empty"><h3>No tasks match</h3><p>Clear the search or reset the filters. Unreleased work is intentionally not listed.</p></section>'}
    <nav class="day-pages" aria-label="Task pages">${btn('previous-page','Previous',page===0?'disabled':'')}<span>${slice.from}–${slice.to} of ${slice.total} · Page ${page+1} / ${slice.pages}</span>${btn('next-page','Next',page+1>=slice.pages?'disabled':'')}</nav>`;
  }else if(tab==='task'){
   const t=task();if(!t){body='<h2>Assignment unavailable in this accounting period.</h2><p>Open the current task list. Earlier correspondence remains in your inbox.</p>';}else{
    const status=dayTaskStatus(t,model.state),saved=w.submissions[t.id],showCheck=checked||saved?.status==='submitted';
    body=`${btn('tasks','‹ Back to tasks')}<div class="day-assignment-head"><span class="day-state" data-state="${e(status.state)}">${e(status.state)}</span><span>${e(t.priority)} priority · Received ${e(t.release)} · Due ${e(t.due)} end of day</span></div><h2>${e(t.title)}</h2>${t.kind==='response'?btn('jump-response','Go to your response'):''}<p class="day-from">${e(t.requestor)} · ${e(t.role)}</p><p>${e(t.brief)}</p>${taskGuidanceHTML(t)}<section class="day-instructions"><h3>What to do</h3>${t.id.endsWith('-welcome')?btn('welcome','Read the CFO’s onboarding email','class="day-primary"'):''}<ol>${t.steps.map(v=>`<li>${e(v)}</li>`).join('')}</ol><h3>Evidence on your desk</h3><div class="day-evidence">${t.evidence.map(id=>btn('source',id+' · '+(model.company.documents.find(d=>d.id===id)?.title??'Supporting source'),`data-id="${e(id)}"`)).join('')}</div><div class="day-actions">${btn('paired','Open evidence + work')}${btn('workspace','Open '+(t.kind==='formal'?'formal deliverable':t.kind==='forecast'?'forecast':'workspace'),'class="day-primary"')}${t.template?btn('template','Create supporting workbook'):''}${t.id.includes('-cash-')?btn('cash-extract','Download bank extract at request date'):''}${t.sourceId?btn('journal','Prepare linked journal'):''}</div><small>Original evidence is read-only. Workbook snapshots do not post or submit your result.</small></section>`;
    if(t.kind==='response'){
     if(!draft)draft=makeDraft(t);
     body+=`<section class="day-response"><h3>Your response to ${e(t.requestor)}</h3><p>Amounts in AUD, not cents. The task remains open until you submit a complete response and its defined checks pass.</p>${t.figures.map(f=>`<label>${e(f.label)}<input name="day-figure:${e(f.id)}" inputmode="decimal" placeholder="0.00" value="${e(rawFigures[f.id]??(draft!.figures[f.id]===undefined?'':(draft!.figures[f.id]/100).toFixed(2)))}"></label>`).join('')}${t.choices?`<label>Control decision<select name="day-decision"><option value="">Choose a decision</option>${t.choices.map(ch=>`<option value="${e(ch.id)}" ${draft!.decision===ch.id?'selected':''}>${e(ch.label)}</option>`).join('')}</select></label>`:''}<label>Response / analysis / recommended action<textarea name="day-note" rows="6" maxlength="6000" placeholder="Explain your analysis, actions, assumptions, owner and next step. Minimum 80 characters to submit.">${e(draft.note)}</textarea></label><label>Evidence references, separated by commas<input name="day-evidence" value="${e(draft.evidence.join(', '))}" placeholder="Source IDs above; optional saved workbook IDs"></label><div class="day-evidence">${t.evidence.map(id=>btn('cite','Add '+id,`data-id="${e(id)}"`)).join('')}</div><label>Attach a saved working paper<select name="day-workbook"><option value="">Choose an existing saved file</option>${(model.state.desktop?.files??[]).filter(f=>!f.deleted).map(f=>`<option value="${e(f.id)}">${e(f.name)}</option>`).join('')}</select></label><details class="day-blocker" ${draft.status==='blocked'?'open':''}><summary>Waiting on information? Record a blocker</summary><label>Missing information / blocker<textarea name="day-blocker" rows="2">${e(draft.blocker)}</textarea></label><label>Person responsible<input name="day-owner" value="${e(draft.owner)}"></label><label>Follow up on<input name="day-followup" type="date" min="${today()}" value="${e(draft.followUp)}"></label>${btn('blocked','Send blocker / follow-up request')}<p>A blocker preserves the outstanding task and deadline. An acknowledgement is not approval or new evidence.</p></details><div class="day-actions day-submit-actions">${btn('save','Save response draft')}${btn('submit','Submit response','class="day-primary"')}${btn('discard','Discard unsaved response')}</div><small>${dirty?'Unsaved response':saved?`Saved ${e(saved.status)} on scenario date ${e(saved.submittedOn??'')}`:'Not yet saved'} · Responses are fictional case messages, not real emails.</small></section>`;
    }
    body+=`<section class="day-review"><h3>Saved-work check</h3><p>${e(status.detail)}</p>${btn('check-task','Check this task')}${showCheck&&status.differences.length?`<table><thead><tr><th>Check</th><th>Your saved result</th><th>Case result</th><th>Difference</th></tr></thead><tbody>${status.differences.map(d=>`<tr><td>${e(d.label)}</td><td>${money(d.actual)}</td><td>${money(d.expected)}</td><td>${money(d.actual-d.expected)}</td></tr>`).join('')}</tbody></table>`:''}${showCheck&&t.choices&&saved?.status==='submitted'&&status.state==='Needs correction'?'<p>Keep unverified changes/payments on hold and use independent trusted contact details. For payroll, use the authorised final register, not rejected overtime.</p>':''}<p>Numerical/control checks are automated. Written judgement, quality of a freeform workbook, commercial assumptions and independent approval require human review.</p></section>`;
   }
  }else if(tab==='calendar'){
   if(!date||date<=today())date=addBusinessDays(today(),1);
   const crossed=dayTasks(model.state,true).filter(t=>t.due>=today()&&t.due<date&&!dayTaskStatus(t,model.state).complete),weekend=[0,6].includes(new Date(today()+'T12:00:00Z').getUTCDay());
   body=`<h2>End your day / change the PC date</h2><p>The fictional PC clock moves forward only. It does not change your actual computer date. Save your work first. Nothing is posted, matched or marked complete by advancing.</p>${weekend?'<p class="day-info">It is a weekend in the internal Monday–Friday calendar. You may inspect records or move to the next working day.</p>':''}<div class="day-datebox"><label>Next PC date<input type="date" name="day-date" value="${e(date)}" min="${addDays(today(),1)}" max="${workdayLimit(model.state.career!.activeMonth)}"></label><div>${btn('next-calendar','Next calendar day')}${btn('next-working','Next working day')}</div><label>End-of-day note / handover to yourself<textarea name="day-endnote" maxlength="2000" rows="3" placeholder="What remains open, who owes you information, and what you will do next.">${e(dayNote)}</textarea></label><p><b>${s.overdue.length+s.due.length}</b> open tasks are due now or overdue. <b>${crossed.length}</b> open deadlines would be crossed by this date change.</p><label class="day-check"><input name="day-ack" type="checkbox" ${ack?'checked':''}>I acknowledge outstanding/skipped deadlines. They remain open and late work is recorded.</label>${btn('advance','Save day log and advance','class="day-primary"')}${crossed.length?`<details><summary>Deadlines crossed</summary>${crossed.map(t=>`<p>${e(t.due)} · ${e(t.title)}</p>`).join('')}</details>`:''}</div><section class="day-help"><h3>Month close without time travel</h3><p>The ${e(model.state.career!.activeMonth)} closing evidence arrives on <b>${closePackDate(model.state.career!.activeMonth)}</b>. You can work through ${workdayLimit(model.state.career!.activeMonth)} in its close window. Close the accounting month, then release the next month. The PC date will not rewind; already-arrived next-month activity is waiting as a backlog.</p><p>This version has one open accounting period, not simultaneous live AP/AR posting into two months. Deadlines use weekdays, with no public-holiday or statutory filing calendar.</p>${btn('month-close','Open month review / close')}</section>`;
  }else if(tab==='check'){
   body=`<h2>Check today’s saved work</h2><p>Checked only against evidence that has arrived by <b>${e(today())}</b>. Future transactions are not counted as missing. Unsaved forms/workbooks are excluded.</p><div class="day-stats"><span><b>${s.completed.length}/${s.tasks.length}</b>Available tasks complete</span><span><b>${s.tasks.filter(x=>x.status.state==='Needs correction').length}</b>Need correction</span><span><b>${s.tasks.filter(x=>x.status.state==='Waiting').length}</b>Waiting</span></div><p>A missing entry, an incorrect entry, an unmatched bank line and an unanswered management request are distinct items. Open a task to inspect the saved-work check and correction details.</p>${s.open.map(x=>row(x.task)).join('')||'<h3>All available numerical/completion checks pass.</h3>'}<section class="day-help"><p>Freeform workbook cells, narrative quality, forecast realism and statutory completeness are not independently marked. Do not interpret task completion as professional sign-off.</p>${btn('export-check','Export today’s check')}${btn('calendar','End day')}${btn('month-close','Full month review')}</section>`;
  }else if(tab==='log'){
   body=`<h2>Your day log</h2><p>Dates do not run in real time. Only your explicit date changes are recorded. Original late-deadline records remain after you fix the work.</p>${btn('export-log','Export day log')}<div>${[...w.history].reverse().map(h=>`<article class="day-log"><h3>${e(h.from)} → ${e(h.to)}</h3><p>${e(h.note||'No end-of-day note recorded.')}</p><small>${h.outstanding.length} due/overdue · ${h.missed.length} crossed deadlines</small><details><summary>Recorded outstanding task IDs</summary><p>${[...new Set([...h.outstanding,...h.missed])].map(e).join('<br>')||'None'}</p></details></article>`).join('')||'<p>Your first day is in progress. The log starts when you advance the PC date.</p>'}</div>`;
  }
  root.innerHTML=`<div class="day-desk"><header class="day-header"><div><span class="day-kicker">HARBOUR & CO. · TODAY</span><h1>${e(formatDay(w.today))}</h1><p>${e(model.state.career!.role==='financial-manager'?'Financial manager':'Financial accountant')} · Open accounting month ${e(model.state.career!.activeMonth)} · ${model.state.career!.closed[model.state.career!.activeMonth]?'Period closed':'Period open'}</p></div>${btn('calendar','Change date','class="day-clock"')}</header><nav class="day-nav" aria-label="Daily desk">${[['today','Today'],['tasks','My tasks'],['mail','Inbox'],['check','Check today’s work'],['calendar','End day'],['log','Day log']].map(([a,l])=>btn(a,l,`aria-current="${tab===a?'page':'false'}"`)).join('')}</nav>${error?`<div class="day-error" role="alert">${e(error)}${conflict?`<div>${btn('download-response','Download preserved draft')}${btn('discard','Discard old draft / load current')}</div>`:''}</div>`:''}${feedback?`<p class="day-info" role="status">${e(feedback)}</p>`:''}${dayNote.trim()?`<div class="day-note-draft">End-of-day note not yet recorded. ${btn('download-daynote','Download note draft')}</div>`:''}<main>${body}</main></div>`;
  if(pending)root.querySelectorAll<HTMLInputElement>('button,input,select,textarea').forEach(b=>b.disabled=true);
  restore();
 }
 async function save(status:DailySubmission['status']='draft'):Promise<boolean>{
  if(!draft||pending)return !dirty;
  if(draftCase!==caseIdentity()||draftBase!==(m().state.workday?.submissions[selected]?.updatedAt??'')){error='The underlying case/response changed. Download and discard the old draft before saving again.';paint();return false;}
  if(!readFigures()){error='Enter valid amounts with at most two decimal places. Use a dot for decimals; commas must group thousands. Blanks are allowed only in drafts.';paint();return false;}
  pending=true;error='';const payload={...draft,status};paint();
  const ok=await c.send({type:'saveDailySubmission',submission:payload});pending=false;
  if(ok){dirty=false;rawFigures={};draftBase=m().state.workday!.submissions[selected]?.updatedAt??'';draft=makeDraft(task()!);feedback=status==='draft'?'Response draft saved.':status==='blocked'?'Blocker recorded. The deadline remains open.':'Response submitted. Review the saved-work check below; any defined errors keep the task open.';checked=status==='submitted';}
  else error=m().error||'Save failed. Your response remains open and unsaved.';
  paint();return ok;
 }
 function readFigures(){
  if(!draft)return true;let good=true;
  root.querySelectorAll<HTMLInputElement>('[name^="day-figure:"]').forEach(el=>{
   const id=el.name.slice(11),v=el.value.trim();rawFigures[id]=el.value;
   if(!v){delete draft!.figures[id];el.removeAttribute('aria-invalid');return;}
   try{draft!.figures[id]=parseMoney(v);el.removeAttribute('aria-invalid');}
   catch{good=false;el.setAttribute('aria-invalid','true');}
  });return good;
 }
 function captureInput(el:HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement){
  if(el.name==='day-endnote'){dayNote=el.value;return;}if(el.name==='day-date'){date=el.value;return;}if(el.name==='day-ack'){ack=(el as HTMLInputElement).checked;return;}
  if(!draft||!el.name.startsWith('day-'))return;
  const names:Record<string,keyof DailySubmission>={'day-note':'note','day-decision':'decision','day-blocker':'blocker','day-owner':'owner','day-followup':'followUp'};
  if(el.name==='day-evidence')draft.evidence=el.value.split(',').map(v=>v.trim()).filter(Boolean);
  else if(names[el.name])(draft as unknown as Record<string,unknown>)[names[el.name]]=el.value;
  else if(el.name.startsWith('day-figure:'))readFigures();
  else return;
  dirty=true;
 }
 root.addEventListener('input',event=>{const el=event.target as HTMLInputElement;if(el.name==='day-query'){query=el.value;page=0;paint();}else captureInput(el);});
 root.addEventListener('change',event=>{const el=event.target as HTMLInputElement;if(el.name==='day-filter'){filter=el.value;page=0;paint();}else if(el.name==='day-kind'){kind=el.value;page=0;paint();}else if(el.name==='day-date'||el.name==='day-ack'){captureInput(el);paint();}else if(el.name==='day-workbook'&&draft&&el.value){draft.evidence=[...new Set([...draft.evidence,el.value])];dirty=true;paint();}else captureInput(el);});
 root.addEventListener('click',async event=>{
  const el=(event.target as Element).closest<HTMLElement>('[data-day-action],[data-day-task]');if(!el||pending)return;
  if(el.dataset.dayTask){changeTask(el.dataset.dayTask);return;}
  const a=el.dataset.dayAction,t=task();
  if(['today','tasks','calendar','log','check'].includes(a!)){if(dirty){error='Save or discard your response before leaving it.';paint();return;}if(a==='check'&&c.dirtyElsewhere()){error='Save or discard your open workbook/accounting forms before checking saved work.';paint();return;}tab=a!;error='';paint();return;}
  if(['overdue','due','arrived','completed','waiting','attention'].includes(a!)){if(dirty)return;filter=a!;kind='all';query='';page=0;tab='tasks';paint();return;}
  if(a==='kind'){if(dirty)return;kind=el.dataset.kind!;filter='open';query='';page=0;tab='tasks';paint();return;}
  if(a==='reset-filters'){filter='open';query='';kind='all';page=0;paint();return;}
  if(a==='previous-page'||a==='next-page'){page+=a==='next-page'?1:-1;paint();return;}
  if(a==='jump-response'){const response=root.querySelector<HTMLElement>('.day-response');response?.scrollIntoView({block:'start'});response?.querySelector<HTMLInputElement>('input,textarea,select')?.focus({preventScroll:true});return;}
  if(a==='download-daynote'){downloadFile('End-of-day-draft.txt',dayNote);return;}
  if(a==='next'){const next=nextAction(daySummary(m().state).tasks,m().state);if(next)changeTask(next.task.id);return;}
  if(a==='mail'||a==='welcome'){c.mail(a==='welcome'?'MAIL-WELCOME':undefined);return;}
  if(a==='source'){c.source(el.dataset.id!);return;}
  if(a==='paired'&&t){c.paired(t);return;}
  if(a==='workspace'&&t){if(t.kind==='processing'&&t.sourceId&&/invoice|credit note/i.test(m().company.documents.find(d=>d.id===t.sourceId)?.kind??'')&&!m().state.journals.some(j=>j.sourceId===t.sourceId)){c.capture(t.sourceId);}else if(t.kind==='processing'&&t.sourceId)c.journal(t.sourceId);else c.app(t.view,t.kind==='formal'?t.formalId:t.kind==='forecast'?'@forecast':undefined);return;}
  if(a==='journal'&&t?.sourceId){c.journal(t.sourceId);return;}
  if(a==='template'&&t?.template){c.workbook(t.template);return;}
  if(a==='files'){c.file('WORKING-FOLDER');return;}
  if(['ledger','bank','settings','ledger-checks'].includes(a!)){c.app(a!);return;}
  if(a==='month-close'){if(today()<closePackDate(m().state.career!.activeMonth)){error='Full month review opens on '+closePackDate(m().state.career!.activeMonth)+'. Use Check today’s work until the closing evidence arrives.';paint();}else c.app('close');return;}
  if(a==='save'||a==='submit'||a==='blocked'){await save(a==='save'?'draft':a==='submit'?'submitted':'blocked');return;}
  if(a==='download-response'){downloadFile('Preserved-daily-response.json',JSON.stringify({response:draft,unsavedAmountText:rawFigures},null,2),'application/json');return;}
  if(a==='discard'){dirty=false;rawFigures={};draftCase=caseIdentity();draftBase=m().state.workday?.submissions[selected]?.updatedAt??'';if(!t){tab='today';selected='';}draft=t?.kind==='response'?makeDraft(t):null;error='';feedback='Unsaved response discarded; saved work is unchanged.';paint();return;}
  if(a==='cite'&&draft){draft.evidence=[...new Set([...draft.evidence,el.dataset.id!])];dirty=true;paint();return;}
  if(a==='check-task'){if(dirty||c.dirtyElsewhere()){error='Save your response and working files before checking.';}else{checked=true;error='';}paint();return;}
  if(a==='next-calendar'||a==='next-working'){date=a==='next-calendar'?addDays(today(),1):addBusinessDays(today(),1);paint();return;}
  if(a==='advance'){
   if(dirty||c.dirtyElsewhere()){error='Save or discard all open response, workbook and accounting-form drafts before advancing. No unsaved work was discarded.';paint();return;}
   pending=true;paint();const ok=await c.send({type:'advanceWorkday',date,note:dayNote,acknowledgeOutstanding:ack});pending=false;
   if(ok){tab='today';dayNote='';ack=false;date='';feedback='PC date advanced. Newly arrived evidence and messages are on your desk.';error='';}else error=m().error||'Date change failed. Check the date and outstanding-deadline acknowledgement.';paint();return;
  }
  if(a==='cash-extract'&&t){const rows=m().company.bank.filter(r=>bankAvailableOn(r.date)<=t.release);downloadFile(`Bank-extract-available-${t.release}.csv`,csv(['Date','Reference','Description','Amount AUD','Balance AUD','Delivered'],rows.map(r=>[r.date,r.reference,r.description,(r.amount/100).toFixed(2),(r.balance/100).toFixed(2),bankAvailableOn(r.date)])),'text/csv');return;}
  if(a==='export-check'){const s=daySummary(m().state);downloadFile(`Daily-check-${today()}.csv`,csv(['PC date','Task','Status','Due','Detail'],s.tasks.map(x=>[today(),x.task.title,x.status.state,x.task.due,x.status.detail])),'text/csv');return;}
  if(a==='export-log'){downloadFile('Finance-day-log.csv',csv(['From','To','Note','Due/overdue IDs','Crossed deadline IDs'],m().state.workday!.history.map(h=>[h.from,h.to,h.note,h.outstanding.join('; '),h.missed.join('; ')])),'text/csv');}
 });
 const refresh=()=>{if(!dirty&&!pending&&selected&&task()?.kind==='response'){rawFigures={};draftBase=m().state.workday!.submissions[selected]?.updatedAt??'';draftCase=caseIdentity();draft=makeDraft(task()!);}paint();};
 paint();return {refresh,openTask:changeTask,calendar:()=>{if(dirty){error='Save or discard your response before changing date.';paint();return;}tab='calendar';paint();},hasUnsaved:()=>dirty||!!dayNote.trim()||pending,saveDraft:async()=>{if(dayNote.trim()){tab='calendar';error='Record the date change or download your end-of-day note before closing. Discard is available in the close dialog.';paint();return false;}return save();},discard:()=>{dirty=false;rawFigures={};draft=task()?.kind==='response'?makeDraft(task()!):null;paint();}};
}
