/** Case-backed working-paper packs. All ledger figures are learner snapshots, not solutions. */
import type {DesktopModel} from './files';
import type {DesktopUserFile,DesktopWorksheet} from './types';
import {columnName,address,syncWorkbook} from './workbook-model';
import {trialBalance,accountBalances,bankAmount} from '../accounting/engine';
import {monthEnd} from '../accounting/money';
export const WORKPAPER_TEMPLATES:Record<string,string>={bank:'Bank reconciliation',payroll:'Payroll control',accrual:'Accrual rollforward',prepayments:'Prepayment schedule',receivables:'Receivables and collections',payables:'Supplier reconciliation and payment plan',assets:'Fixed-asset rollforward',inventory:'Inventory reconciliation',management:'Management accounts',afs:'AFS preparation',cashflow:'13-week cash forecast',close:'Month-end close file',blank:'Blank working paper'};
type Value=string|number;
function sheet(name:string,rows:Value[][],moneyCols:number[]=[],headers=4):DesktopWorksheet{
 const cols=Math.max(8,...rows.map(r=>r.length)),cells=Array.from({length:Math.max(60,rows.length+8)},(_,r)=>Array.from({length:cols},(_,c)=>String(rows[r]?.[c]??''))),styles:NonNullable<DesktopWorksheet['styles']>={};
 rows.forEach((row,r)=>row.forEach((v,c)=>{if(r===0)styles[address(r,c)]={bold:true,color:'#ffffff',fill:'#185c43'};else if(r===headers-1)styles[address(r,c)]={bold:true,color:'#ffffff',fill:'#326e5a'};else if(r>headers-1){styles[address(r,c)]={...(moneyCols.includes(c)?{format:'accounting' as const}:{}),...(String(v).startsWith('=')?{color:'#172d27'}:{color:'#2459a6'})};}}));
 return {id:'sheet-'+name.toLowerCase().replace(/[^a-z0-9]/g,'-'),name,cells,styles,widths:{'0':265,'1':140,'2':140,'3':140,'4':140,'5':145,'6':170,'7':200},freezeRows:headers,freezeCols:1};
}
export function enrichWorkingFile(file:DesktopUserFile,model:DesktopModel,template:string):DesktopUserFile{
 const month=model.state.career?.activeMonth??'2025-12',end=monthEnd(month),tb=trialBalance(model.journals,end),period=trialBalance(model.journals.filter(j=>j.date.startsWith(month)),end),opening=accountBalances(model.journals,undefined,month==='2025-01'?'2024-12-31':new Date(Date.UTC(2025,Number(month.slice(5,7))-1,0)).toISOString().slice(0,10));
 const amount=(code:string)=>{const r=tb.find(r=>r.code===code);return r?(r.debit-r.credit)/100:0;};
 const main=sheet(template==='blank'?'Workpaper':WORKPAPER_TEMPLATES[template]?.slice(0,31)??'Workpaper',file.cells,template==='blank'?[]:[1]);
 if(template==='blank'){main.freezeRows=0;main.freezeCols=0;}
 const ledger=sheet('Learner TB',[['Learner trial balance',end],['Snapshot at workbook creation. Re-create or update after posting.'],[],['Account','Description','Debit AUD','Credit AUD','Signed balance AUD'],...tb.filter(r=>r.debit||r.credit).map(r=>[r.code,r.name,r.debit/100,r.credit/100,(r.debit-r.credit)/100])],[2,3,4]);
 const instructions=sheet('Read me',[[WORKPAPER_TEMPLATES[template]??'Working paper',month],['Practice file, not a posting or a signed statutory report.'],[],['Stage','Your responsibility'],['1. Evidence','Read the independent source documents in the monthly folders.'],['2. Prepare','Blue entries are inputs/snapshots. Black formulas calculate your workings.'],['3. Investigate','Explain differences. Do not force a reconciliation with an unsupported plug.'],['4. Process','Post corrections in Journal & ledger, not by changing source evidence.'],['5. Update','Ledger and source tabs are snapshots, not live links. Update/re-create after posting.'],['6. Conclude','Identify evidence, preparer, reviewer, outstanding items and next action.'],['7. Submit','Use Finance desk for the formal career deliverable. Saving this file is not sign-off.'],['Currency','AUD. Dated fictional 2025 case; not current statutory advice.'],['Missing prior-year AFS','Obtain comparative evidence rather than inventing it.']]);
 let sheets=[main];
 if(template==='bank'){
  sheets.push(sheet('Statement',[['Independent bank statement',month],['Case-source data at creation; do not alter the evidence.'],[],['Date','Reference','Description','Amount AUD','Balance AUD','Bank ID'],...model.company.bank.filter(r=>r.date.startsWith(month)).map(r=>[r.date,r.reference,r.description,r.amount/100,r.balance/100,r.id])],[3,4]));
  sheets.push(sheet('Cashbook',[['Learner cashbook',month],['Your posted transactions, not the worked answer.'],[],['Date','Reference','Description','Amount AUD','Journal ID','Source ID'],...model.journals.filter(j=>j.date.startsWith(month)&&bankAmount(j)).map(j=>[j.date,j.reference,j.description,bankAmount(j)/100,j.id,j.sourceId??''])],[3]));
 }else if(template==='payroll'){
  const pay=model.company.payroll[month]??[],controlRows:Value[][]=[['Payroll controls',month],['Compare the register, liability balances, payments and evidence.'],[],['Control','Learner GL credit AUD','Register AUD','Reconciling items (+/-)','Difference','Explanation'],...([['Net wages','2110','net'],['Withholding','2120','withholding'],['Super','2130','super'],['Deductions','2140','deductions']] as const).map(([label,code,key],i)=>[label,-amount(code),pay.reduce((s,p)=>s+p[key],0)/100,0,`=B${i+5}-C${i+5}-D${i+5}`,'Explain opening balances, payments and current accruals.'])];sheets.push(sheet('GL controls',controlRows,[1,2,3,4]));
 }else if(template==='prepayments'){
  const rows:Value[][]=[['Prepayment rollforward',month],['Enter remaining cover, current expense and new prepayments from evidence.'],[],['Policy / contract','Opening prepaid','New payments prepaid','Months remaining','Expense release','Closing prepaid','Source','Comment']];
  for(let i=5;i<=24;i++)rows.push(['',0,0,0,0,`=B${i}+C${i}-E${i}`,'','']);rows.push(['Total','=SUM(B5:B24)','=SUM(C5:C24)','','=SUM(E5:E24)','=SUM(F5:F24)'],['Learner GL control',amount('1300')+amount('1310')],['Unexplained difference','=F25-B26'],['Prepared by',model.displayName],['Conclusion','']);sheets=[sheet('Prepayments',rows,[1,2,4,5])];
 }else if(template==='accrual'){
  main.widths!['0']=250;main.cells[19][1]=String(-amount('2100'));
 }else if(template==='receivables'||template==='payables'){
  const supplier=template==='payables',kind=supplier?'supplier':'customer',control=supplier?'2000':'1100';
  const rows:Value[][]=[[supplier?'Supplier payment planning':'Receivables collection plan',month],['Statement amounts and allocations require your investigation; GL includes all posted movements.'],[],['Contact','Learner GL balance','Statement balance','Reconciling items','Difference','Proposed amount','Evidence','Action / due date']];
  for(const contact of model.company.contacts.filter(c=>c.kind===kind)){const r=rows.length+1,balance=model.journals.filter(j=>j.date<=end).flatMap(j=>j.lines).filter(l=>l.account===control&&l.contact===contact.id).reduce((s,l)=>s+l.debit-l.credit,0)/100*(supplier?-1:1);rows.push([contact.name,balance,'',0,`=IF(C${r}="","",B${r}-C${r}-D${r})`,0,contact.id,'']);}
  const last=rows.length;rows.push(['Total',`=SUM(B5:B${last})`,`=SUM(C5:C${last})`,`=SUM(D5:D${last})`,`=SUM(E5:E${last})`,`=SUM(F5:F${last})`]);rows.push(['Prepared by',model.displayName],['Conclusion / priorities','']);sheets=[sheet(supplier?'Payables plan':'Collections',rows,[1,2,3,4,5])];
 }else if(template==='assets'){
  const rows:Value[][]=[['Fixed asset rollforward',month],['Populate asset-level additions, disposals and depreciation from dated evidence.'],[],['Asset / category','Opening cost','Additions','Disposals (-)','Closing cost','Opening accum dep','Charge','Closing accum dep']];
  for(let i=5;i<=24;i++)rows.push(['',0,0,0,`=SUM(B${i}:D${i})`,0,0,`=F${i}+G${i}`]);rows.push(['Total',...Array.from({length:7},(_,c)=>`=SUM(${columnName(c+1)}5:${columnName(c+1)}24)`)],['GL cost',amount('1500')],['Cost difference','=E25-B26'],['GL accumulated depreciation',-amount('1510')],['Accumulated depreciation difference','=H25-B28'],['Disposal dep releases','Enter signed releases in the Charge column or extend the schedule; explain separately.']);sheets=[sheet('Assets',rows,[1,2,3,4,5,6,7])];
 }else if(template==='inventory'){
  const rows:Value[][]=[['Inventory and NRV reconciliation',month],['Enter counted quantities, verified unit costs and selling costs.'],[],['Item','Book quantity','Count quantity','Unit cost AUD','Count variance AUD','Count value AUD','NRV per unit','NRV shortfall AUD']];
  for(let i=5;i<=24;i++)rows.push(['',0,0,0,`=(C${i}-B${i})*D${i}`,`=C${i}*D${i}`,'',`=IF(G${i}="","",MAX(0,D${i}-G${i})*C${i})`]);rows.push(['Total','','','', '=SUM(E5:E24)','=SUM(F5:F24)','','=SUM(H5:H24)'],['GL gross inventory',amount('1200')],['Gross difference','=F25-B26'],['GL allowance',-amount('1210')],['Allowance difference','=H25-B28']);sheets=[sheet('Stock and NRV',rows,[3,4,5,6,7])];
 }else if(template==='management'){
  const rows:Value[][]=[['Management accounts',month],['Current month actuals from your ledger. Enter approved budget and explain material variances.'],[],['Account','Description','Actual debit / (credit)','Budget debit / (credit)','Variance','Variance %','Driver / action','Evidence']];
  for(const a of period.filter(r=>['income','expense','revenue'].includes(r.type))){const r=rows.length+1;rows.push([a.code,a.name,(a.debit-a.credit)/100,'',`=IF(D${r}="","",C${r}-D${r})`,`=IFERROR(E${r}/ABS(D${r}),0)`,'','']);}sheets=[sheet('Actual vs budget',rows,[2,3,4])];
 }else if(template==='afs'){
  const rows:Value[][]=[['AFS lead schedule',month],['Learner year-to-date figures only. Signed prior-year comparatives are outstanding.'],[],['Account','Description','Current signed AUD','Prior year AUD','Movement','AFS line / note','Evidence','Status']];
  for(const a of tb.filter(r=>r.debit||r.credit)){const r=rows.length+1;rows.push([a.code,a.name,(a.debit-a.credit)/100,'',`=IF(D${r}="","",C${r}-D${r})`,'','','Not assessed']);}sheets=[sheet('AFS mapping',rows,[2,3,4]),sheet('Disclosure checklist',[['AFS disclosure assessment',month],['Document applicability, evidence and unresolved gaps.'],[],['Area','Applicable?','Evidence','Conclusion','Outstanding request','Owner'],...['Entity and basis of preparation','Going concern','Accounting policies','Revenue','Financial instruments / credit risk','PPE','Leases','Inventory','Employee benefits','Provisions and contingencies','Tax and deferred tax','Related parties','Events after reporting period','Cash flow statement','Comparative figures'].map(label=>[label,'Not assessed','','','',''])])];
 }else if(template==='cashflow'){
  const rows:Value[][]=[['13-week cash forecast',month],['Planning inputs, not a prediction or the next month actuals. Positive numbers for receipts and payments.'],[],['Week','Opening cash','Collections','Supplier payments','Payroll / tax','Other payments','Net financing','Closing cash']];
  for(let i=5;i<=17;i++)rows.push([i-4,i===5?amount('1000'):`=H${i-1}`,0,0,0,0,0,`=B${i}+C${i}-D${i}-E${i}-F${i}+G${i}`]);rows.push([],['Minimum forecast cash','=MIN(H5:H17)'],['Required reserve',0],['Headroom','=B19-B20'],['Assumptions',''],['Actions / funding plan','']);sheets=[sheet('13 week forecast',rows,[1,2,3,4,5,6,7])];
 }else if(template==='close'){
  sheets=[sheet('Close checklist',[['Month-end close file',month],['Use actual evidence and journal IDs. This checklist does not sign off the accounting system.'],[],['Workstream','Status','Preparer','Reviewer','Evidence','Open difference AUD','Next action','Due date'],...['Bank reconciliation','Receivables and ECL','Supplier statements and accruals','Payroll and liabilities','Inventory and NRV','Fixed assets and depreciation','Prepayments','Revenue cut-off','Leases and borrowings','Tax controls','Provisions','Management accounts','Cash forecast','AFS and disclosures','Final review'].map(label=>[label,'Not started',model.displayName,'','',0,'',end])],[5])];
 }
 if(template!=='blank'){sheets.push(ledger,instructions);file.name=`${WORKPAPER_TEMPLATES[template]??'Working paper'} ${month}.xlsx`;}
 file.sheets=sheets;file.activeSheetId=sheets[0].id;syncWorkbook(file);return file;
}
