import type { Account, Line } from './types';
const definitions: [string, string, Account['type'], string, string?][] = [
 ['1000','Operating bank','asset','Cash'],
 ['1010','Petty cash','asset','Cash'],
 ['1100','Trade receivables','asset','Receivables','customer'],
 ['1110','Expected credit loss allowance','asset','Receivables'],
 ['1200','Inventory','asset','Inventory'],
 ['1210','Inventory NRV allowance','asset','Inventory'],
 ['1300','Prepaid insurance','asset','Prepayments'],
 ['1310','Prepaid subscriptions','asset','Prepayments'],
 ['1320','Accrued revenue','asset','Receivables'],
 ['1400','GST input tax credits','asset','Tax receivables'],
 ['1500','Plant and equipment — cost','asset','Property, plant & equipment'],
 ['1510','Plant and equipment — accumulated depreciation','asset','Property, plant & equipment'],
 ['1520','Right-of-use asset — cost','asset','Right-of-use assets'],
 ['1530','Right-of-use asset — accumulated depreciation','asset','Right-of-use assets'],
 ['1600','Deferred tax asset','asset','Deferred tax'],
 ['2000','Trade payables','liability','Payables','supplier'],
 ['2100','Accrued expenses','liability','Accruals'],
 ['2110','Net wages payable','liability','Employee liabilities'],
 ['2120','PAYG withholding payable','liability','Employee liabilities'],
 ['2130','Superannuation payable','liability','Employee liabilities'],
 ['2140','Other payroll deductions payable','liability','Employee liabilities'],
 ['2150','Annual leave provision','liability','Employee liabilities'],
 ['2160','Interest payable','liability','Accruals'],
 ['2200','GST output tax','liability','Tax payables'],
 ['2210','GST settlement payable','liability','Tax payables'],
 ['2300','Customer deposits / deferred revenue','liability','Deferred revenue'],
 ['2400','Warranty provision','liability','Provisions'],
 ['2410','Legal claim provision','liability','Provisions'],
 ['2500','Bank loan — non-current','liability','Non-current borrowings'],
 ['2510','Bank loan — current','liability','Current borrowings'],
 ['2520','Lease liability — non-current','liability','Non-current borrowings'],
 ['2530','Lease liability — current','liability','Current borrowings'],
 ['2600','Current income tax payable','liability','Tax payables'],
 ['2610','Deferred tax liability','liability','Deferred tax'],
 ['3000','Share capital','equity','Share capital'],
 ['3100','Retained earnings','equity','Retained earnings'],
 ['3200','Dividends declared','equity','Dividends'],
 ['4000','Product sales','income','Revenue'],
 ['4010','Service revenue','income','Revenue'],
 ['4020','Sales returns and discounts','income','Revenue'],
 ['4100','Interest income','income','Other income'],
 ['4200','Gain on asset disposal','income','Other income'],
 ['4300','Foreign exchange gains','income','Other income'],
 ['5000','Cost of goods sold','expense','Cost of sales'],
 ['5010','Inventory shrinkage','expense','Cost of sales'],
 ['5020','Inventory write-down to NRV','expense','Cost of sales'],
 ['6000','Salaries and wages','expense','Employee costs'],
 ['6010','Employer superannuation','expense','Employee costs'],
 ['6020','Annual leave expense','expense','Employee costs'],
 ['6100','Premises rent','expense','Occupancy'],
 ['6110','Utilities','expense','Occupancy'],
 ['6200','Insurance','expense','Administration'],
 ['6210','Software subscriptions','expense','Administration'],
 ['6220','Office supplies','expense','Administration'],
 ['6230','Repairs and maintenance','expense','Administration'],
 ['6240','Professional fees','expense','Administration'],
 ['6300','Marketing','expense','Selling costs'],
 ['6310','Freight and distribution','expense','Selling costs'],
 ['6400','Bank charges','expense','Finance costs'],
 ['6410','Interest expense','expense','Finance costs'],
 ['6420','Foreign exchange losses','expense','Finance costs'],
 ['6500','Depreciation — equipment','expense','Depreciation'],
 ['6510','Depreciation — right-of-use asset','expense','Depreciation'],
 ['6600','Expected credit loss expense','expense','Impairment'],
 ['6610','Bad debts written off','expense','Impairment'],
 ['6700','Warranty expense','expense','Provisions'],
 ['6710','Legal claim expense','expense','Provisions'],
 ['6800','Income tax expense — current','expense','Income tax'],
 ['6810','Income tax expense — deferred','expense','Income tax'],
 ['6900','Loss on asset disposal','expense','Other expenses'],
 ['6990','Suspense / unresolved items','asset','Unresolved items'],
];
const contraCredit = new Set(['1110','1210','1510','1530']);
const contraDebit = new Set(['3200','4020']);
export const ACCOUNTS: Account[] = definitions.map(([code,name,type,group,control])=>({code,name,type,group,normal:contraCredit.has(code)?'credit':contraDebit.has(code)?'debit':type==='asset'||type==='expense'?'debit':'credit',...(control?{control:control as 'customer'|'supplier'}:{})}));
export const ACCOUNT_MAP = Object.fromEntries(ACCOUNTS.map(a=>[a.code,a]));
export function balanceClassification(code:string):'Current assets'|'Non-current assets'|'Current liabilities'|'Non-current liabilities'|'Equity'|null {
 const account=ACCOUNT_MAP[code];if(!account)return null;
 if(account.type==='asset')return ['1500','1510','1520','1530','1600'].includes(code)?'Non-current assets':'Current assets';
 if(account.type==='liability')return ['2500','2520','2610'].includes(code)?'Non-current liabilities':'Current liabilities';
 return account.type==='equity'?'Equity':null;
}
export function dr(account:string, debit:number, contact?:string, memo?:string):Line { return {account,debit,credit:0,...(contact?{contact}:{}),...(memo?{memo}:{})}; }
export function cr(account:string, credit:number, contact?:string, memo?:string):Line { return {account,debit:0,credit,...(contact?{contact}:{}),...(memo?{memo}:{})}; }
