import type { PracticeCompany, PracticeState, SourceDocument, Journal } from './types';
import { journalsFor, trialBalance, profitAndLoss, financialPosition, subledger, cashFlow } from './engine';
import { money, numberMoney, sum, monthEnd } from './money';
import {asOfDate} from './workday-calendar';
import {ACCOUNTS,balanceClassification} from './accounts';
import {financialNotes,equityMovement,type NoteTable} from './financial-notes';
export function csvCell(value:unknown):string{let s=String(value??'');if(/^[=+@\t\r]/.test(s)||/^-[^\d]/.test(s))s="'"+s;return /[",\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
export function csv(headers:string[],rows:unknown[][]):string{return '\uFEFF'+[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');}
export function downloadFile(name:string,content:string|Uint8Array,type='text/plain;charset=utf-8'){const blob=new Blob([content as BlobPart],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),20000);}
export function htmlEscape(value:unknown):string{return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export const printableStyles=`*{box-sizing:border-box}body{font:14px/1.55 Arial,sans-serif;color:#182536;margin:0;padding:42px;background:#fff}h1{font-size:30px;line-height:1.1;margin:12px 0}h2{font-size:18px;margin-top:32px}p{margin:8px 0}.mast{display:flex;justify-content:space-between;gap:30px;border-bottom:3px solid #16385b;padding-bottom:24px;margin-bottom:28px}.brand{font-size:20px;font-weight:800;color:#16385b}.muted{color:#637084}.label{font-size:11px;letter-spacing:1.4px;text-transform:uppercase;color:#64748b}.meta{display:flex;justify-content:space-between;gap:24px;margin:24px 0}.number{text-align:right;font-variant-numeric:tabular-nums}table{width:100%;border-collapse:collapse;margin:18px 0;break-inside:auto}th{text-align:left;font-size:12px;letter-spacing:.5px;background:#eef3f8;padding:10px;border-bottom:1px solid #bac9d7}td{padding:10px;border-bottom:1px solid #e0e6ed;vertical-align:top}tr{break-inside:avoid}thead{display:table-header-group}.totals{margin-left:auto;width:300px}.totals div{display:flex;justify-content:space-between;padding:7px 0}.grand{border-top:2px solid #16385b;font-size:19px;font-weight:700}footer{border-top:1px solid #d9e2ec;margin-top:36px;padding-top:16px;font-size:11px;color:#6b7280}.note{background:#f4f7fb;padding:16px;border-left:3px solid #3468a5}.pagebreak{break-before:page}@page{size:A4;margin:15mm}@media print{body{padding:0}button{display:none}}`;
function wrap(title:string,body:string):string{return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${htmlEscape(title)}</title><style>${printableStyles}</style></head><body>${body}<footer>LEDGERLAB · FICTIONAL TRAINING DOCUMENT · AUD · Not valid for payment, tax filing or employment records.</footer></body></html>`;}
export function documentHTML(d:SourceDocument,company:PracticeCompany,state?:PracticeState):string{
 const e=htmlEscape;let content=`<div class="mast"><div><div class="brand">${(d.kind==='Supplier invoice'||d.kind==='Supplier credit note')?e(d.party):d.kind==='Bank statement'?'PRACTICE BANK':d.kind==='Payslip'?'HARBOUR & CO.':e(company.name.toUpperCase())}</div><p class="muted">Fictional accounting practice company<br>Brisbane, Queensland · AUD</p></div><div class="number"><div class="label">${e(d.kind)}</div><h1>${e(d.id)}</h1><span>${e(d.date)}</span></div></div><h2>${e(d.title)}</h2><div class="meta"><div><div class="label">${d.kind==='Sales invoice'?'Bill to':'Prepared for / by'}</div><strong>${e(d.party)}</strong></div><div class="number">${d.dueDate?`<div class="label">Due date</div>${e(d.dueDate)}`:''}</div></div>`;
 if(d.kind==='Bank statement'){
  const rows=company.bank.filter(r=>r.date.slice(0,7)===d.date.slice(0,7));content+=`<div class="meta"><div>Opening balance<br><strong>${money(Number(d.metadata?.opening??0))}</strong></div><div>Money in<br><strong>${money(sum(rows.filter(r=>r.amount>0).map(r=>r.amount)))}</strong></div><div>Money out<br><strong>${money(-sum(rows.filter(r=>r.amount<0).map(r=>r.amount)))}</strong></div><div>Closing balance<br><strong>${money(d.total)}</strong></div></div><table><thead><tr><th>Date</th><th>Description / reference</th><th class="number">Money out</th><th class="number">Money in</th><th class="number">Balance</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date}</td><td>${e(r.description)}<br><small>${e(r.reference)}</small></td><td class="number">${r.amount<0?numberMoney(-r.amount):'—'}</td><td class="number">${r.amount>0?numberMoney(r.amount):'—'}</td><td class="number">${numberMoney(r.balance)}</td></tr>`).join('')}</tbody></table>`;
 } else if(d.kind==='Payroll register'){
  const pay=company.payroll[d.date.slice(0,7)]??[];content+=`<table><thead><tr><th>Employee</th><th class="number">Gross</th><th class="number">Withheld</th><th class="number">Deductions</th><th class="number">Net</th><th class="number">Super</th></tr></thead><tbody>${pay.map(p=>`<tr><td>${e(p.name)}<br><small>${e(p.role)}</small></td>${[p.gross,p.withholding,p.deductions,p.net,p.super].map(v=>`<td class="number">${numberMoney(v)}</td>`).join('')}</tr>`).join('')}<tr><td><strong>Total</strong></td>${['gross','withholding','deductions','net','super'].map(k=>`<td class="number"><strong>${numberMoney(sum(pay.map(p=>Number(p[k as keyof typeof p]))))}</strong></td>`).join('')}</tr></tbody></table>`;
 } else if(d.lines.length){content+=`<table><thead><tr><th>Description</th><th class="number">Quantity</th><th class="number">Unit price</th><th class="number">Net</th><th class="number">GST</th></tr></thead><tbody>${d.lines.map(l=>`<tr><td>${e(l.description)}</td><td class="number">${l.quantity}</td><td class="number">${numberMoney(l.unitPrice)}</td><td class="number">${numberMoney(l.net)}</td><td class="number">${numberMoney(l.tax)}</td></tr>`).join('')}</tbody></table><div class="totals"><div><span>${d.kind==='Payslip'?'Gross pay':'Subtotal'}</span><strong>${money(d.net)}</strong></div>${d.kind==='Payslip'?`<div><span>Withholding</span><span>(${money(Number(d.metadata?.withholding??0))})</span></div><div><span>Other deductions</span><span>(${money(Number(d.metadata?.deductions??0))})</span></div>`:`<div><span>GST</span><span>${money(d.tax)}</span></div>`}<div class="grand"><span>${d.kind==='Payslip'?'Net pay':'Total'}</span><span>${money(d.total)}</span></div></div>`;}
 if(d.notes.length)content+=`<h2>Supporting information</h2>${d.notes.map(n=>`<p>${e(n)}</p>`).join('')}`;
 return wrap(d.title,content);
}
export function journalCSV(journals:Journal[]):string{return csv(['Journal ID','Date','Reference','Source document','Narration','Module','Account','Contact','Debit AUD','Credit AUD','Exercise','Origin','Cash flow class','Inventory item','Line memo'],journals.flatMap(j=>j.lines.map(l=>[j.id,j.date,j.reference,j.sourceId??'',j.description,j.module,l.account,l.contact??'',(l.debit/100).toFixed(2),(l.credit/100).toFixed(2),j.exerciseId??'',j.origin??'seed',j.cashClass??'',l.itemId??'',l.memo??''])));}
export function trialBalanceCSV(journals:Journal[],to='2025-12-31'):string{return csv(['Account','Name','Type','Debit AUD','Credit AUD'],trialBalance(journals,to).map(r=>[r.code,r.name,r.type,(r.debit/100).toFixed(2),(r.credit/100).toFixed(2)]));}
export function bankCSV(company:PracticeCompany,month='2025-12'):string{return csv(['Transaction ID','Date','Description','Reference','Amount AUD','Balance AUD'],company.bank.filter(r=>r.date.startsWith(month)).map(r=>[r.id,r.date,r.description,r.reference,(r.amount/100).toFixed(2),(r.balance/100).toFixed(2)]));}
export function payrollCSV(company:PracticeCompany,month='2025-12'):string{return csv(['Employee ID','Name','Salary','Allowance','Overtime','Gross','Withholding','Deductions','Net','OTE','Super rate percent','Super'],(company.payroll[month]??[]).map(p=>[p.employeeId,p.name,...[p.salary,p.allowance,p.overtime,p.gross,p.withholding,p.deductions,p.net,p.ote].map(v=>(v/100).toFixed(2)),p.superRateBps/100,(p.super/100).toFixed(2)]));}

// Small standards-compliant ZIP writer, STORE method. Document text is generated, never fetched.
export function zipFiles(files:{name:string;content:string}[]):Uint8Array{
 const enc=new TextEncoder(),chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;
 const table=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
 const crc=(data:Uint8Array)=>{let c=0xffffffff;for(const b of data)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;};
 for(const f of files){const safePath=f.name.split(/[\\/]/).filter(Boolean).map(part=>part==='..'?'__':part.replace(/[<>:\x00-\x1F]/g,'_')).join('/');const name=enc.encode(safePath),data=enc.encode(f.content),checksum=crc(data),local=new Uint8Array(30+name.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,checksum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);local.set(name,30);chunks.push(local,data);
  const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,checksum,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=local.length+data.length;
 }
 const centralSize=sum(central.map(c=>c.length)),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);const all=[...chunks,...central,end],out=new Uint8Array(sum(all.map(a=>a.length)));let pos=0;for(const a of all){out.set(a,pos);pos+=a.length;}return out;
}
export function sourcePack(company:PracticeCompany,state:PracticeState,month=state.career?.activeMonth??'2025-12',includeAnswers=false){const docs=[...company.documents,...state.customDocuments].filter(d=>d.date.startsWith(month)||d.id==='TB-OPEN'||company.exercises.some(e=>e.documents.includes(d.id)));const files=[{name:'START-HERE.txt',content:`LEDGERLAB ACCOUNTING PRACTICE\n${company.name} · Seed ${company.seed}\nAll figures are AUD. All entities and documents are fictional.\n\n1. Read TB-OPEN and the accounting policies.\n2. ${state.workday?'Open Today, read the onboarding email, and process only evidence received by '+state.workday.today+'. The PC date is separate from the accounting month.':'Process the unposted '+month+' evidence.'}\n3. Reconcile bank, customers, suppliers, payroll and balance-sheet schedules.\n4. Complete adjusting journals, taxes and financial statements.\n5. Document your conclusions in the audit support workspace.\n\nHTML documents can be opened in a browser and printed to PDF. CSV amounts are in dollars, with headers. The app ledger stores integer cents.\nThe unadjusted ledger includes your posted attempts. Answers are included only when explicitly selected.\nTax assumptions and exclusions are stated in the case memos. This is a training simulation, not a tax filing or live payroll system.\n`},{name:'data/bank-statement.csv',content:bankCSV(company,month)},{name:'data/payroll-register.csv',content:payrollCSV(company,month)},{name:'data/learner-journals.csv',content:journalCSV(journalsFor(company,state))},{name:'data/learner-trial-balance.csv',content:trialBalanceCSV(journalsFor(company,state),state.workday?asOfDate(state):'2025-12-31')},{name:'data/learner-financial-statements.html',content:financialStatementsHTML(company,state,'2025-01-01',state.workday?asOfDate(state):'2025-12-31')},{name:'data/learner-backup.json',content:JSON.stringify({format:'LedgerLab backup',version:1,state},null,2)},...docs.map(d=>({name:`documents/${d.kind.toLowerCase().replace(/ /g,'-')}/${d.id}.html`,content:documentHTML(d,company,state)}))];if(includeAnswers)files.push({name:'answers/solution-journals.csv',content:journalCSV([company.opening,...company.solutionJournals])},{name:'answers/solution-trial-balance.csv',content:trialBalanceCSV([company.opening,...company.solutionJournals])},{name:'answers/worked-explanations.txt',content:company.exercises.map(e=>`${e.id}: ${e.title}\n${e.reasoning}\n${JSON.stringify(e.expected,null,2)}`).join('\n\n')});return zipFiles(files);}
export function financialStatementsHTML(company:PracticeCompany,state:PracticeState,from='2025-01-01',to=state.career?monthEnd(state.career.activeMonth):'2025-12-31'){
 const js=journalsFor(company,state),pl=profitAndLoss(js,from,to),bs=financialPosition(js,to),cf=cashFlow(js,from,to),eq=equityMovement(js,from,to),notes=financialNotes(company,state,to),opening=financialPosition([company.opening],'2024-12-31'),e=htmlEscape;
 const line=(name:string,amount:number,bold=false)=>`<tr><td>${bold?'<strong>':''}${e(name)}${bold?'</strong>':''}</td><td class="number">${bold?'<strong>':''}${numberMoney(amount)}${bold?'</strong>':''}</td></tr>`;
 const noteTable=(t:NoteTable)=>`<h3>${e(t.title)}</h3><table><thead><tr><th>Line item</th>${t.columns.map(c=>`<th class="number">${e(c)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr${r.total?' style="font-weight:700;border-top:2px solid #16385b"':''}><td>${e(r.label)}</td>${r.values.map(v=>`<td class="number">${numberMoney(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const positionSections=['Current assets','Non-current assets','Current liabilities','Non-current liabilities','Equity'];
 const position=positionSections.map(section=>{const accounts=ACCOUNTS.filter(a=>balanceClassification(a.code)===section),sign=section.includes('assets')?1:-1,total=sum(accounts.map(a=>bs.balances[a.code]))*sign+(section==='Equity'?bs.profit:0),prior=sum(accounts.map(a=>opening.balances[a.code]))*sign;return `<tr><th colspan="3">${e(section)}</th></tr>${accounts.filter(a=>bs.balances[a.code]||opening.balances[a.code]).map(a=>`<tr><td>${e(a.name)}</td><td class="number">${numberMoney(bs.balances[a.code]*sign)}</td><td class="number">${numberMoney(opening.balances[a.code]*sign)}</td></tr>`).join('')}${section==='Equity'?`<tr><td>Current-year profit</td><td class="number">${numberMoney(bs.profit)}</td><td class="number">—</td></tr>`:''}<tr style="font-weight:700"><td>Total ${e(section.toLowerCase())}</td><td class="number">${numberMoney(total)}</td><td class="number">${numberMoney(prior)}</td></tr>`;}).join('');
 let body=`<style>h2,h3{break-after:avoid}.afs-note{margin-top:30px}.afs-note h2{border-bottom:1px solid #bdccdc;padding-bottom:10px}.toc{columns:2;column-gap:28px}.toc li{break-inside:avoid;margin:8px 0}.assessment{white-space:pre-wrap}.status-open{color:#956221}.status-complete{color:#287357}</style><div class="mast"><div><div class="brand">${e(company.name)}</div><h1>Financial statements</h1><p>Training draft · ${e(from)} to ${e(to)} · AUD</p></div><div class="label">LedgerLab<br>Seed ${company.seed}</div></div><p class="note">These statements reflect the learner ledger at export. Incomplete or incorrect entries affect the figures. The supplied comparative information is limited to the 31 December 2024 financial position. This teaching draft is not a signed, audited or statutory-compliant set of accounts.</p><h2>Contents</h2><ol><li>Statement of profit or loss and comprehensive income</li><li>Statement of financial position</li><li>Statement of changes in equity</li><li>Statement of cash flows and operating reconciliation</li><li>Notes to the financial statements</li><li>Preparer workpaper conclusions</li></ol><h2>${notes.length?'Note index':'Interim reporting boundary'}</h2><ol class="toc">${notes.map(n=>`<li>${e(n.title)} · ${state.disclosures?.[n.id]?.completed?'assessment complete':'assessment open'}</li>`).join('')}</ol><p>${notes.length?`Notes 3–18 use year-to-date movements to ${e(to)} and comparative financial position balances. Primary performance, equity-movement and cash-flow statements use the selected period.`:'Annual note evidence and year-end estimate work are not released before December. This is an interim management-reporting draft. The absence of notes here is not a completed disclosure assessment.'}</p>
 <section class="pagebreak"><h2>Statement of profit or loss and comprehensive income</h2><p>${e(from)} to ${e(to)} · AUD</p><table><thead><tr><th>Account</th><th class="number">AUD</th></tr></thead><tbody>${line('Revenue',pl.revenue)}${line('Cost of sales',-pl.cogs)}${line('Gross profit',pl.grossProfit,true)}${pl.groups.filter(g=>!['Cost of sales','Income tax'].includes(g.name)).map(g=>line(g.name,-g.amount)).join('')}${line('Other income',pl.otherIncome)}${line('Profit before tax',pl.profitBeforeTax,true)}${line('Current income tax expense',-pl.balances['6800'])}${line('Deferred income tax expense / (benefit)',-pl.balances['6810'])}${line('Profit for the period',pl.netProfit,true)}${line('Other comprehensive income (none modelled in this case)',0)}${line('Total comprehensive income',pl.netProfit,true)}</tbody></table><p>Comparative performance information has not been supplied. ${notes.length?'Notes 3, 4 and 5 support revenue, expenses and taxation.':'Annual tax and estimate adjustments may remain outstanding until December.'}</p></section>
 <section class="pagebreak"><h2>Statement of financial position</h2><table><thead><tr><th>Line item</th><th class="number">${e(to)}</th><th class="number">31 Dec 2024</th></tr></thead><tbody>${position}<tr style="font-weight:700"><td>Total assets</td><td class="number">${numberMoney(bs.assets)}</td><td class="number">${numberMoney(opening.assets)}</td></tr><tr style="font-weight:700"><td>Total liabilities and equity</td><td class="number">${numberMoney(bs.liabilities+bs.equity)}</td><td class="number">${numberMoney(opening.liabilities+opening.equity)}</td></tr><tr><td>Unreconciled accounting-equation difference</td><td class="number">${numberMoney(bs.difference)}</td><td class="number">${numberMoney(opening.difference)}</td></tr></tbody></table><p>Current classification follows the supplied operating cycle, provision settlement assumptions and explicit debt-current accounts. Suspense is unresolved and must be investigated. ${notes.length?'Notes 6–17 support the statement balances.':'Use current source evidence and monthly role deliverables to support the interim balances.'}</p></section>
 <section class="pagebreak"><h2>Statement of changes in equity</h2><p>${e(from)} to ${e(to)} · AUD</p><table><tbody>${line('Opening equity at the start of the selected period',eq.opening.equity)}${line('Profit / comprehensive income for the selected period',eq.profit)}${line('Share capital contributions / (reductions)',eq.capital)}${line('Dividends and other equity movements',eq.other)}${line('Closing equity',eq.closing.equity,true)}${line('Equity rollforward difference',eq.difference)}</tbody></table><p>Opening equity includes retained profit from earlier months where a monthly performance period is selected. No other comprehensive income is modelled in this case. Agree the movements to authorised shareholder records.</p></section>
 <section class="pagebreak"><h2>Statement of cash flows</h2><p>${e(from)} to ${e(to)} · AUD</p><table><tbody>${line('Operating cash flows',cf.direct.operating)}${line('Investing cash flows',cf.direct.investing)}${line('Financing cash flows',cf.direct.financing)}${line('Net change in cash and cash equivalents',sum(Object.values(cf.direct)),true)}${line('Opening cash and cash equivalents',cf.opening)}${line('Closing cash and cash equivalents',cf.closing,true)}</tbody></table><h3>Reconciliation of profit to operating cash flow</h3><table><tbody>${line('Profit for the period',cf.profit)}${cf.noncash.map(r=>line(r.name,r.amount)).join('')}${line('Interest expense classified as financing',cf.financingInterest)}${line('Interest income classified as investing',cf.investingInterest)}${line('Gain / loss on asset disposal adjustment',cf.gainDisposal+cf.lossDisposal)}${cf.workingCapital.map(r=>line(r.name,r.amount)).join('')}${line('Control movements relating to investing and financing',cf.classificationAdjustments)}${line('Net operating cash from the indirect bridge',cf.indirectOperating,true)}${line('Difference to actual operating cash flows',cf.operatingDifference)}</tbody></table><p>The bridge is derived from ledger movements with no balancing plug. The selected policy classifies interest paid as financing and interest received as investing. Non-cash lease commencement is excluded. ${notes.length?'Notes 6, 11 and 14 provide supporting cash and financing movements.':'Reconcile the current cash and financing movements to released source records.'}</p></section>
 <section class="pagebreak"><h2>Notes to the financial statements</h2><p>Amounts in AUD. These case discussions and preparer assessments are a teaching draft. Outstanding assessments and evidence gaps remain visible.</p>${notes.map(n=>{const saved=state.disclosures?.[n.id];return `<section class="afs-note"><h2>${n.id}. ${e(n.title)}</h2>${n.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}${n.tables.map(noteTable).join('')}<p class="muted">Source evidence: ${n.documents.map(e).join(', ')}</p>${n.source?`<p><a href="${e(n.source.url)}">${e(n.source.label)}</a></p>`:''}<h3>Preparer assessment</h3><p class="${saved?.completed?'status-complete':'status-open'}">${saved?.completed?'Assessment marked complete by the learner':'Assessment remains open'}</p>${saved?.text?`<p class="assessment">${e(saved.text)}</p>`:`<ul>${n.prompts.map(p=>`<li>${e(p)}</li>`).join('')}</ul><p>No preparer assessment has been saved.</p>`}</section>`;}).join('')}</section>
 <section class="pagebreak"><h2>Preparer workpaper conclusions</h2>${Object.values(state.workpapers).filter(w=>w.conclusion).map(w=>`<h3>${e(w.id)}</h3><p class="assessment">${e(w.conclusion)}</p><p class="muted">Prepared: ${w.prepared?e(w.preparer):'not signed'} · Reviewed: ${w.reviewed?e(w.reviewer):'not signed / requires review'}</p><p class="muted">Evidence: ${w.evidence.map(e).join(', ')}</p>`).join('')||'<p>No workpaper conclusions have been saved.</p>'}</section>`;
 return wrap('Financial statements — '+company.name,body);
}
