import { dr, cr } from './accounts';
import { cents, pct, sum, isoMonth, monthEnd, addDays } from './money';
import type { PracticeCompany, Journal, SourceDocument, Contact, Employee, PayRow, Asset, StockItem, Exercise, Line } from './types';

export function randomSource(seed:number) { let a=seed>>>0; return ()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;}; }
export function payrollFor(employees:Employee[],month:number):PayRow[] {
 return employees.map(e=>{const salary=e.monthlySalary,allowance=e.ordinaryAllowance,overtime=month===12?e.overtime:Math.round(e.overtime/2),gross=salary+allowance+overtime,withholding=pct(gross,e.withholdingBps),ote=salary+allowance,superRateBps=month<7?1150:1200;
 return {employeeId:e.id,name:e.name,role:e.role,salary,allowance,overtime,gross,taxable:gross,withholding,deductions:e.postTaxDeduction,net:gross-withholding-e.postTaxDeduction,ote,superRateBps,super:pct(ote,superRateBps),leaveHours:13.33};});
}
export function monthlyDepreciation(a:Asset):number { return Math.round((a.cost-a.residual)/a.lifeMonths); }
function balances(journals:Journal[]):Record<string,number> { const b:Record<string,number>={};for(const j of journals)for(const l of j.lines)b[l.account]=(b[l.account]??0)+l.debit-l.credit;return b; }

export function generateCompany(seed=271828):PracticeCompany {
 const rnd=randomSource(seed),int=(lo:number,hi:number)=>lo+Math.floor(rnd()*(hi-lo+1));
 const contacts:Contact[]=[
  ...['Northline Works','Cedarfield Construction','Arc Studio Group','Beacon Interiors','Riverbend Facilities','Summit Trade Group','Westbrook Projects'].map((name,i)=>({id:`C${i+1}`,name,kind:'customer' as const,email:`accounts@customer${i+1}.example`,address:`${18+i*7} Example Street, Brisbane QLD 4000`,terms:30})),
  ...['Pacific Trade Supplies','Foundry Wholesale','Coastal Components','City Property Services','BrightGrid Energy','Cloudstack Software','Anchor Insurance','Workshop Equipment Co.','Studio North Marketing'].map((name,i)=>({id:`S${i+1}`,name,kind:'supplier' as const,email:`accounts@supplier${i+1}.example`,address:`${30+i*9} Sample Road, Brisbane QLD 4000`,terms:30}))
 ];
 const employees:Employee[]=[
  ['E01','Morgan Lee','Operations manager',6900,150,0,2400,0,116,4183],
  ['E02','Alex Taylor','Account manager',5800,100,240,2200,5000,92,3523],
  ['E03','Sam Patel','Warehouse supervisor',5200,100,320,2100,0,104,3158],
  ['E04','Jamie Brooks','Sales coordinator',4600,0,160,1900,0,76,2794],
  ['E05','Riley Chen','Warehouse assistant',4100,0,280,1700,2500,64,2490],
  ['E06','Jordan Ellis','Office administrator',4400,0,0,1800,0,88,2672],
 ].map(r=>({id:r[0] as string,name:r[1] as string,role:r[2] as string,monthlySalary:cents(r[3] as number),ordinaryAllowance:cents(r[4] as number),overtime:cents(r[5] as number),withholdingBps:r[6] as number,postTaxDeduction:r[7] as number,annualLeaveHours:r[8] as number,hourlyRate:r[9] as number}));
 const assets:Asset[]=[
  {id:'FA-001',name:'Warehouse racking',category:'Fixtures',purchaseDate:'2023-01-01',availableDate:'2023-01-01',cost:cents(48000),residual:cents(3000),lifeMonths:120,openingAccumulated:cents(9000),supplier:'Pacific Trade Supplies'},
  {id:'FA-002',name:'Delivery vehicle',category:'Vehicles',purchaseDate:'2023-01-01',availableDate:'2023-01-01',cost:cents(60000),residual:cents(12000),lifeMonths:60,openingAccumulated:cents(19200),supplier:'Example Motors'},
  {id:'FA-003',name:'Office equipment',category:'Equipment',purchaseDate:'2024-01-01',availableDate:'2024-01-01',cost:cents(18000),residual:0,lifeMonths:36,openingAccumulated:cents(6000),supplier:'Workshop Equipment Co.'},
  {id:'FA-004',name:'Electric pallet stacker',category:'Equipment',purchaseDate:'2025-12-12',availableDate:'2025-12-16',cost:cents(24000+int(0,8)*500),residual:cents(2000),lifeMonths:60,openingAccumulated:0,supplier:'Workshop Equipment Co.',documentId:'PI-CAPEX-12'},
 ];
 const inventory:StockItem[]=[
  ['P01','Commercial door closer','unit',120,265],['P02','Architectural handle set','set',85,185],['P03','Access control kit','kit',240,520],['P04','Safety sign pack','pack',36,82],['P05','LED work light','unit',55,122],
 ].map(r=>({id:r[0] as string,name:r[1] as string,unit:r[2] as string,cost:cents(r[3] as number),price:cents(r[4] as number),openingQty:180+int(0,4)*10,bought:Array(12).fill(0),sold:Array(12).fill(0),countVariance:r[0]==='P01'?-7:0,nrv:cents(r[0]==='P05'?42:r[4] as number)}));
 const all:Journal[]=[],docs:SourceDocument[]=[],exercises:Exercise[]=[];
 const journal=(id:string,date:string,description:string,lines:Line[],module='Bookkeeping',sourceId?:string,cashClass?:Journal['cashClass']):Journal=>({id,date,description,reference:sourceId??id,module,lines:lines.filter(l=>l.debit||l.credit),sourceId,origin:'seed',cashClass});
 const push=(j:Journal)=>{all.push(j);return j;};
 const doc=(d:Partial<SourceDocument>&Pick<SourceDocument,'id'|'kind'|'date'|'party'|'title'>):SourceDocument=>{const x:SourceDocument={lines:[],net:0,tax:0,total:0,notes:[],journalIds:[],...d};docs.push(x);return x;};
 const exercise=(id:string,title:string,module:string,brief:string,expected:Journal[],documents:string[],reasoning:string,hints:string[],difficulty:Exercise['difficulty']='Intermediate',dependsOn:string[]=[],pitfalls:string[]=[])=>{
  for(const j of expected)j.exerciseId=id;
  exercises.push({id,title,module,brief,expected,documents,reasoning,hints,difficulty,dependsOn,pitfalls,minutes:difficulty==='Advanced'?20:difficulty==='Foundation'?8:12,points:difficulty==='Advanced'?20:difficulty==='Foundation'?10:15,assertion:module==='Revenue'?'Cut-off and accuracy':module==='Provisions'?'Completeness and valuation':module==='Assets'?'Existence and valuation':'Completeness and accuracy'});
 };
 const openingLines:Line[]=[dr('1000',cents(210000)),dr('1010',cents(500)),dr('1100',cents(12000),'C7'),cr('1110',cents(3000)),dr('1200',sum(inventory.map(i=>i.openingQty*i.cost))),dr('1500',sum(assets.filter(a=>a.id!=='FA-004').map(a=>a.cost))),cr('1510',sum(assets.map(a=>a.openingAccumulated))),dr('1600',cents(2000)),cr('2610',cents(1000)),cr('2150',cents(14000)),cr('2400',cents(6000)),cr('2500',cents(56000)),cr('2510',cents(24000)),cr('2600',cents(4000)),cr('3000',cents(100000))];
 const openingDifference=sum(openingLines.map(l=>l.debit-l.credit));openingLines.push(cr('3100',openingDifference));
 const opening=journal('OPEN-2025','2024-12-31','Agreed opening trial balance',openingLines,'Opening balances','TB-OPEN');
 doc({id:'TB-OPEN',kind:'Memo',date:'2024-12-31',party:'Harbour & Co.',title:'Opening balances and accounting policies',notes:['All opening balances have been agreed. The 2024 income statement is not supplied. The financial position comparative is 31 December 2024.','All documents, people, bank details and entities in this case are fictional. Currency: AUD. Calendar year-end: 31 December 2025.','The business uses accrual accounting, a perpetual inventory system with fixed unit costs, monthly GST reporting and a monthly full-charge depreciation convention from availability for use.','Interest paid is classified as financing; interest received as investing. Income tax payments are operating cash flows.','The exercise tax rate is 25%. PAYG withholding uses stated training percentages, not statutory withholding tables. No payroll tax, workers compensation or tax offsets are modelled.'],journalIds:[opening.id]});
 doc({id:'SI-2024-118',kind:'Sales invoice',date:'2024-11-15',dueDate:'2024-12-15',party:'Westbrook Projects',title:'Opening overdue customer invoice',lines:[{description:'Opening carried-forward invoice balance (including GST previously accounted for)',quantity:1,unitPrice:cents(12000),net:cents(12000),tax:0}],net:cents(12000),total:cents(12000),notes:['Carried in opening receivables. Do not post again. No payment has been received during 2025. Opening ECL allowance: $3,000.'],journalIds:[opening.id]});
 const payments:{date:string;amount:number;description:string;contact:string;sourceId:string;side:'customer'|'supplier';cashClass?:Journal['cashClass'];exercise?:string}[]=[];
 const payroll:Record<string,PayRow[]>={};
 for(let m=1;m<=12;m++) {
  const month=isoMonth(m),end=monthEnd(month),monthJ:Journal[]=[];
  for(let i=0;i<15;i++) {
   const item=inventory[i%5],q=int(16,32)+(m>9?3:0),net=item.price*q,tax=pct(net,1000),contact=contacts[(i+m)%6],day=String(2+i*2).padStart(2,'0'),date=`${month}-${Math.min(Number(day),26).toString().padStart(2,'0')}`,id=`SI-${String(m).padStart(2,'0')}-${String(i+1).padStart(3,'0')}`;
   inventory[i%5].sold[m-1]+=q;
   const j=push(journal(`J-${id}`,date,`Sale to ${contact.name}`, [dr('1100',net+tax,contact.id),cr('4000',net),cr('2200',tax),dr('5000',item.cost*q),cr('1200',item.cost*q)],'Sales',id));monthJ.push(j);
   doc({id,kind:'Sales invoice',date,dueDate:addDays(date,30),party:contact.name,title:`Invoice ${id}`,lines:[{description:item.name,quantity:q,unitPrice:item.price,net,tax,account:'4000',itemId:item.id}],net,tax,total:net+tax,notes:['Goods dispatched and accepted on the invoice date. GST 10%. Cost of goods sold is recorded with the invoice.'],journalIds:[j.id],metadata:{contactId:contact.id}});
   const paymentDate=addDays(date,18+int(0,24));
   if(i===13&&m===12) {payments.push({date:'2025-12-31',amount:Math.round((net+tax)/2),description:`Part receipt ${contact.name}`,contact:contact.id,sourceId:id,side:'customer'});}
   else if(paymentDate<='2025-12-31')payments.push({date:paymentDate,amount:net+tax,description:`Receipt ${contact.name}`,contact:contact.id,sourceId:id,side:'customer'});
   if(m===12&&i===3)exercise('EX-SALE','Post a credit sale and cost of sales','Sales',`A dispatched order is still in the unprocessed inbox. Record the invoice, GST and the inventory cost using the dispatch information.`,[j],[id],`Recognise the receivable at the gross invoice amount, revenue excluding GST, and the GST liability. Separately move ${q} units at ${item.cost/100} per unit from inventory to cost of sales.`,['The customer owes the GST-inclusive amount.','The revenue and inventory entries belong on the same dispatch date.'],'Foundation',[],['Omitting cost of sales overstates inventory and profit.'] );
  }
  for(let i=0;i<3;i++) {
   const contact=contacts[(i+m+2)%6],net=cents(3800+int(0,12)*200),tax=pct(net,1000),date=`${month}-${String(8+i*8).padStart(2,'0')}`,id=`SI-SVC-${m}-${i+1}`;
   const j=push(journal(`J-${id}`,date,`Installation services — ${contact.name}`,[dr('1100',net+tax,contact.id),cr('4010',net),cr('2200',tax)],'Sales',id));
   doc({id,kind:'Sales invoice',date,dueDate:addDays(date,30),party:contact.name,title:`Service invoice ${id}`,lines:[{description:'Completed site installation services',quantity:1,unitPrice:net,net,tax,account:'4010'}],net,tax,total:net+tax,notes:['Customer accepted the completed work on the invoice date.'],journalIds:[j.id],metadata:{contactId:contact.id}});
   const datePaid=addDays(date,25);if(datePaid<='2025-12-31')payments.push({date:datePaid,amount:net+tax,description:`Service receipt ${contact.name}`,contact:contact.id,sourceId:id,side:'customer'});
  }
  for(let i=0;i<3;i++) {
   const contact=contacts[7+i],date=`${month}-${String(3+i*3).padStart(2,'0')}`,id=`PI-${String(m).padStart(2,'0')}-${i+1}`,items=inventory.filter((_,ix)=>ix%3===i);
   const lines=items.map(item=>{const q=item.sold[m-1]+int(0,8);item.bought[m-1]=q;const net=q*item.cost;return {description:item.name,quantity:q,unitPrice:item.cost,net,tax:pct(net,1000),itemId:item.id,account:'1200'};});
   const net=sum(lines.map(l=>l.net)),tax=sum(lines.map(l=>l.tax));
   const j=push(journal(`J-${id}`,date,`Stock received from ${contact.name}`,[dr('1200',net),dr('1400',tax),cr('2000',net+tax,contact.id)],'Purchases',id));
   doc({id,kind:'Supplier invoice',date,dueDate:addDays(date,30),party:contact.name,title:`Supplier invoice ${id}`,lines,net,tax,total:net+tax,notes:['The receiving team signed for all listed units on the invoice date. No freight or purchase discounts.'],journalIds:[j.id],metadata:{contactId:contact.id}});
   const paid=addDays(date,28);if(paid<='2025-12-31')payments.push({date:paid,amount:net+tax,description:`Payment ${contact.name}`,contact:contact.id,sourceId:id,side:'supplier'});
   if(m===12&&i===1)exercise('EX-PURCHASE','Record inventory received on credit','Purchases','The goods received note and supplier invoice agree. Record the inventory acquisition and recoverable GST.',[j],[id],'Inventory includes purchase cost excluding recoverable GST. Credit the named supplier for the gross amount.',['Use the supplier control account with a supplier contact.','Do not debit cost of sales before the stock is sold.'],'Foundation');
  }
  const expenses:[string,number,string,string][]=[['Premises rent',3500,'6100','S4'],['Utilities',780+int(0,12)*10,'6110','S5'],['Office supplies',250+int(0,8)*20,'6220','S3'],['Marketing retainer',1300,'6300','S9'],['Distribution costs',950+int(0,8)*50,'6310','S1']];
  for(let i=0;i<expenses.length;i++){
   if(m===12&&i===1)continue;
   const [description,amount,account,contactId]=expenses[i],net=cents(amount),tax=pct(net,1000),date=`${month}-${String(5+i*3).padStart(2,'0')}`,id=`PI-EXP-${m}-${i+1}`,contact=contacts.find(c=>c.id===contactId)!;
   const j=push(journal(`J-${id}`,date,description,[dr(account,net),dr('1400',tax),cr('2000',net+tax,contactId)],'Purchases',id));
   doc({id,kind:'Supplier invoice',date,dueDate:addDays(date,14),party:contact.name,title:`${description} — ${month}`,lines:[{description,quantity:1,unitPrice:net,net,tax,account}],net,tax,total:net+tax,notes:['The service relates entirely to the stated month. GST 10%.'],journalIds:[j.id],metadata:{contactId}});
   payments.push({date:addDays(date,10),amount:net+tax,description,contact:contactId,sourceId:id,side:'supplier'});
  }
  const pay=payrollFor(employees,m);payroll[month]=pay;
  const gross=sum(pay.map(p=>p.gross)),netPay=sum(pay.map(p=>p.net)),withholding=sum(pay.map(p=>p.withholding)),deductions=sum(pay.map(p=>p.deductions)),superannuation=sum(pay.map(p=>p.super));
  const pj=push(journal(`J-PAY-${m}`,`${month}-25`,`Payroll accrual — ${month}`,[dr('6000',gross),dr('6010',superannuation),cr('2110',netPay),cr('2120',withholding),cr('2130',superannuation),cr('2140',deductions)],'Payroll',`PAY-${month}`));
  const payCash=push(journal(`J-PAY-BANK-${m}`,`${month}-26`,`Net wages paid — ${month}`,[dr('2110',netPay),cr('1000',netPay)],'Payroll',`PAY-${month}`,'operating'));
  push(journal(`J-PAYG-BANK-${m}`,`${month}-28`,`PAYG and deductions paid — ${month}`,[dr('2120',withholding),dr('2140',deductions),cr('1000',withholding+deductions)],'Payroll',`PAY-${month}`,'operating'));
  if(m<12)push(journal(`J-SUPER-BANK-${m}`,end,`Employer super paid — ${month}`,[dr('2130',superannuation),cr('1000',superannuation)],'Payroll',`PAY-${month}`,'operating'));
  doc({id:`PAY-${month}`,kind:'Payroll register',date:`${month}-25`,party:'Harbour & Co.',title:`Payroll register — ${month}`,lines:pay.map(p=>({description:`${p.name} — gross pay`,quantity:1,unitPrice:p.gross,net:p.gross,tax:0})),net:gross,total:gross,notes:[`Gross ${gross/100}; withholding ${withholding/100}; post-tax deductions ${deductions/100}; net pay ${netPay/100}; employer super ${superannuation/100}.`,`Use the case withholding percentages supplied per employee. These are teaching rates, not ATO tax tables. Super rate ${(m<7?11.5:12)}% of salary and ordinary allowances; separately identified overtime is excluded from OTE in this case.`,'Net wages were paid on the 26th. PAYG and other deductions were remitted on the 28th. December super remains unpaid at year-end.'],journalIds:[pj.id,payCash.id],metadata:{gross,netPay,withholding,deductions,superannuation}});
  for(const p of pay)doc({id:`PS-${month}-${p.employeeId}`,kind:'Payslip',date:`${month}-25`,party:p.name,title:`Payslip ${month} · ${p.name}`,lines:[{description:'Ordinary salary',quantity:1,unitPrice:p.salary,net:p.salary,tax:0},{description:'Ordinary allowance',quantity:1,unitPrice:p.allowance,net:p.allowance,tax:0},{description:'Overtime (non-OTE)',quantity:1,unitPrice:p.overtime,net:p.overtime,tax:0}],net:p.gross,total:p.net,notes:[`Gross pay: ${p.gross/100}. Training withholding: ${p.withholding/100}. Post-tax deductions: ${p.deductions/100}. Net pay: ${p.net/100}.`,`Employer super: ${p.super/100} (${p.superRateBps/100}% of OTE ${p.ote/100}), additional to gross pay.`,'This is a fictional training payslip. No real tax file number, bank account or employee record.'],journalIds:[pj.id],metadata:{...p}});
  if(m===12){exercise('EX-PAYROLL','Prepare and post the payroll journal','Payroll','Reconcile the employee register to the payslips. Post gross wages, withholding, employee deductions, net wages payable and employer super.',[pj],[`PAY-${month}`],'Gross wages and employer super are expenses. Withholding and employee deductions are liabilities taken from gross pay; they are not extra expenses. Employer super is additional to gross wages.',['Check gross − withholding − deductions = net pay.','Debit wages for gross pay, not net pay. Credit separate payable accounts.'],'Intermediate',[],['Net pay does not include employer super.','Use 12% of OTE in December, and exclude the separately identified overtime in this case.']);exercise('EX-PAYMENT','Record the payroll bank payment','Payroll','The bank shows a bulk net wage payment on 26 December. Clear the payroll liability using the payroll register.',[payCash],[`PAY-${month}`],'Paying employees settles wages payable; it does not create a second wages expense.',['The debit belongs to net wages payable.'],'Foundation',['EX-PAYROLL']);}
  const dep=sum(assets.filter(a=>a.availableDate<=end).map(monthlyDepreciation));
  const dj=push(journal(`J-DEP-${m}`,end,`Equipment depreciation — ${month}`,[dr('6500',dep),cr('1510',dep)],'Assets','FA-REGISTER'));
  if(m===12)exercise('EX-DEPRECIATION','Update the fixed asset register','Assets','Calculate straight-line depreciation for each asset, including the new stacker available from 16 December. Apply the stated full-month convention.',[dj],['FA-REGISTER','PI-CAPEX-12'],'Depreciate cost less residual value over useful life from availability for use. The teaching policy takes a full month in the first month. This is a case convention, not a universal reporting rule.',['Monthly depreciation = (cost − residual value) ÷ useful life in months.','Include the new stacker for one month.'],'Intermediate',['EX-CAPEX']);
  const amort=push(journal(`J-INS-${m}`,end,'Monthly insurance release',[dr('6200',cents(1000)),cr('1300',cents(1000))],'Prepayments','INS-2025'));
  if(m===12)exercise('EX-INSURANCE','Release the final month of insurance','Prepayments','The annual insurance premium covers 1 January to 31 December. Eleven monthly releases have been posted. Record December.',[amort],['INS-2025'],'Allocate the premium to the twelve covered months. The prepaid balance should be zero at 31 December. GST was handled when the invoice was recorded.',['Do not apply GST again on the month-end release.'],'Foundation');
  if(m>=7){const sj=push(journal(`J-SUB-${m}`,end,'Monthly subscription release',[dr('6210',cents(500)),cr('1310',cents(500))],'Prepayments','SUB-2025'));if(m===12)exercise('EX-SUBSCRIPTION','Reconcile the software prepayment','Prepayments','A $6,000 annual subscription covers 1 July 2025 to 30 June 2026. Release December and confirm the remaining six months.',[sj],['SUB-2025'],'Six of twelve months have been consumed by year-end. Expense $500 for December and retain $3,000 as the closing prepayment.',['The remaining balance is a future service right, not an unrecorded expense.'],'Foundation');}
  const loanOpening=cents(80000-(m-1)*2000),interest=pct(loanOpening,50);
  push(journal(`J-LOAN-${m}`,`${month}-28`,'Loan instalment: principal and interest',[dr('2510',cents(2000)),dr('6410',interest),cr('1000',cents(2000)+interest)],'Financing','LOAN-AGREEMENT','financing'));
  push(journal(`J-WARRANTY-PAY-${m}`,`${month}-20`,'Warranty claim settled',[dr('2400',cents(400)),cr('1000',cents(400))],'Provisions','WARRANTY-REPORT','operating'));
  const fee=cents(45+int(0,5)*5),fj=push(journal(`J-BANK-FEE-${m}`,end,'Account maintenance fee',[dr('6400',fee),cr('1000',fee)],'Bank','BANK-2025-12','operating'));
  if(m===12)exercise('EX-BANK-FEE','Record a bank-only charge','Bank','The statement includes a maintenance fee that is absent from the cash book. The fee is input taxed in this case, with no GST credit.',[fj],['BANK-2025-12'],'Record the bank statement charge in the cash book before completing the reconciliation.',['This is a book adjustment, not a timing difference.'],'Foundation');
  if(m===3||m===6||m===9)push(journal(`J-TAX-INST-${m}`,`${month}-21`,'Income tax instalment paid',[dr('2600',cents(3000)),cr('1000',cents(3000))],'Tax','TAX-MEMO','operating'));
 }
 // Annual contracts are paid directly; their monthly amortisation is generated above.
 for(const [id,date,amount,account,party,title] of [['INS-2025','2025-01-02',12000,'1300','Anchor Insurance','Annual insurance policy'],['SUB-2025','2025-07-01',6000,'1310','Cloudstack Software','Annual software subscription']] as const){const net=cents(amount),tax=pct(net,1000);const j=push(journal(`J-${id}`,date,title,[dr(account,net),dr('1400',tax),cr('1000',net+tax)],'Prepayments',id,'operating'));doc({id,kind:'Contract',date,party,title,lines:[{description:title,quantity:1,unitPrice:net,net,tax}],net,tax,total:net+tax,notes:[id==='INS-2025'?'Coverage: 1 January–31 December 2025. Net premium $12,000, GST $1,200.':'Coverage: 1 July 2025–30 June 2026. Net subscription $6,000, GST $600.','Paid on invoice date. Allocate the net cost evenly over 12 months.'],journalIds:[j.id]});}
 push(journal('J-OPEN-TAX-PAY','2025-01-20','Prior-year income tax balance paid',[dr('2600',cents(4000)),cr('1000',cents(4000))],'Tax','TAX-MEMO','operating'));
 // Every settlement carries its invoice ID and contact through to the subledger.
 for(let i=0;i<payments.length;i++){const p=payments[i];push(journal(`J-SET-${String(i+1).padStart(4,'0')}`,p.date,p.description,p.side==='customer'?[dr('1000',p.amount),cr('1100',p.amount,p.contact)]:[dr('2000',p.amount,p.contact),cr('1000',p.amount)],p.side==='customer'?'Receipts':'Payments',p.sourceId,p.cashClass??'operating'));}
 const capex=assets[3],ctax=pct(capex.cost,1000),cj=push(journal('J-CAPEX','2025-12-12','Electric pallet stacker acquired',[dr('1500',capex.cost),dr('1400',ctax),cr('2000',capex.cost+ctax,'S8')],'Assets','PI-CAPEX-12','investing'));
 const cp=push(journal('J-CAPEX-PAY','2025-12-19','Pallet stacker supplier paid',[dr('2000',capex.cost+ctax,'S8'),cr('1000',capex.cost+ctax)],'Assets','PI-CAPEX-12','investing'));
 doc({id:'PI-CAPEX-12',kind:'Supplier invoice',date:'2025-12-12',dueDate:'2025-12-26',party:'Workshop Equipment Co.',title:'Electric pallet stacker acquisition',lines:[{description:capex.name,quantity:1,unitPrice:capex.cost,net:capex.cost,tax:ctax,account:'1500'}],net:capex.cost,tax:ctax,total:capex.cost+ctax,notes:['The asset is ready for use on 16 December. Residual value $2,000; useful life 60 months.','Paid on 19 December. This payment is already in the cash book; the invoice is unprocessed.'],journalIds:[cj.id,cp.id],metadata:{contactId:'S8'}});
 exercise('EX-CAPEX','Capitalise new equipment','Assets','An asset purchase was left in the unprocessed inbox. Record the acquisition and recoverable GST. Its payment is already recorded.',[cj],['PI-CAPEX-12'],'A productive asset provides benefits over more than one period. Capitalise its net purchase cost, then depreciate when available for use.',['The invoice goes to equipment cost, not repairs.','The supplier payment already exists; do not post a second payment.'],'Intermediate');
 doc({id:'FA-REGISTER',kind:'Memo',date:'2025-12-31',party:'Finance team',title:'Fixed asset register and depreciation policy',notes:assets.map(a=>`${a.id} ${a.name}: cost ${a.cost/100}; residual ${a.residual/100}; life ${a.lifeMonths} months; available ${a.availableDate}; opening accumulated depreciation ${a.openingAccumulated/100}.`).concat(['Straight-line method; charge a full month from the month available for use. Round each asset monthly to the nearest cent. No disposals or impairment in this case.']),journalIds:all.filter(j=>j.id.startsWith('J-DEP')).map(j=>j.id)});
 // IFRS 16-style equipment lease, exempt from GST for this isolated teaching case.
 const leaseRate=0.005,leasePayment=cents(2000),leaseMonths=36,leasePV=Math.round(leasePayment*(1-Math.pow(1+leaseRate,-leaseMonths))/leaseRate);
 const lj=push(journal('J-LEASE-START','2025-07-01','Recognise equipment lease at present value',[dr('1520',leasePV),cr('2520',leasePV)],'Leases','LEASE-2025','financing'));
 let leaseBalance=leasePV;let decemberLease:Journal[]=[];
 for(let m=7;m<=12;m++){const interest=Math.round(leaseBalance*leaseRate),principal=leasePayment-interest,month=isoMonth(m);const j=push(journal(`J-LEASE-PAY-${m}`,monthEnd(month),'Equipment lease payment',[dr('2520',principal),dr('6410',interest),cr('1000',leasePayment)],'Leases','LEASE-2025','financing'));leaseBalance-=principal;const dep=Math.round(leasePV/36);const d=push(journal(`J-LEASE-DEP-${m}`,monthEnd(month),'Right-of-use asset depreciation',[dr('6510',dep),cr('1530',dep)],'Leases','LEASE-2025'));if(m===12)decemberLease=[j,d];}
 let nextBalance=leaseBalance,nextPrincipal=0;for(let i=0;i<12;i++){const interest=Math.round(nextBalance*leaseRate),principal=leasePayment-interest;nextBalance-=principal;nextPrincipal+=principal;}
 const lr=push(journal('J-LEASE-RECLASS','2025-12-31','Current portion of lease liability',[dr('2520',nextPrincipal),cr('2530',nextPrincipal)],'Leases','LEASE-2025'));decemberLease.push(lr);
 doc({id:'LEASE-2025',kind:'Contract',date:'2025-07-01',party:'Example Equipment Leasing',title:'36-month equipment lease',notes:[`Commencement: 1 July 2025. 36 end-of-month payments of $2,000. Monthly discount rate: 0.5%. Initial present value: ${leasePV/100}.`,`No initial direct costs, incentives, residual guarantee, purchase option or GST in this isolated case. ROU asset equals initial liability. Depreciate over 36 months.`,`The first five monthly instalments and depreciation charges are already recorded. December opening liability: ${(leaseBalance+(leasePayment-Math.round((leaseBalance+leasePayment)/(1+leaseRate)*leaseRate)))/100} (use the amortisation schedule for exact amounts).`,'Classify principal due within the next twelve months as current. Interest paid is a financing cash flow under the case policy.'],journalIds:[lj.id,...decemberLease.map(j=>j.id)],metadata:{leasePV,leasePayment,leaseRate,leaseMonths}});
 exercise('EX-LEASE','Roll forward the equipment lease','Leases','Prepare December lease interest, principal, ROU depreciation and the next twelve months current-liability split.',decemberLease,['LEASE-2025'],'Accrete interest using the monthly discount rate on the opening liability. Allocate the cash payment between interest and principal. Depreciate the ROU asset separately. Current principal excludes unaccrued future interest.',['Use the schedule in the Leases workspace.','A lease payment is not entirely a rent expense.'],'Advanced',[],['Do not include the July non-cash commencement in cash outflows.']);
 // Month-end evidence and adjustments.
 const deposit=push(journal('J-DEPOSIT','2025-12-06','Advance received for installation contract',[dr('1000',cents(16500)),cr('2300',cents(15000)),cr('2200',cents(1500))],'Revenue','CONTRACT-DEC','operating'));
 const release=push(journal('J-REV-RELEASE','2025-12-31','Recognise accepted installation milestone',[dr('2300',cents(6000)),cr('4010',cents(6000))],'Revenue','CONTRACT-DEC'));
 doc({id:'CONTRACT-DEC',kind:'Contract',date:'2025-12-06',party:'Beacon Interiors',title:'Installation contract: customer advance and milestone',net:cents(15000),tax:cents(1500),total:cents(16500),notes:['A $16,500 cash advance was received on 6 December, including $1,500 GST already accounted for. The advance is recorded as a contract liability.','The contract contains distinct accepted installation stages. By 31 December, an accepted stage worth $6,000 excluding GST is complete. The balance is due to be performed in January.','Release only the accepted milestone amount. Do not recognise the full advance as revenue.'],journalIds:[deposit.id,release.id]});
 exercise('EX-DEFERRED','Recognise earned customer advances','Revenue','The customer paid in advance. Determine the revenue earned by year-end from the accepted milestone and release the appropriate contract liability.',[release],['CONTRACT-DEC'],'Revenue follows satisfaction of the performance obligation. The remaining $9,000 relates to future work and remains deferred. GST was recognised on the advance in this case.',['The bank receipt is already posted.','A $6,000 accepted stage is complete.'],'Intermediate');
 const unbilledAmount=cents(4200+int(0,6)*150),uj=push(journal('J-UNBILLED','2025-12-31','Accrue completed but unbilled installation',[dr('1320',unbilledAmount),cr('4010',unbilledAmount)],'Revenue','UNBILLED-MEMO'));
 doc({id:'UNBILLED-MEMO',kind:'Memo',date:'2025-12-31',party:'Operations manager',title:'Completed unbilled work',net:unbilledAmount,total:unbilledAmount,notes:[`A separate completed installation worth ${unbilledAmount/100} excluding GST was accepted on 30 December. Billing occurs on 5 January 2026.`,`Recognise accrued revenue at year-end. In this case the GST attribution trigger occurs with the January invoice, so do not recognise GST in December. Reverse the accrual when billing is posted.`],journalIds:[uj.id]});
 exercise('EX-UNBILLED','Capture unbilled revenue at cut-off','Revenue','Accepted work has not yet been invoiced. Record the year-end accrual using the operations memo.',[uj],['UNBILLED-MEMO'],'The work is complete and accepted before year-end. Recognise a receivable for unbilled revenue; the future invoice must clear that accrual to avoid double counting.',['Use accrued revenue, rather than trade receivables for this memo.'],'Intermediate');
 const accrual=push(journal('J-ACCRUAL','2025-12-31','Accrue December utilities and professional fees',[dr('6110',cents(940)),dr('6240',cents(3500)),cr('2100',cents(4440))],'Accruals','ACCRUAL-MEMO'));
 doc({id:'ACCRUAL-MEMO',kind:'Memo',date:'2025-12-31',party:'Finance team',title:'Unrecorded December expenses',net:cents(4440),total:cents(4440),notes:['The January invoice review identified December electricity of $940 excluding GST and December accounting work of $3,500 excluding GST.','Both services were received before year-end. No tax invoice was held at year-end; the case records input GST when the invoices arrive.','Prepare an accrual of $4,440. Clear or reverse it when the January invoices are recorded.'],journalIds:[accrual.id]});
 exercise('EX-ACCRUAL','Accrue missing period expenses','Accruals','Review January invoices for services already received in December. Accrue the December expense without prematurely claiming input GST.',[accrual],['ACCRUAL-MEMO'],'Expense recognition follows service consumption. Use the appropriate expense lines and a single accrual liability. Avoid creating a supplier invoice before it is received.',['Two expense accounts, one accrued-expense liability.'],'Intermediate',[],['An invoice date in January does not automatically make the cost a January expense.']);
 const countLoss=-inventory[0].countVariance*inventory[0].cost,stockj=push(journal('J-STOCK-COUNT','2025-12-31','Record physical inventory shortage',[dr('5010',countLoss),cr('1200',countLoss)],'Inventory','COUNT-2025'));
 const last=inventory[4],qty=last.openingQty+sum(last.bought)-sum(last.sold)+last.countVariance,nrvLoss=qty*(last.cost-last.nrv),nrvj=push(journal('J-STOCK-NRV','2025-12-31','Write LED work lights down to NRV',[dr('5020',nrvLoss),cr('1210',nrvLoss)],'Inventory','COUNT-2025'));
 doc({id:'COUNT-2025',kind:'Stock count',date:'2025-12-31',party:'Warehouse supervisor',title:'Signed year-end inventory count and NRV review',lines:inventory.map(item=>{const q=item.openingQty+sum(item.bought)-sum(item.sold)+item.countVariance;return {description:`${item.id} ${item.name} — actual count`,quantity:q,unitPrice:item.cost,net:q*item.cost,tax:0};}),net:sum(inventory.map(i=>(i.openingQty+sum(i.bought)-sum(i.sold)+i.countVariance)*i.cost)),total:sum(inventory.map(i=>(i.openingQty+sum(i.bought)-sum(i.sold)+i.countVariance)*i.cost)),notes:['The door closer count is 7 units below book quantity. All other physical counts agree with the perpetual records.','LED work lights have an estimated selling price less completion and selling costs of $42 per unit. Historical cost is $55 per unit. All other products have NRV above cost.','Record physical shrinkage separately from the valuation allowance.'],journalIds:[stockj.id,nrvj.id]});
 exercise('EX-STOCK','Reconcile the physical stock count','Inventory','Compare perpetual quantities to the signed physical count. Investigate and record the shortage at its carrying cost.',[stockj],['COUNT-2025'],'A physical shortage reduces inventory at cost and is an expense. The missing units are not a sales transaction and do not generate revenue or GST.',['Seven units of P01 are missing; use cost, not selling price.'],'Intermediate');
 exercise('EX-NRV','Measure inventory at lower of cost and NRV','Inventory','The year-end review indicates that one product cannot recover its carrying cost. Calculate and record a separate NRV allowance.',[nrvj],['COUNT-2025'],'Compare unit cost to estimated net realisable value for each item. Apply the shortfall to the actual quantity held.',['Use the P05 physical count × ($55 − $42).'],'Intermediate',['EX-STOCK']);
 const warrantyTarget=cents(5400+int(0,6)*200),warrantyCurrent=cents(1200),wj=push(journal('J-WARRANTY-ADJ','2025-12-31','Remeasure product warranty provision',[dr('6700',warrantyTarget-warrantyCurrent),cr('2400',warrantyTarget-warrantyCurrent)],'Provisions','WARRANTY-REPORT'));
 doc({id:'WARRANTY-REPORT',kind:'Memo',date:'2025-12-31',party:'Quality manager',title:'Warranty claims and expected future outflows',net:warrantyTarget,total:warrantyTarget,notes:[`Opening provision was $6,000. Claims settled were $400 in each of 12 months, already debited to the provision. A portfolio assessment of products sold before year-end estimates remaining expected claim costs of ${warrantyTarget/100}.`,'The products carry an assurance warranty. A present obligation exists from past sales, an outflow for the portfolio is probable, and the estimate is reliable.','The estimate is the required closing provision, not an additional expense. No reimbursement asset or discounting is needed for this short-term case.'],journalIds:[wj.id]});
 exercise('EX-WARRANTY','Roll forward the warranty provision','Provisions','Reconcile opening provision, claims used and the required closing estimate. Record only the adjustment needed to reach that estimate.',[wj],['WARRANTY-REPORT'],'Required closing provision less the current ledger provision is the adjustment. Cash claims use the provision; remeasurement goes to expense.',['Opening $6,000 less $4,800 claims leaves $1,200 before remeasurement.'],'Intermediate',[],['Do not expense the full closing estimate on top of the existing provision.']);
 const legalAmount=cents(18000+int(0,4)*1000),legalj=push(journal('J-LEGAL','2025-12-31','Recognise probable legal claim',[dr('6710',legalAmount),cr('2410',legalAmount)],'Provisions','LEGAL-LETTER'));
 doc({id:'LEGAL-LETTER',kind:'Memo',date:'2025-12-29',party:'Example Legal Partners',title:'Legal claims assessment',net:legalAmount,total:legalAmount,notes:[`A customer claim arises from a pre-year-end breach. Counsel considers a loss 70% likely. The single most likely settlement is ${legalAmount/100}; other outcomes do not change the best estimate. Payment is expected within six months.`,`A separate threatened claim has only a 20% probability of an outflow of $40,000. It is possible, not remote, with no present payable. Disclose it as a contingent liability; do not recognise a provision for it.`,'Future refurbishment planned by management costs $25,000. No contract or constructive obligation exists. No provision or contingent liability is recognised solely for this future plan.'],journalIds:[legalj.id]});
 exercise('EX-LEGAL','Distinguish provisions and contingencies','Provisions','Assess three items in the legal letter. Recognise only the qualifying present obligation, and document the contingent liability separately in the AFS notes.',[legalj],['LEGAL-LETTER'],'A present obligation from a past event, probable outflow and reliable estimate support a provision. A merely possible obligation is disclosed unless remote. Future operating plans alone do not create a present obligation.',['For this single obligation, the best estimate is the stated settlement; do not mechanically multiply it by 70%.'],'Advanced',[],['A budget for future expenditure is not automatically a provision.']);
 const leaveTarget=sum(employees.map(e=>Math.round(e.annualLeaveHours*e.hourlyRate))),leaveDelta=leaveTarget-cents(14000),lvj=push(journal('J-LEAVE','2025-12-31','Remeasure accrued annual leave',[dr('6020',leaveDelta),cr('2150',leaveDelta)],'Payroll','LEAVE-REPORT'));
 doc({id:'LEAVE-REPORT',kind:'Memo',date:'2025-12-31',party:'People team',title:'Annual leave entitlement valuation',lines:employees.map(e=>({description:`${e.name}: unused leave hours × ordinary hourly rate`,quantity:e.annualLeaveHours,unitPrice:e.hourlyRate,net:Math.round(e.annualLeaveHours*e.hourlyRate),tax:0})),net:leaveTarget,total:leaveTarget,notes:['The supplied hours are the final unused entitlements after all leave taken. Multiply by current ordinary hourly rates. The opening provision was $14,000 and no separate provision entries were posted during the year.','This exercise excludes on-costs and discounting. A real employee benefit valuation must assess both. Do not add payroll withholding or GST to the provision.'],journalIds:[lvj.id]});
 exercise('EX-LEAVE','Value the annual leave provision','Payroll','Value the final unused leave entitlements from the employee report and adjust the provision to the required closing amount.',[lvj],['LEAVE-REPORT'],'Closing unused entitlement × current pay rate gives the case liability. Only the movement from the existing provision is charged to expense.',['Check hours, rates and the opening liability separately.'],'Intermediate');
 const loanj=push(journal('J-LOAN-RECLASS','2025-12-31','Classify next twelve months loan principal',[dr('2500',cents(24000)),cr('2510',cents(24000))],'Financing','LOAN-AGREEMENT'));
 doc({id:'LOAN-AGREEMENT',kind:'Contract',date:'2025-01-01',party:'Practice Bank',title:'Term loan agreement and repayment terms',notes:['Opening loan: $80,000, split $24,000 current / $56,000 non-current. Principal payments: $2,000 monthly. Interest: 0.5% of opening monthly principal, paid with each instalment.','All twelve instalments are already recorded. No covenant breach or callable-on-demand term exists. The next twelve months principal is $24,000.','Reclassify principal without changing total debt or cash. Interest paid is financing under the selected case policy.'],journalIds:[loanj.id]});
 exercise('EX-LOAN','Reconcile and classify the bank loan','Financing','Agree opening debt to repayments and the lender terms. Reclassify the next twelve months principal to current borrowings.',[loanj],['LOAN-AGREEMENT'],'The current/non-current split changes presentation, not total debt or profit. Exclude future interest not yet accrued.',['After $24,000 repayments, total loan principal is $56,000.'],'Intermediate');
 // Specific post-year-end clearance: a customer receipt deposited on 31 December.
 const transit=cents(1800),tj=push(journal('J-TRANSIT','2025-12-31','Customer remittance deposited; clears 2 January',[dr('1000',transit),cr('1100',transit,'C1')],'Receipts','REMIT-DEC31','operating'));
 doc({id:'REMIT-DEC31',kind:'Memo',date:'2025-12-31',party:'Northline Works',title:'31 December deposit in transit',net:transit,total:transit,notes:['A $1,800 customer remittance was deposited before cut-off and is recorded in the cash book. The bank credits it on 2 January.','Allocate this receipt as an on-account customer credit until remittance details are available. It is a valid deposit in transit. Do not post it again.'],journalIds:[tj.id],metadata:{contactId:'C1'}});
 // ECL from full receivables subledger, using explicit aging assumptions.
 const preECL=balances([opening,...all]),arDocs=docs.filter(d=>d.kind==='Sales invoice');
 const aging=[0,0,0,0,0];
 for(const d of arDocs){let amount=d.total;const settlements=all.filter(j=>j.sourceId===d.id&&j.lines.some(l=>l.account==='1100'&&l.credit));amount-=sum(settlements.flatMap(j=>j.lines.filter(l=>l.account==='1100').map(l=>l.credit-l.debit)));if(amount<=0)continue;const days=Math.floor((Date.parse('2025-12-31')-Date.parse(d.dueDate??d.date))/86400000);const bucket=days<=0?0:days<=30?1:days<=60?2:days<=90?3:4;aging[bucket]+=amount;}
 const eclRates=[100,300,1000,3500,8000],eclTarget=sum(aging.map((amount,i)=>pct(amount,eclRates[i]))),eclDelta=eclTarget+preECL['1110'];
 const ej=push(journal('J-ECL','2025-12-31','Update expected credit loss allowance',[dr('6600',eclDelta),cr('1110',eclDelta)],'Receivables','ECL-MEMO'));
 doc({id:'ECL-MEMO',kind:'Memo',date:'2025-12-31',party:'Credit controller',title:'Receivables loss-rate matrix',net:eclTarget,total:eclTarget,notes:['Apply the following lifetime expected loss assumptions to open invoice balances, based on days past due: not yet due 1%; 1–30 days 3%; 31–60 days 10%; 61–90 days 35%; over 90 days 80%.','Round the allowance for each aging bucket to cents. The $1,800 on-account customer credit is shown separately and does not reduce the loss-rate matrix for unidentified invoices.','These are supplied forward-looking case assumptions. They are not standard-mandated rates. Opening ECL allowance is $3,000.'],journalIds:[ej.id],metadata:{current:aging[0],days1to30:aging[1],days31to60:aging[2],days61to90:aging[3],over90:aging[4],eclTarget}});
 exercise('EX-ECL','Prepare the receivables impairment allowance','Receivables','Age unpaid invoices by due date. Apply the supplied loss-rate matrix and adjust the existing allowance to the required closing amount.',[ej],['ECL-MEMO','SI-2024-118'],'An expected credit loss allowance is a contra asset. The expense is the movement from the existing allowance, not the entire receivables balance. The matrix must use invoice balances after receipts.',['Use the aged receivables workspace and the stated bucket loss rates.','Do not write off the customer invoice when merely recognising an allowance.'],'Advanced',['EX-SALE']);
 // GST control transfers are generated after all operational transactions.
 for(let m=1;m<=12;m++){const month=isoMonth(m),end=monthEnd(month),b=balances(all.filter(j=>j.date.startsWith(month))),input=b['1400']??0,output=-(b['2200']??0),net=output-input;const lines=[dr('2200',output),cr('1400',input),net>=0?cr('2210',net):dr('2210',-net)];const gj=push(journal(`J-GST-${m}`,end,`Transfer GST controls — ${month}`,lines,'Tax',`GST-${month}`));if(m<12&&net)push(journal(`J-GST-PAY-${m}`,`${isoMonth(m+1)}-21`,net>=0?'Monthly GST settlement paid':'Monthly GST refund received',net>=0?[dr('2210',net),cr('1000',net)]:[dr('1000',-net),cr('2210',-net)],'Tax',`GST-${month}`,'operating'));if(m===12){doc({id:`GST-${month}`,kind:'Memo',date:end,party:'Finance team',title:'Monthly GST reconciliation',notes:['The fictional company reports monthly. Taxable supplies use 10% GST; input tax credits are taken only on supported taxable purchases. No GST is charged on wages, interest, depreciation or provision entries.','Reconcile December output and input control balances, transfer them to the settlement account, and leave the December net payable unpaid at year-end.','This worksheet teaches ledger-to-return reconciliation. It does not submit a BAS or validate actual GST attribution eligibility.'],journalIds:[gj.id]});exercise('EX-GST','Reconcile GST and transfer the net payable','Tax','Complete all taxable invoice entries, reconcile input and output controls, then transfer the December net amount to GST settlement payable.',[gj],[`GST-${month}`],'Debit output GST and credit input GST to clear the period controls. Credit the settlement liability for the net payable. Cash is paid in the following month.',['Finish the missing sale, purchase and capital invoice first.'],'Advanced',['EX-SALE','EX-PURCHASE','EX-CAPEX']);}}
 const bt=balances([opening,...all]),profitBeforeTax=-sum(Object.entries(bt).filter(([a])=>Number(a)>=4000).map(([,v])=>v));
 const temporaryAddbacks=eclDelta+(warrantyTarget-cents(6000))+legalAmount+leaveDelta+nrvLoss,taxDepDifference=cents(6000),taxable=profitBeforeTax+temporaryAddbacks-taxDepDifference,taxExpense=pct(Math.max(0,taxable),2500);
 const taxj=push(journal('J-CURRENT-TAX','2025-12-31','Recognise current income tax expense',[dr('6800',taxExpense),cr('2600',taxExpense)],'Tax','TAX-MEMO'));
 const dtaTarget=pct(eclTarget+warrantyTarget+legalAmount+leaveTarget+nrvLoss,2500),dtlTarget=pct(cents(10000),2500),dtaMove=dtaTarget-cents(2000),dtlMove=dtlTarget-cents(1000),dtj=push(journal('J-DEFERRED-TAX','2025-12-31','Recognise movements in deferred tax',[dr('1600',dtaMove),cr('6810',dtaMove),dr('6810',dtlMove),cr('2610',dtlMove)],'Tax','TAX-MEMO'));
 doc({id:'TAX-MEMO',kind:'Memo',date:'2025-12-31',party:'Tax adviser — case assumptions',title:'Current and deferred tax training bridge',net:taxExpense,total:taxExpense,notes:[`Assume a 25% tax rate and sufficient probable future taxable profit to support the deferred tax asset. These are exercise inputs, not a tax eligibility conclusion.`,`Taxable profit: accounting profit before tax + annual ECL allowance movement + warranty closing less opening $6,000 + legal provision movement + leave provision movement + NRV allowance movement − additional tax depreciation of $6,000. No permanent differences in this case.`,`Year-end deductible temporary differences: full ECL allowance, warranty provision, legal provision, leave provision and NRV allowance. Tax base of each related liability/allowance is zero under the supplied assumptions. DTA opening balance $2,000.`,`Equipment taxable temporary difference at year-end: $10,000. DTL opening balance $1,000. The case includes an opening recognition catch-up in the deferred-tax movement, so the total tax expense need not equal exactly 25% of accounting profit.`,`Opening current tax payable $4,000 was paid in January. Three $3,000 current-year instalments were paid. Credit current tax payable for the current-year tax expense, without expensing the cash payments again.`],journalIds:[taxj.id,dtj.id],metadata:{profitBeforeTax,temporaryAddbacks,taxDepDifference,taxable,taxExpense,dtaTarget,dtlTarget}});
 exercise('EX-TAX','Prepare the current income tax computation','Tax','Use the supplied book-to-tax bridge after completing the operating adjustments. Record current tax expense and reconcile the instalments.',[taxj],['TAX-MEMO'],'Start with accounting profit before tax, adjust for the supplied temporary differences and additional tax depreciation, then apply the case rate. Instalments reduce the payable and do not reduce tax expense.',['The tax bridge shows which movements are added back.','Complete all profit-affecting adjustments before attempting this task.'],'Advanced',['EX-ECL','EX-WARRANTY','EX-LEGAL','EX-LEAVE','EX-NRV','EX-DEPRECIATION','EX-LEASE','EX-ACCRUAL','EX-UNBILLED','EX-DEFERRED','EX-INSURANCE','EX-SUBSCRIPTION','EX-PAYROLL','EX-STOCK','EX-BANK-FEE']);
 exercise('EX-DEFERRED-TAX','Calculate deferred tax balances and movements','Tax','Calculate closing deferred tax assets and liabilities under the supplied tax-base assumptions. Recognise the movement from opening balances.',[dtj],['TAX-MEMO'],'Deferred tax reflects temporary differences, subject to recognition criteria. Multiply the closing temporary difference by the applicable tax rate, then post the movement from the opening deferred tax balance.',['A DTA increase is normally a tax credit; a DTL increase is normally a tax expense.','Assess the probable future taxable profit assumption in your workpaper.'],'Advanced',['EX-TAX']);
 // Statement is independent of the learner cash book, with one genuine timing difference.
 const bankJournals=all.filter(j=>j.id!=='J-TRANSIT'&&j.lines.some(l=>l.account==='1000')).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
 let running=cents(210000);const bank=bankJournals.map((j,i)=>{const amount=sum(j.lines.filter(l=>l.account==='1000').map(l=>l.debit-l.credit));running+=amount;return {id:`BT-${String(i+1).padStart(4,'0')}`,date:j.date,description:j.description,reference:j.sourceId??j.id,amount,balance:running,journalId:j.id};});
 for(let m=1;m<=12;m++){const month=isoMonth(m),rows=bank.filter(b=>b.date.startsWith(month)),before=bank.filter(b=>b.date<`${month}-01`).at(-1)?.balance??cents(210000),closing=rows.at(-1)?.balance??before;doc({id:`BANK-${month}`,kind:'Bank statement',date:monthEnd(month),party:'Practice Bank',title:`Operating account statement — ${month}`,net:sum(rows.map(r=>r.amount)),total:closing,notes:[`Fictional account: TRAINING-001. Opening statement balance: ${before/100}. Closing balance: ${closing/100}.`,`Statement movements are generated from the independent source scenario. They do not change when you post journals.`,`December has a $1,800 deposit in transit clearing on 2 January. Record missing cash-book transactions before assessing the remaining difference.`],journalIds:rows.map(r=>r.journalId!),metadata:{opening:before,closing,transactionCount:rows.length}});}
 // Independent counterparty statements are generated from the complete source history.
 for(const contact of contacts){
  const isCustomer=contact.kind==='customer',code=isCustomer?'1100':'2000',sign=isCustomer?1:-1;
  const movements=[opening,...all].flatMap(j=>j.lines.filter(l=>l.account===code&&l.contact===contact.id).map(l=>({j,amount:(l.debit-l.credit)*sign})));
  const contactInvoices=docs.filter(d=>d.party===contact.name&&d.kind===(isCustomer?'Sales invoice':'Supplier invoice'));
  const statementLines=contactInvoices.map(d=>{const amount=sum(movements.filter(m=>m.j.sourceId===d.id||d.id==='SI-2024-118'&&m.j.id==='OPEN-2025').map(m=>m.amount));return {description:`${d.id} | Invoice ${d.date} | Due ${d.dueDate??d.date}`,quantity:1,unitPrice:amount,net:amount,tax:0};}).filter(l=>l.net!==0);
  const total=sum(movements.map(m=>m.amount)),onAccount=total-sum(statementLines.map(l=>l.net));if(onAccount)statementLines.push({description:'Unapplied / on-account movements',quantity:1,unitPrice:onAccount,net:onAccount,tax:0});
  doc({id:`STMT-${contact.id}-2025-12`,kind:isCustomer?'Customer statement':'Supplier statement',date:'2025-12-31',party:contact.name,title:`${isCustomer?'Customer':'Supplier'} statement - ${contact.name}`,lines:statementLines,net:total,total,notes:['Independent source statement as at 31 December 2025. This statement reflects the complete source transactions, including invoices you may not yet have recorded.','Reconcile this external balance to your ledger and explain missing invoices, unapplied receipts, payments and other differences. Amounts include any GST previously charged; do not post tax again from this statement.'],journalIds:[],metadata:{contactId:contact.id,onAccount}});
 }
 all.sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
 const missing=new Set(exercises.flatMap(e=>e.expected.map(j=>j.id))),baseJournals=all.filter(j=>!missing.has(j.id));
 const budget=Array.from({length:12},(_,i)=>({month:isoMonth(i+1),revenue:cents(103000+(i>8?8000:0)),cogs:cents(41500+(i>8?3500:0)),opex:cents(45500)}));
 return {seed,name:'Harbour & Co. Supply',currency:'AUD',year:2025,period:'2025-12',contacts,documents:docs,opening,baseJournals,solutionJournals:all,exercises,bank,employees,payroll,assets,inventory,budget};
}
