import type {PracticeCompany,PracticeState,Journal} from './types';
import {monthlyDepreciation} from './generator';
import {accountBalances,journalsFor,subledger,profitAndLoss} from './engine';
import {sum,pct,monthEnd} from './money';
export function assetSchedule(company:PracticeCompany,to='2025-12-31'){
 return company.assets.filter(a=>a.availableDate<=to).map(a=>{const [y,m]=a.availableDate.split('-').map(Number),[ey,em]=to.split('-').map(Number),firstYear=Math.max(2025,y),firstMonth=y<2025?1:m,months=Math.max(0,(ey-firstYear)*12+em-firstMonth+1),monthly=monthlyDepreciation(a),depreciation=Math.min(a.cost-a.residual-a.openingAccumulated,monthly*months),accumulated=a.openingAccumulated+depreciation;return {...a,monthly,months,depreciation,accumulated,carryingValue:a.cost-accumulated};});
}
export function leaseSchedule(company:PracticeCompany){const d=company.documents.find(d=>d.id==='LEASE-2025');if(!d)return {pv:0,payment:0,rate:0,months:0,rows:[] as {number:number;date:string;opening:number;interest:number;payment:number;principal:number;closing:number;depreciation:number}[],december:{number:6,date:'2025-12-31',opening:0,interest:0,payment:0,principal:0,closing:0,depreciation:0},currentPortion:0,noncurrent:0};const pv=Number(d.metadata?.leasePV),payment=Number(d.metadata?.leasePayment),rate=Number(d.metadata?.leaseRate),months=Number(d.metadata?.leaseMonths);let liability=pv;const rows=Array.from({length:months},(_,i)=>{const date=new Date(Date.UTC(2025,6+i,1)),month=date.toISOString().slice(0,7),opening=liability,interest=Math.round(opening*rate),cash=i===months-1?opening+interest:payment,principal=cash-interest;liability-=principal;return {number:i+1,date:monthEnd(month),opening,interest,payment:cash,principal,closing:liability,depreciation:i===months-1?pv-Math.round(pv/months)*(months-1):Math.round(pv/months)};});return {pv,payment,rate,months,rows,december:rows[5],currentPortion:sum(rows.slice(6,18).map(r=>r.principal)),noncurrent:rows[5].closing-sum(rows.slice(6,18).map(r=>r.principal))};}
export function inventorySchedule(company:PracticeCompany,state:PracticeState,to='2025-12-31'){
 const js=journalsFor(company,state).filter(j=>j.date<=to),active=(id:string,account:string,positive:boolean)=>sum(js.filter(j=>j.sourceId===id).flatMap(j=>j.lines.filter(l=>l.account===account).map(l=>l.debit-l.credit)))*(positive?1:-1)>0;
 return company.inventory.map(item=>{const docs=[...company.documents,...state.customDocuments].filter(d=>d.date<=to&&d.lines.some(l=>l.itemId===item.id)),purchases=sum(docs.filter(d=>d.kind==='Supplier invoice'&&active(d.id,'1200',true)).flatMap(d=>d.lines.filter(l=>l.itemId===item.id).map(l=>l.quantity))),sales=sum(docs.filter(d=>d.kind==='Sales invoice'&&active(d.id,'1200',false)).flatMap(d=>d.lines.filter(l=>l.itemId===item.id).map(l=>l.quantity))),customerReturns=sum(docs.filter(d=>d.kind==='Credit note'&&active(d.id,'1200',true)).flatMap(d=>d.lines.filter(l=>l.itemId===item.id).map(l=>l.quantity))),supplierReturns=sum(docs.filter(d=>d.kind==='Supplier credit note'&&active(d.id,'1200',false)).flatMap(d=>d.lines.filter(l=>l.itemId===item.id).map(l=>l.quantity))),bookQty=item.openingQty+purchases-sales+customerReturns-supplierReturns,months=Number(to.slice(5,7)),physicalQty=item.openingQty+sum(item.bought.slice(0,months))-sum(item.sold.slice(0,months))+(to>='2025-12-31'?item.countVariance:0),variance=physicalQty-bookQty,nrv=to>='2025-12-31'?item.nrv:item.cost,nrvAllowance=Math.max(0,item.cost-nrv)*physicalQty;
 return {...item,nrv,purchases:purchases-supplierReturns,sales:sales-customerReturns,customerReturns,supplierReturns,bookQty,physicalQty,variance,costValue:physicalQty*item.cost,nrvAllowance,netValue:physicalQty*item.cost-nrvAllowance};});
}
export function taxBridge(company:PracticeCompany,state:PracticeState){const js=journalsFor(company,state).filter(j=>j.date<='2025-12-31'),pl=profitAndLoss(js),b=accountBalances(js),o=accountBalances([company.opening]);const differences=[['ECL allowance movement','1110'],['Warranty provision movement','2400'],['Legal claim provision movement','2410'],['Annual leave provision movement','2150'],['Inventory NRV allowance movement','1210']].map(([label,account])=>({label,account,amount:-(b[account]-o[account])}));const additionalDepreciation=600000,taxable=pl.profitBeforeTax+sum(differences.map(d=>d.amount))-additionalDepreciation,expectedTax=pct(Math.max(0,taxable),2500),deductible=-sum(['1110','2400','2410','2150','1210'].map(a=>b[a])),dta=pct(deductible,2500),dtl=pct(1000000,2500);return {pl,b,differences,additionalDepreciation,taxable,expectedTax,deductible,dta,dtl,currentExpense:b['6800'],currentLiability:-b['2600']};}
export const WORKPAPERS=[
 {id:'A-01',title:'Trial balance and lead schedule',area:'Reporting',assertions:'Completeness, accuracy and classification',accounts:['1000','1100','2000'],procedures:['Agree total debits and credits.','Map all accounts to statement lines.','Trace material balances to lead schedules.','Explain unusual debit liabilities or credit assets.'],evidence:['TB-OPEN']},
 {id:'B-01',title:'Bank and cash',area:'Cash',assertions:'Existence, rights and completeness',accounts:['1000','1010'],procedures:['Agree the bank statement closing balance to the reconciliation.','Match receipts and payments to cash-book entries.','Substantiate deposits in transit and outstanding payments with subsequent clearance.','Check that bank-only charges are posted.'],evidence:['BANK-2025-12','REMIT-DEC31']},
 {id:'C-01',title:'Trade receivables and ECL',area:'Receivables',assertions:'Existence, valuation and cut-off',accounts:['1100','1110','1320'],procedures:['Agree aged receivables to the control account.','Review overdue balances and subsequent receipts.','Recalculate the lifetime expected credit loss matrix.','Review unbilled revenue and customer acceptance before year-end.'],evidence:['ECL-MEMO','SI-2024-118','UNBILLED-MEMO']},
 {id:'D-01',title:'Inventory and NRV',area:'Inventory',assertions:'Existence, completeness and valuation',accounts:['1200','1210'],procedures:['Agree perpetual quantities to signed count records.','Investigate shortages and surplus stock.','Test costs to purchase invoices.','Assess lower of cost and NRV at item level.'],evidence:['COUNT-2025']},
 {id:'E-01',title:'Fixed assets and depreciation',area:'Assets',assertions:'Existence, rights, valuation and classification',accounts:['1500','1510'],procedures:['Roll forward cost and accumulated depreciation.','Inspect capital expenditure support and availability dates.','Recalculate useful-life and residual-value assumptions.','Reconcile depreciation expense and closing carrying value.'],evidence:['FA-REGISTER','PI-CAPEX-12']},
 {id:'E-02',title:'Lease accounting',area:'Leases',assertions:'Completeness, valuation and presentation',accounts:['1520','1530','2520','2530'],procedures:['Agree contractual cash flows and discount rate.','Recalculate the present value and effective interest schedule.','Separate ROU depreciation from liability movements.','Agree the current principal portion to the next twelve months.'],evidence:['LEASE-2025']},
 {id:'F-01',title:'Payables and accrued expenses',area:'Payables',assertions:'Completeness, obligations and cut-off',accounts:['2000','2100'],procedures:['Agree supplier balances to control accounts.','Inspect January invoices for pre-year-end services.','Reconcile received goods to supplier invoices.','Document why the liability belongs in December.'],evidence:['ACCRUAL-MEMO','PI-12-2']},
 {id:'G-01',title:'Payroll and employee benefits',area:'Payroll',assertions:'Occurrence, completeness and accuracy',accounts:['6000','6010','2110','2120','2130','2140','2150'],procedures:['Agree gross-to-net pay for each employee.','Recalculate employer super using the dated OTE assumption.','Trace net wages, PAYG and deductions to bank payments.','Value unused leave and reconcile the provision.'],evidence:['PAY-2025-12','LEAVE-REPORT']},
 {id:'H-01',title:'Provisions and contingencies',area:'Provisions',assertions:'Completeness, valuation and disclosure',accounts:['2400','2410'],procedures:['Identify a present obligation from a past event.','Assess likelihood of outflow and reliability of estimate.','Reconcile opening provision, additions and utilisation.','Separate recognised provisions, disclosed contingencies and future plans.'],evidence:['WARRANTY-REPORT','LEGAL-LETTER']},
 {id:'I-01',title:'Revenue and prepayments',area:'Revenue',assertions:'Occurrence, cut-off and classification',accounts:['1300','1310','1320','2300','4000','4010'],procedures:['Test revenue to delivery or acceptance evidence.','Reconcile customer advances to performance obligations.','Accrue accepted unbilled work.','Allocate contracts over the covered periods.'],evidence:['CONTRACT-DEC','UNBILLED-MEMO','INS-2025','SUB-2025']},
 {id:'J-01',title:'Tax balances and computations',area:'Tax',assertions:'Completeness, valuation and presentation',accounts:['1400','2200','2210','1600','2610','2600'],procedures:['Agree supported taxable transactions to GST controls.','Prepare the current-tax book-to-tax reconciliation.','Reconcile tax instalments to the current-tax balance.','Assess tax bases and DTA recoverability assumptions.'],evidence:['GST-2025-12','TAX-MEMO']},
 {id:'K-01',title:'Borrowings and cash flows',area:'Financing',assertions:'Completeness, classification and accuracy',accounts:['2500','2510','2520','2530','6410'],procedures:['Reconcile opening debt to principal repayments.','Assess current/non-current classification.','Exclude non-cash lease commencement from cash flows.','Agree indirect operating cash flow to actual cash movements.'],evidence:['LOAN-AGREEMENT','LEASE-2025']},
 {id:'L-01',title:'Financial statements and final review',area:'Reporting',assertions:'Presentation, disclosure and overall reasonableness',accounts:['3000','3100','6800','6810'],procedures:['Agree all statements to the final trial balance.','Review accounting policies and significant judgments.','Prepare contingencies, subsequent events and going-concern assessments.','Note that missing prior-year income information prevents a complete statutory comparative set.'],evidence:['TB-OPEN','LEGAL-LETTER','TAX-MEMO']},
];
