#!/usr/bin/env python3
"""Real DOM regression: compact tasks, filters, precise amounts, mail and native modals."""
from pathlib import Path
import json, os, sys
from playwright.sync_api import sync_playwright
HTML=Path(sys.argv[1]);OUT=Path(sys.argv[2]);OUT.mkdir(parents=True,exist_ok=True)
checks=[];errors=[]
def ck(value,label):
    assert value,label
    checks.append(label);print(f'PASS {len(checks)} {label}',flush=True)
def idle(page):page.wait_for_function('!ledgerlabPreview.model().saving')
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
    ctx=browser.new_context(viewport={'width':1440,'height':900},accept_downloads=True)
    page=ctx.new_page();page.set_default_timeout(8000);page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content(HTML.read_text(),wait_until='domcontentloaded');page.wait_for_function('!!window.ledgerlabPreview')
    day=page.locator('[data-window=workbench]')
    ck(page.locator('.pc-navigation [data-section]').count()==7,'Seven navigation sections retained')
    ck(page.locator('.pc-navigation [data-section=today]').get_attribute('aria-current')=='page','Today reports current navigation section')
    ck(page.locator('.pc-storage-banner').is_visible(),'Memory-only warning is always visible in opaque-origin preview')
    ck('memory' in page.locator('.pc-storage-banner').inner_text().lower(),'Warning does not claim durable storage')
    box=day.locator('.day-task').first.bounding_box()
    ck(box['y']+box['height']<850,'Next task is visible without scrolling at 1440 by 900')
    ck(not day.locator('.day-routine').evaluate('(el)=>el.open'),'Routine is collapsed rather than burying work')
    page.screenshot(path=str(OUT/'01-today.png'))
    day.locator('.day-nav [data-day-action=tasks]').click()
    q=day.locator('[name=day-query]');q.press_sequentially('HANDOVER')
    ck(q.input_value()=='HANDOVER','Task search retains every typed character across repaint')
    ck(q.evaluate('(el)=>el===document.activeElement'),'Task search retains keyboard focus')
    day.locator('[name=day-kind]').select_option('processing')
    ck(day.locator('.day-task').count()==3,'Work area and text query combine')
    q.fill(page.evaluate('ledgerlabPreview.model().company.documents.find(d=>d.id==="HANDOVER-ACCRUAL").title'))
    ck(day.locator('.day-task').count()==1,'Displayed source title can be used to find its task')
    day.locator('[data-day-action=reset-filters]').click()
    ck(q.input_value()=='' and day.locator('[name=day-kind]').input_value()=='all','Reset restores filters together')
    result=page.evaluate('ledgerlabPreview.session.save({type:"advanceWorkday",date:"2025-08-01",note:"Release the closing evidence for pagination checks.",acknowledgeOutstanding:true})')
    ck(result['ok'],'Scenario date advances through actual command validation')
    day.locator('.day-nav [data-day-action=tasks]').click();day.locator('[name=day-filter]').select_option('all')
    ck(day.locator('.day-task').count()==20,'Large task queue is paginated to twenty rows')
    day.locator('[data-day-action=next-page]').click()
    ck('21–40' in day.locator('.day-pages').inner_text(),'Next task page has correct record range')
    q.fill('impossible-reference-zz')
    ck(day.locator('.day-task').count()==0 and 'Page 1 / 1' in day.locator('.day-pages').inner_text(),'No-result query resets out-of-range pagination')
    day.locator('[data-day-action=reset-filters]').click();page.screenshot(path=str(OUT/'02-tasks.png'))
    page.evaluate('ledgerlabPreview.desktop.openDaily("2025-07-welcome")')
    amount=day.locator('[name^="day-figure:"]').first;note=day.locator('[name=day-note]')
    amount.fill('1,2');note.fill('I investigated the inherited bank information and documented my first-day priorities and outstanding evidence.')
    day.locator('[data-day-action=save]').click();idle(page)
    ck('commas must group' in day.locator('[role=alert]').inner_text(),'Ambiguous decimal comma is rejected visibly')
    ck(amount.input_value()=='1,2','Invalid amount remains visible for correction')
    ck(page.evaluate('!ledgerlabPreview.model().state.workday.submissions["2025-07-welcome"]'),'Rejected amount never saves a response')
    amount.fill('1,234.56');day.locator('[data-day-action=save]').click();idle(page)
    ck('Response draft saved' in day.inner_text(),'Valid grouped amount saves normally')
    ck(123456 in page.evaluate('Object.values(ledgerlabPreview.model().state.workday.submissions["2025-07-welcome"].figures)'),'Valid amount saved as exact integer cents')
    # Changing unrelated mail state must preserve a response cursor and current draft.
    note.fill('A retained response draft while another piece of saved workspace data changes.');note.focus();note.evaluate('(el)=>el.setSelectionRange(12,20)')
    page.evaluate('ledgerlabPreview.session.save({type:"markDesktopMailRead",mailId:"MAIL-WELCOME",read:true})');idle(page)
    ck(note.input_value().startswith('A retained response'),'Unrelated save does not overwrite unsaved response')
    ck(note.evaluate('(el)=>el===document.activeElement&&el.selectionStart===12&&el.selectionEnd===20'),'Unrelated save retains response focus and selected text')
    # Native modal must be actually modal, not an aria label on a normal div.
    page.locator('[data-close-task=workbench]').click();dialog=page.locator('dialog.pc-modal-backdrop[open]')
    ck(dialog.evaluate('(el)=>el.matches(":modal")'),'Dirty close uses real browser-native modality')
    page.locator('[data-section=work]').evaluate('(el)=>el.focus()')
    ck(dialog.evaluate('(el)=>el.contains(document.activeElement)'),'Background cannot steal focus from modal')
    for _ in range(7):page.keyboard.press('Tab')
    ck(dialog.evaluate('(el)=>el.contains(document.activeElement)'),'Tab remains within modal controls')
    page.keyboard.press('Escape')
    ck(dialog.count()==0 and note.input_value().startswith('A retained response'),'Escape cancels closing and preserves draft')
    # Same-seed, same-start timestamp restore still invalidates old draft ownership.
    state=page.evaluate('ledgerlabPreview.model().state')
    ck(page.evaluate('(state)=>ledgerlabPreview.session.save({type:"importBackup",state})',state)['ok'],'Same-case backup can be restored')
    page.evaluate('ledgerlabPreview.desktop.openDaily("2025-07-welcome")')
    ck('saved case' in day.locator('[role=alert]').inner_text().lower(),'Same-case restore marks previous unsaved response stale')
    day.locator('[data-day-action=save]').click()
    ck('saved case' in day.locator('[role=alert]').inner_text().lower() and page.evaluate('ledgerlabPreview.model().state.workday.submissions["2025-07-welcome"].note') == state['workday']['submissions']['2025-07-welcome']['note'],'Stale response cannot save into restored case')
    day.locator('[data-day-action=discard]').first.click()
    # Mail folders distinguish correspondence from real incoming unread work.
    page.evaluate('ledgerlabPreview.desktop.openMail()');mail=page.locator('[data-window=mail]')
    unread_before=mail.locator('.pc-mail-toolbar small').inner_text()
    mail.get_by_label('Mail folder',exact=True).select_option('drafts')
    ck(mail.locator('[data-mail]').count()>=1,'Saved draft is visible in Drafts folder')
    ck(mail.locator('[data-unread=true]').count()==0,'Outgoing drafts are not styled as unread incoming mail')
    ck(mail.get_by_label('Unread emails only').is_disabled(),'Unread filter disabled for outgoing draft folder')
    mail.get_by_label('Search scenario emails').fill('not-a-message')
    page.evaluate('ledgerlabPreview.desktop.openMail("MAIL-WELCOME")')
    ck(mail.get_by_label('Mail folder',exact=True).input_value()=='inbox' and mail.get_by_label('Search scenario emails').input_value()=='','Explicit message links clear stale folder and search filters')
    ck(mail.locator('[data-mail="MAIL-WELCOME"]').get_attribute('data-active')=='true','Explicit message link selects the requested mail')
    ck(mail.locator('.pc-mail-toolbar small').inner_text()==unread_before,'Folder/search navigation does not alter unread totals')
    # Diagnostics use actual journal postings and do not change financial state.
    before=page.evaluate('JSON.stringify(ledgerlabPreview.model().state)')
    page.evaluate('ledgerlabPreview.desktop.openApp("ledger-checks")');health=page.locator('[data-window=ledger-checks]')
    ck(health.locator('.pc-health').is_visible(),'Ledger diagnostics are reachable as a working feature')
    ck('not the worked solution' in health.inner_text(),'Diagnostics clearly distinguish actual-ledger checks from answer grading')
    with page.expect_download() as dl:health.locator('[data-health-export]').click()
    text=Path(dl.value.path()).read_text()
    ck('Severity' in text and 'Finding' in text,'Ledger checks export an inspectable CSV')
    ck(page.evaluate('JSON.stringify(ledgerlabPreview.model().state)')==before,'Diagnostics and export do not post or mutate saved state')
    page.screenshot(path=str(OUT/'03-ledger-checks.png'))
    # Backup shortcut works even when a workbook consumes ordinary Ctrl+S.
    page.evaluate('ledgerlabPreview.desktop.newWorkbook()');page.locator('.xl-formula-input').first.wait_for() if page.locator('.xl-formula-input').count() else None
    with page.expect_download() as dl: page.keyboard.press('Control+Shift+s')
    ck('backup' in dl.value.suggested_filename.lower(),'Dedicated shortcut exports a saved-state backup')
    page.locator('[data-action=global-search]').click();search=page.locator('#ledgerlab-global-query');search.fill('ledger')
    ck(search.get_attribute('role')=='combobox','Search exposes combobox semantics')
    search.press('ArrowDown')
    ck(bool(search.get_attribute('aria-activedescendant')),'Search announces the active keyboard result')
    page.keyboard.press('Escape')
    page.set_viewport_size({'width':390,'height':844});page.evaluate('ledgerlabPreview.desktop.openDaily()')
    ck(page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),'Narrow workspace has no whole-page horizontal overflow')
    button=page.locator('.pc-storage-banner [data-action=backup-now]').bounding_box()
    ck(button['x']>=0 and button['x']+button['width']<=390,'Narrow-screen backup action fits entirely inside viewport')
    page.locator('.day-nav [data-day-action=today]').click()
    page.locator('.pc-toast').evaluate('(el)=>el.hidden=true')
    page.screenshot(path=str(OUT/'04-mobile.png'))
    ck(errors==[],'No uncaught errors in clarity/safety browser journey')
    browser.close()
(OUT/'results.json').write_text(json.dumps({'assertions':len(checks),'checks':checks,'page_errors':errors},indent=2))
print(f'Clarity Chromium: {len(checks)} assertions passed.',flush=True)
