#!/usr/bin/env python3
"""End-to-end daily-desktop acceptance. Uses real Chromium DOM and the real command/session engine.
Pass standalone HTML, generated workday-fixture JSON and output directory. Fixtures are never shipped in the app.
"""
from pathlib import Path
import json,sys,os
from playwright.sync_api import sync_playwright,expect
HTML=Path(sys.argv[1]).resolve();FIX=json.loads(Path(sys.argv[2]).read_text());OUT=Path(sys.argv[3]);OUT.mkdir(parents=True,exist_ok=True)
checks=[]
def ck(v,label):
 assert v,label
 checks.append(label);print(f'PASS {len(checks)} {label}',flush=True)
def idle(page):page.wait_for_function('!ledgerlabPreview.model().saving')
def date(page):return page.evaluate('ledgerlabPreview.model().state.workday.today')
def focus(page,id):
 page.evaluate('(id)=>{const btn=document.querySelector(`[data-task="${id}"]`);const w=document.querySelector(`[data-window="${id}"]`);if(btn&&(!w||w.hidden||w.dataset.active!=="true"))btn.click();}',id)
def daily(page):focus(page,'workbench');return page.locator('[data-window=workbench]')
def da(page,a):daily(page).locator('[data-day-action="'+a+'"]').first.click()
def open_task(page,slug):page.evaluate('(id)=>ledgerlabPreview.desktop.openDaily(id)', '2025-07-'+slug)
def fill_response(page,values=None):
 w=daily(page);r=values or FIX['welcome']
 for key,value in r['figures'].items():w.locator('[name="day-figure:'+key+'"]').fill(f'{value/100:.2f}')
 if r['decision']:w.locator('[name=day-decision]').select_option(r['decision'])
 w.locator('[name=day-note]').fill(r['note']);w.locator('[name=day-evidence]').fill(', '.join(r['evidence']))
def advance(page,target,ack=True):
 page.evaluate('ledgerlabPreview.desktop.openDaily(undefined,true)');w=daily(page);w.locator('[name=day-date]').fill(target);w.locator('[name=day-date]').press('Tab')
 if ack:w.locator('[name=day-ack]').check()
 w.locator('[data-day-action=advance]').click();idle(page)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
 context=browser.new_context(viewport={'width':1500,'height':1000},accept_downloads=True);page=context.new_page();page.set_default_timeout(10000)
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content(HTML.read_text());page.wait_for_function('!!window.ledgerlabPreview')
 ck(date(page)=='2025-07-01','Fresh daily job begins on first of July')
 ck(page.locator('.day-header').is_visible(),'Daily desk is the first open window')
 ck(page.locator('[data-action=clock]').is_visible(),'Taskbar date is a working clock button')
 ck('6' in page.locator('.day-stats').inner_text(),'First-day queue is small rather than full month')
 page.screenshot(path=str(OUT/'today.png'),full_page=True)
 da(page,'welcome');mail=page.locator('[data-window=mail]')
 expect(mail.locator('.pc-message h2')).to_contain_text('Welcome')
 ck('PC date and the open accounting month are different' in mail.inner_text(),'Onboarding explains the two dates')
 ck(mail.locator('[data-source=HANDOVER]').count()==1,'Onboarding links to predecessor handover')
 mail.locator('[data-action=read]').click();idle(page)
 ck(page.evaluate('ledgerlabPreview.model().state.desktop.readMail.includes("MAIL-WELCOME")'),'Read marker genuinely saves')
 ck(page.evaluate('Object.keys(ledgerlabPreview.model().state.workday.submissions).length')==0,'Reading mail does not complete an assignment')
 mail.locator('[data-action=app]').click()
 ck(daily(page).locator('.day-response').is_visible(),'Email opens the exact first-day assignment')
 page.locator('[data-close-task=mail]').click();ck(page.locator('[data-window=mail]').count()==0,'Mail taskbar close actually removes window')
 # Invalid numeric text survives other UI actions and cannot silently turn into an old saved value.
 daily(page).locator('[name="day-figure:bank"]').fill('12oops')
 daily(page).locator('[data-day-action=cite]').first.click()
 ck(daily(page).locator('[name="day-figure:bank"]').input_value()=='12oops','Invalid amount text survives evidence selection without silent replacement')
 open_task(page,'welcome')
 ck(daily(page).locator('[name="day-figure:bank"]').input_value()=='12oops','Reopening the same assignment preserves its unsaved response')
 da(page,'save');idle(page)
 ck('valid amounts' in daily(page).locator('[role=alert]').inner_text(),'Invalid amount is rejected rather than saving a stale previous value')
 ck(daily(page).locator('[name="day-figure:bank"]').input_value()=='12oops','Rejected amount remains available for correction')
 fill_response(page,{**FIX['welcome'],'figures':{'bank':1}});da(page,'submit');idle(page)
 ck('Needs correction' in daily(page).inner_text(),'Incorrect amount receives visible feedback')
 ck(daily(page).locator('.day-review table').count()==1,'Feedback shows saved and independent amounts')
 ck(page.evaluate('ledgerlabPreview.model().state.journals.length')==0,'Reply submission never posts a journal')
 fill_response(page);da(page,'submit');idle(page)
 ck(daily(page).locator('.day-state').first.inner_text()=='Complete','Correct submission completes defined onboarding checks')
 ck(not page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Confirmed response clears dirty flag')
 # Close controls protect daily drafts, including failed submissions.
 daily(page).locator('[name=day-note]').fill('Unsaved revised plan: I will verify the inherited ledger and collect independent evidence before correcting the old accountant’s entries.')
 daily(page).locator('[data-window-action=close]').click();dialog=page.get_by_role('dialog')
 ck(dialog.is_visible(),'Closing unsaved response opens Save/Discard/Cancel dialog')
 dialog.get_by_role('button',name='Cancel',exact=True).click();ck(daily(page).locator('[name=day-note]').input_value().startswith('Unsaved revised'),'Cancel preserves response')
 daily(page).locator('[data-window-action=close]').click();page.get_by_role('dialog').get_by_role('button',name='Save draft & close',exact=True).click();idle(page)
 ck(page.locator('[data-window=workbench]').count()==0,'Save draft & close really closes the daily window')
 ck(page.evaluate('ledgerlabPreview.model().state.workday.submissions["2025-07-welcome"].status')=='draft','Save & close saves draft without falsely submitting it')
 open_task(page,'welcome');fill_response(page);da(page,'submit');idle(page);da(page,'check')
 ck('Future transactions are not counted as missing' in daily(page).inner_text(),'Daily checking explicitly excludes unreleased activity')
 with page.expect_download() as dl:da(page,'export-check')
 export=OUT/'daily-check.csv';dl.value.save_as(export);ck('PC date,Task,Status,Due,Detail' in export.read_text(encoding='utf-8-sig'),'Daily report exports actual task statuses')
 # Full month review remains gated in both menu and posting boundary.
 da(page,'month-close');ck('opens on 2025-08-01' in daily(page).locator('[role=alert]').inner_text(),'Early month-review button gives clear opening date')
 page.evaluate('ledgerlabPreview.desktop.openApp("close")');app=page.locator('[data-window=accounting]')
 ck(app.locator('.mr-panel').count()==0,'Alternate accounting view cannot reveal full-month answer screen early')
 ck('Work from today’s assignments' in app.inner_text(),'Early accounting close view routes to current work')
 app.locator('[data-window-action=close]').click()
 advance(page,'2025-07-04',False)
 ck(date(page)=='2025-07-01','Skipped deadlines cannot be silently accepted')
 ck('Acknowledge' in daily(page).locator('[role=alert]').inner_text(),'Advance error identifies missing acknowledgement')
 daily(page).locator('[name=day-ack]').check();da(page,'advance');idle(page)
 ck(date(page)=='2025-07-04','Acknowledged date change persists')
 ck(page.evaluate('ledgerlabPreview.model().state.journals.length')==0,'Advancing never auto-processes bank or source records')
 ck(page.evaluate('ledgerlabPreview.model().company.documents.some(d=>d.kind==="Supplier invoice"&&d.date==="2025-07-03")'),'Prior-day supplier invoice arrives when due')
 ck(not page.evaluate('!!ledgerlabPreview.model().company.payroll["2025-07"]'),'Payroll remains hidden before review pack delivery')
 da(page,'log');ck('2025-07-01 → 2025-07-04' in daily(page).inner_text(),'Day log records the actual date jump')
 page.evaluate('ledgerlabPreview.session.load()');idle(page)
 ck(date(page)=='2025-07-04','Workspace reload restores scenario date from the local adapter')
 ck(page.evaluate('!!ledgerlabPreview.model().state.workday.submissions["2025-07-welcome"]'),'Workspace reload restores submitted first-day response')
 ck(page.evaluate('ledgerlabPreview.model().saveStatus')=='Preview memory only','Blocked-navigation browser harness correctly declares memory-only persistence')
 # Unsaved accounting form blocks date change even after closing that window.
 page.evaluate('ledgerlabPreview.desktop.openApp("ledger")');app=page.locator('[data-window=accounting]')
 app.locator('[name=journal-description]').fill('Unposted draft to retain while navigating')
 ck(page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Editing a journal form registers unsaved work')
 app.locator('[data-window-action=close]').click();advance(page,'2025-07-07')
 ck(date(page)=='2025-07-04','Date change blocked by retained accounting-form draft')
 ck('accounting-form drafts' in daily(page).locator('[role=alert]').inner_text(),'Date error explains how to clear unsaved work')
 page.evaluate('ledgerlabPreview.desktop.openApp("ledger")');app=page.locator('[data-window=accounting]')
 ck(app.locator('[name=journal-description]').input_value()=='Unposted draft to retain while navigating','Closing/reopening accounting preserves its draft')
 app.locator('[data-local=discard-forms]').click();page.get_by_role('dialog').get_by_role('button',name='Discard accounting drafts',exact=True).click()
 ck(not page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Explicit discard clears retained accounting drafts')
 app.locator('[data-window-action=close]').click();advance(page,'2025-07-07')
 ck(date(page)=='2025-07-07','Next workday advance works after saving/discarding drafts')
 open_task(page,'cash-07')
 with page.expect_download() as dl:da(page,'cash-extract')
 bank=OUT/'weekly-bank-extract.csv';dl.value.save_as(bank)
 ck('Delivered' in bank.read_text(),'Weekly request exports a reproducible as-of bank extract')
 ck('2025-07-25' not in bank.read_text(),'Weekly bank snapshot cannot reveal later pay run')
 da(page,'calendar');advance(page,'2025-07-14')
 bank_task=next(t for t in FIX['julyTasks'] if t['id'].endswith('bank-change'))
 control={'figures':{},'decision':'release','note':FIX['welcome']['note'],'evidence':bank_task['evidence']}
 open_task(page,'bank-change');fill_response(page,control);da(page,'submit');idle(page)
 ck(daily(page).locator('.day-state').first.inner_text()=='Needs correction','Unsafe supplier-detail change gets correction feedback')
 fill_response(page,{**control,'decision':'hold-verify'});da(page,'submit');idle(page);advance(page,'2025-07-15')
 page.evaluate('ledgerlabPreview.desktop.openMail("MAIL-REPLY-2025-07-bank-change")');mail=page.locator('[data-window=mail]')
 ck('existing bank details have not changed' in mail.inner_text(),'Next-day callback reply reflects the submitted safe decision')
 page.screenshot(path=str(OUT/'supplier-control-mail.png'),full_page=True)
 mail.locator('[data-window-action=close]').click();advance(page,'2025-07-23')
 ck(page.evaluate('!!ledgerlabPreview.model().company.payroll["2025-07"]'),'Payroll pack releases before pay day in browser')
 open_task(page,'payroll-release');da(page,'workspace');app=page.locator('[data-window=accounting]')
 ck('Alex Taylor' in app.inner_text(),'Payroll workspace exposes delivered authorised employee figures')
 app.locator('[data-window-action=close]').click()
 # Unsaved response survives external refresh and cannot overwrite a newer one.
 open_task(page,'payroll-release');daily(page).locator('[name=day-note]').fill('Preserve this local payroll investigation draft while I check the original records and obtain HR clarification.');
 page.evaluate('ledgerlabPreview.session.load()');idle(page)
 ck(daily(page).locator('[name=day-note]').input_value().startswith('Preserve this local'),'Reload retains an unsaved daily response in the same case')
 da(page,'discard')
 payroll=next(t for t in FIX['julyTasks'] if t['id'].endswith('payroll-release'))
 pr={'figures':{f['id']:f['expected'] for f in payroll['figures']},'decision':payroll['correctDecision'],'note':FIX['welcome']['note'],'evidence':payroll['evidence']}
 fill_response(page,pr);page.evaluate('ledgerlabPreview.dropNextAcknowledgement()');da(page,'submit');idle(page)
 ck('Save failed' in daily(page).locator('[role=alert]').inner_text() or 'Reload' in daily(page).locator('[role=alert]').inner_text(),'Uncertain save is not falsely confirmed')
 ck(page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Uncertain-save response remains unsaved in UI')
 page.evaluate('ledgerlabPreview.session.load()');idle(page)
 ck(daily(page).locator('[data-day-action=download-response]').count()==1,'Reloaded newer saved response preserves old draft with conflict notice')
 da(page,'discard');ck(daily(page).locator('.day-state').first.inner_text()=='Complete','Explicit discard loads acknowledged saved response after lost response')
 advance(page,'2025-08-01');ck(date(page)=='2025-08-01','PC can enter next calendar month while accounting month stays open')
 ck(page.evaluate('ledgerlabPreview.model().state.career.activeMonth')=='2025-07','July accounting period remains open for its early-August close')
 page.evaluate('ledgerlabPreview.desktop.openApp("close")');app=page.locator('[data-window=accounting]')
 ck(app.locator('.mr-panel').is_visible(),'Full month review becomes available on close-pack arrival')
 ck('Daily management requests' in app.inner_text(),'Month review includes outstanding daily management work')
 app.locator('[data-window-action=close]').click()
 formal=next(t for t in FIX['julyTasks'] if t['kind']=='formal' and t['release']<='2025-08-01')
 page.evaluate('(id)=>ledgerlabPreview.desktop.openDaily(id)',formal['id']);da(page,'workspace');app=page.locator('[data-window=accounting]')
 ck(app.locator('details[data-task="'+formal['formalId']+'"]').get_attribute('open') is not None,'Formal assignment opens its exact deliverable rather than an unrelated finance screen')
 app.locator('[data-window-action=close]').click()
 forecast=next(t for t in FIX['julyTasks'] if t['kind']=='forecast')
 page.evaluate('(id)=>ledgerlabPreview.desktop.openDaily(id)',forecast['id']);da(page,'workspace');app=page.locator('[data-window=accounting]')
 ck(app.locator('[name="forecast-assumptions"]').is_visible(),'Forecast assignment opens the actual editable forecast directly')
 app.locator('[data-window-action=close]').click();page.evaluate('ledgerlabPreview.desktop.openDaily()');da(page,'today');page.screenshot(path=str(OUT/'close-week-desk.png'),full_page=True)
 # Another browser tab sees durable date and progress; clock date is not system date.
 saved_case=page.evaluate('ledgerlabPreview.model().state');second=context.new_page();second.set_content(HTML.read_text());second.wait_for_function('!!window.ledgerlabPreview');second.evaluate('(state)=>ledgerlabPreview.session.save({type:"importBackup",state})',saved_case);idle(second)
 ck(date(second)=='2025-08-01','Full saved-case backup restores the daily job in another tab')
 ck(second.evaluate('ledgerlabPreview.model().state.workday.history.length')==page.evaluate('ledgerlabPreview.model().state.workday.history.length'),'Case-backup restore retains all date history')
 # Narrow layout uses real close controls and visible daily actions.
 small=browser.new_page(viewport={'width':600,'height':850});small.on('pageerror',lambda e:errors.append(str(e)));small.set_content(HTML.read_text());small.wait_for_function('!!window.ledgerlabPreview')
 ck(small.locator('.day-header').is_visible(),'Daily desk remains readable at 600px')
 ck(small.locator('.day-header [data-day-action=calendar]').is_visible(),'Narrow layout retains a change-date button')
 ck(small.locator('.day-desk').evaluate('(el)=>el.scrollWidth<=el.clientWidth+1'),'Daily desk has no horizontal overflow on narrow screen')
 small.screenshot(path=str(OUT/'daily-narrow.png'),full_page=True)
 small.locator('[data-window=workbench] [data-window-action=close]').click();ck(small.locator('[data-window=workbench]').count()==0,'Close controls work in narrow layout')
 ck(not errors,'No uncaught browser exceptions through daily workflows')
 (OUT/'workday-browser-verification.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'errors':errors,'storage_test':'Chromium set_content because file navigation is blocked by environment policy. Browser tests use the declared memory fallback, workspace reload and explicit backup restore, not durable browser storage across process restart.'},indent=2))
 browser.close()
