#!/usr/bin/env python3
"""Real Chromium DOM interaction regression suite for the self-contained workstation.
The environment blocks browser navigation, so set_content is used. Workspace reload,
command persistence and uncertain saves use the real WorkspaceSession with the local
memory fallback; a separate SQLite suite covers production request persistence.
"""
from pathlib import Path
import os,sys,json,zipfile,io
from playwright.sync_api import sync_playwright,expect
HTML=Path(sys.argv[1]).read_text();OUT=Path(sys.argv[2]);OUT.mkdir(parents=True,exist_ok=True)
checks=[]
def check(v,label):
    assert v,label
    checks.append(label)
    print('PASS',len(checks),label,flush=True)
def setup(browser,width=1600,height=1050):
    page=browser.new_page(viewport={'width':width,'height':height},accept_downloads=True)
    page.set_default_timeout(5000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content(HTML,wait_until='load');page.wait_for_function('!!window.ledgerlabPreview');page.evaluate('ledgerlabPreview.session.save({type:"startCareer",seed:271828,startMonth:"2025-07",role:"financial-manager",scenario:"messy",daily:false,confirmation:"START TAKEOVER"})');return page,errors
def win(page):
    id=page.locator('.pc-window[data-active=true]').get_attribute('data-window');return page.locator(f'.pc-window[data-window="{id}"]')
def focus(page,id):page.locator(f'.pc-taskbar [data-task="{id}"]').click()
def goto(w,ref):w.get_by_label('Name box',exact=True).fill(ref);w.get_by_label('Name box',exact=True).press('Enter')
def cell(w,ref):return w.locator(f'td[aria-label="{ref}"] .xl-cell-value')
def enter(w,ref,value):goto(w,ref);w.locator('.xl-grid-scroll').press('F2');w.locator('.xl-cell-editor').fill(value);w.locator('.xl-cell-editor').press('Enter')
def raw(w,ref):goto(w,ref);return w.get_by_label('Formula bar',exact=True).input_value()
def paste(w,text):w.locator('.xl-grid-scroll').evaluate('(el,text)=>{const d=new DataTransfer();d.setData("text/plain",text);el.dispatchEvent(new ClipboardEvent("paste",{bubbles:true,cancelable:true,clipboardData:d}));}',text)
def save(w):w.locator('[data-action=save]').click();expect(w.locator('.pc-editor-status')).to_contain_text('Saved with this case')
def close(w):w.locator('[data-window-action=close]').click()
def workbook(page):
    page.locator('.pc-taskbar [data-action=drive]').click();page.locator('[data-window=explorer] [data-action=new-workbook]').click();w=win(page);w.locator('[data-window-action=max]').click();return w,w.get_attribute('data-window')
def action(w,name):w.locator(f'[data-xl="{name}"]').click()
def ribbon(w,name):w.locator(f'[data-ribbon="{name}"]').click()
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
    page,errors=setup(browser)
    check(page.locator('.pc-workbench-steps article').count()==4,'Start here exposes a four-step workflow')
    page.screenshot(path=str(OUT/'workstation-home.png'))
    w,sid=workbook(page)
    check(w.locator('.xl-grid-scroll').get_attribute('aria-colcount')=='26','New workbook opens with A–Z columns')
    check(w.locator('.xl-grid-scroll').get_attribute('aria-rowcount')=='100','New workbook opens with 100 rows')
    w.locator('[data-action=file-details]').click();w.get_by_label('Working file name').fill('July control test.xlsx');w.locator('[data-action=file-details]').click()
    goto(w,'B6');w.locator('.xl-grid-scroll').press('1');w.locator('.xl-cell-editor').press('2');w.locator('.xl-cell-editor').press('5');w.locator('.xl-cell-editor').press('Enter')
    check(cell(w,'B6').inner_text()=='125','Typing starts replacement editing and Enter commits')
    check(w.get_by_label('Name box').input_value()=='B7','Enter moves down one cell')
    enter(w,'B7','24.75');enter(w,'B8','=SUM(B6:B7)')
    check(cell(w,'B8').inner_text()=='149.75','SUM recalculates after keyboard entry')
    check(raw(w,'B8')=='=SUM(B6:B7)','Formula bar shows raw formula rather than display value')
    goto(w,'B8');w.locator('.xl-grid-scroll').press('F2');w.locator('.xl-cell-editor').fill('999');w.locator('.xl-cell-editor').press('Escape')
    check(raw(w,'B8')=='=SUM(B6:B7)','Escape cancels an in-cell edit')
    goto(w,'C6');w.get_by_label('Formula bar').fill('=B6+$B$7');w.get_by_label('Formula bar').press('Tab')
    check(raw(w,'C6')=='=B6+$B$7','Formula-bar edit commits with Tab')
    goto(w,'C6:C8');w.locator('.xl-grid-scroll').press('Control+d')
    check(raw(w,'C8')=='=B8+$B$7','Fill down adjusts relative and preserves absolute references')
    goto(w,'D6');paste(w,'=B6');w.locator('.xl-grid-scroll').press('F2');w.locator('.xl-cell-editor').press('End');w.locator('.xl-cell-editor').press('F4');w.locator('.xl-cell-editor').press('Enter')
    check(raw(w,'D6')=='=$B$6','F4 toggles an absolute reference during edit')
    goto(w,'C6');action(w,'copy');goto(w,'D9');action(w,'paste')
    check(raw(w,'D9')=='=C9+$B$7','Clipboard copy adjusts formula references to destination')
    goto(w,'B8');action(w,'copy');goto(w,'E9');action(w,'paste-values')
    check(raw(w,'E9')=='149.75','Paste values stores result, not formula')
    goto(w,'B12');paste(w,'1\t2\n3\t4')
    check(cell(w,'C13').inner_text()=='4','Multiline TSV paste fills a rectangular range')
    goto(w,'B12:C13');w.locator('.xl-grid-scroll').press('Delete')
    check(cell(w,'C13').inner_text()=='','Delete clears the entire selected range')
    w.locator('.xl-grid-scroll').press('Control+z');check(cell(w,'C13').inner_text()=='4','Undo restores a whole rectangular edit')
    w.locator('.xl-grid-scroll').press('Control+y');check(cell(w,'C13').inner_text()=='','Redo reapplies the same rectangular edit')
    goto(w,'B6');w.locator('.xl-grid-scroll').press('Control+b');check(w.locator('td[aria-label=B6]').evaluate('(el)=>getComputedStyle(el).fontWeight')=='700','Ctrl+B formats the selected cell')
    w.get_by_label('Number format',exact=True).select_option('accounting');check(cell(w,'B6').inner_text()=='125.00','Accounting number format applies')
    w.get_by_label('Cell fill',exact=True).fill('#fff2cc');w.get_by_label('Cell fill',exact=True).dispatch_event('change');check('255, 242, 204' in w.locator('td[aria-label=B6]').evaluate('(el)=>getComputedStyle(el).backgroundColor'),'Cell fill applies to grid')
    enter(w,'E12','12.5%');check(cell(w,'E12').inner_text()=='12.50%','Percentage entry infers percentage formatting')
    enter(w,'F12','2025-07-31');check(cell(w,'F12').inner_text()=='2025-07-31','ISO date entry infers a date format')
    goto(w,'G12');paste(w,'2\n4');goto(w,'G12:G13')
    handle=w.locator('.xl-fill-handle').bounding_box();target=w.locator('td[aria-label=G16]').bounding_box();page.mouse.move(handle['x']+2,handle['y']+2);page.mouse.down();page.mouse.move(target['x']+15,target['y']+10,steps=10);page.mouse.up()
    check(cell(w,'G16').inner_text()=='10','Dragging the fill handle extends a two-number series')
    action(w,'add-sheet');check(w.locator('.xl-sheet-tabs [data-sheet]').count()==2,'Plus adds a real worksheet')
    ribbon(w,'view');action(w,'rename-sheet');w.get_by_label('Sheet name').fill('Support data');action(w,'confirm-rename')
    check(w.locator('.xl-sheet-tabs [data-sheet]').last.inner_text()=='Support data','Sheet rename updates its tab')
    enter(w,'A1','100');enter(w,'A2','200')
    w.locator('.xl-sheet-tabs [data-sheet]').first.click();enter(w,'F6',"=SUM('Support data'!A1:A2)")
    check(cell(w,'F6').inner_text()=='300','Cross-sheet formulas calculate from the other worksheet')
    w.locator('.xl-sheet-tabs [data-sheet]').last.click();action(w,'rename-sheet');w.get_by_label('Sheet name').fill('Source data');action(w,'confirm-rename');w.locator('.xl-sheet-tabs [data-sheet]').first.click()
    check(raw(w,'F6')=="=SUM('Source data'!A1:A2)",'Renaming a sheet updates references without breaking the formula')
    action(w,'formulas');check(cell(w,'F6').inner_text().startswith('=SUM'),'Show formulas changes the grid display');action(w,'formulas')
    action(w,'freeze-row');check(w.locator('td[aria-label=A1]').evaluate('(el)=>getComputedStyle(el).position')=='sticky','Freeze top row pins row one')
    action(w,'freeze-col');check(w.locator('td[aria-label=A20]').evaluate('(el)=>getComputedStyle(el).position')=='sticky','Freeze first column pins column A')
    action(w,'unfreeze');check(w.locator('td[aria-label=A20]').evaluate('(el)=>getComputedStyle(el).position')!='sticky','Unfreeze removes frozen panes')
    w.locator('[data-delete-sheet]').last.click();expect(page.get_by_role('dialog')).to_be_visible();page.get_by_role('dialog').get_by_role('button',name='Cancel',exact=True).click();check(w.locator('[data-sheet]').count()==2,'Cancel worksheet delete keeps both sheets')
    w.locator('[data-delete-sheet]').last.click();page.get_by_role('dialog').get_by_role('button',name='Delete sheet',exact=True).click();check(w.locator('[data-sheet]').count()==1,'Worksheet tab × deletes only after confirmation')
    check(cell(w,'F6').inner_text().startswith('#REF'),'Deleted-sheet dependent formula shows REF')
    ribbon(w,'home');action(w,'undo');check(w.locator('[data-sheet]').count()==2 and cell(w,'F6').inner_text()=='300','Undo restores deleted sheet and its dependent formulas')
    goto(w,'A30');paste(w,'Name\tAmount\nZulu\t3\nAlpha\t1\nBeta\t2');goto(w,'A30:B33');ribbon(w,'data');action(w,'sort-asc');check(cell(w,'A31').inner_text()=='Alpha' and cell(w,'B31').inner_text()=='1','Sort moves the selected rows together and retains headers')
    action(w,'filter');w.get_by_label('Filter rows',exact=True).fill('Alpha');check(w.locator('td[aria-label=A32]').is_hidden(),'Filter hides nonmatching rows without deleting data');action(w,'clear-filter');check(w.locator('td[aria-label=A32]').is_visible(),'Clear filter restores rows')
    goto(w,'A31');action(w,'insert-row');check(cell(w,'A32').inner_text()=='Alpha','Insert row shifts existing data down');action(w,'delete-row');check(cell(w,'A31').inner_text()=='Alpha','Delete row restores data position')
    ribbon(w,'home');action(w,'find');w.get_by_label('Find in sheet').fill('Zulu');action(w,'find-next');check(w.get_by_label('Name box').input_value()=='A33','Find locates a matching cell');w.get_by_label('Replace with').fill('Gamma');action(w,'replace');check(cell(w,'A33').inner_text()=='Gamma','Replace changes the selected match');action(w,'close-find')
    goto(w,'B6');save(w);check(page.evaluate('(id)=>ledgerlabPreview.model().state.desktop.files.find(f=>f.id===id).sheets.length',sid)==2,'Save persists a multi-sheet workbook through the session command')
    # Editing a previously saved cell enables Save even before Enter.
    goto(w,'B6');w.locator('.xl-grid-scroll').press('F2');w.locator('.xl-cell-editor').fill('250');check(w.locator('[data-action=save]').is_enabled(),'Save is enabled for an uncommitted edit in a previously saved workbook')
    check(page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Uncommitted edit participates in unsaved-work guard');save(w);check(cell(w,'B6').inner_text()=='250.00','Clicking Save commits the active edit before saving')
    with page.expect_download() as dl:w.locator('[data-action=download]').click()
    exported=OUT/'browser-workbook.xlsx';dl.value.save_as(exported)
    with zipfile.ZipFile(exported) as z:
        check('xl/worksheets/sheet2.xml' in z.namelist(),'Exported XLSX contains both worksheets')
        check(b'Source data' in z.read('xl/workbook.xml'),'Export preserves worksheet names')
        check(b'<f>' in z.read('xl/worksheets/sheet1.xml'),'Export preserves supported formulas')
    # Clean header close, reopen through the drive, taskbar close.
    close(w);check(page.locator(f'[data-window="{sid}"]').count()==0,'Clean title-bar close removes window')
    page.locator('.pc-taskbar [data-action=drive]').click();exp=page.locator('[data-window=explorer]');exp.locator('[data-folder="Working papers/2025-07"]').first.click();exp.locator(f'[data-file="{sid}"]').click();w=win(page)
    check(cell(w,'B6').inner_text()=='250.00','Reopening saved workbook restores values and formatting')
    # Maximize, minimize, taskbar restore; dirty taskbar Cancel, discard, save & close.
    w.locator('[data-window-action=max]').click();w.locator('[data-window-action=min]').click();check(w.is_hidden(),'Minimize hides the workbook without closing');focus(page,sid);check(w.is_visible(),'Taskbar restores a minimized workbook')
    enter(w,'B6','777');page.locator(f'[data-close-task="{sid}"]').click();page.get_by_role('dialog').get_by_role('button',name='Cancel',exact=True).click();check(w.is_visible() and cell(w,'B6').inner_text()=='777.00','Taskbar × Cancel keeps the unsaved draft')
    page.locator(f'[data-close-task="{sid}"]').click();page.get_by_role('dialog').get_by_role('button',name='Discard changes',exact=True).click();check(page.locator(f'[data-window="{sid}"]').count()==0,'Taskbar × Discard closes the editor')
    exp.locator(f'[data-file="{sid}"]').click();w=win(page);check(cell(w,'B6').inner_text()=='250.00','Discard does not overwrite the saved file')
    enter(w,'B6','321');close(w);page.get_by_role('dialog').get_by_role('button',name='Save & close',exact=True).click();expect(page.locator(f'[data-window="{sid}"]')).to_have_count(0);check(page.evaluate('(id)=>ledgerlabPreview.model().state.desktop.files.find(f=>f.id===id).cells[5][1]',sid)=='321','Title-bar Save & close waits for acknowledged persistence')
    # Genuine import through native file chooser.
    with page.expect_file_chooser() as chooser:exp.locator('[data-action=import-csv]').click()
    chooser.value.set_files(exported);page.wait_for_function("!!document.querySelector('.pc-window[data-active=true] .xl-workbook')");w=win(page);expect(w.locator('.xl-sheet-tabs [data-sheet]')).to_have_count(2)
    check(cell(w,'B6').inner_text()=='250.00','XLSX import restores numeric cells and number format');check(cell(w,'F6').inner_text()=='300','XLSX import restores cross-sheet calculations')
    close(w);page.get_by_role('dialog').get_by_role('button',name='Discard changes',exact=True).click()
    # Source safety and mail controls.
    exp.get_by_label('Search finance drive').fill('2025-08');check(exp.locator('.pc-file-list [data-file]').count()==0,'Future-month source files are not exposed by drive search')
    exp.get_by_label('Search finance drive').fill('');page.locator('.pc-taskbar [data-action=mail]').click();mail=page.locator('[data-window=mail]');mail.get_by_label('Search scenario emails').fill('July 2025: Monthly bank statement');mail.locator('[data-mail]').click();mid=mail.locator('[data-mail]').get_attribute('data-mail');mail.locator('[data-action=read]').click();check(page.evaluate('(id)=>ledgerlabPreview.model().state.desktop.readMail.includes(id)',mid),'Scenario mail read status is saved')
    mail.locator('[data-source]').first.click();doc=win(page);check('allow-scripts' not in doc.locator('iframe').get_attribute('sandbox'),'Source document iframe cannot execute scripts');close(doc);close(mail)
    # Operational app: journal validation, invoice capture and bank matching.
    page.evaluate("ledgerlabPreview.desktop.openApp('ledger')");app=page.locator('[data-window=accounting]');app.locator('[data-window-action=max]').click()
    for view in ['ledger','payables','receivables','bank','payroll','reports','assets','inventory','provisions','tax','audit','documents','knowledge','settings','career','close','overview','practice']:
        app.get_by_label('Accounting workspace',exact=True).select_option(view);check(app.locator('.lc-workspace').count()==1 and 'accounting-window preview' not in app.inner_text(),view+' opens an operational view, not a placeholder')
    app.get_by_label('Accounting workspace',exact=True).select_option('ledger')
    bank=page.evaluate("ledgerlabPreview.model().company.bank.find(r=>r.date.startsWith('2025-07')&&r.amount<0)")
    app.get_by_label('Journal description',exact=True).fill('UI cash payment');app.get_by_label('Journal reference',exact=True).fill('UI-PAY');app.get_by_label('Journal date',exact=True).fill(bank['date']);app.get_by_label('Account 1',exact=True).select_option('6400');app.get_by_label('Debit 1',exact=True).fill(f"{-bank['amount']/100:.2f}");app.get_by_label('Account 2',exact=True).select_option('1000');app.get_by_label('Credit 2',exact=True).fill('1.00')
    app.get_by_role('button',name='Post journal',exact=True).click();check('balance' in app.locator('[data-local-status]').inner_text().lower(),'Unbalanced journal is rejected with a visible explanation')
    app.get_by_label('Credit 2',exact=True).fill(f"{-bank['amount']/100:.2f}");app.get_by_role('button',name='Post journal',exact=True).click();page.wait_for_function('ledgerlabPreview.model().state.journals.length===1');check(page.evaluate('ledgerlabPreview.model().state.journals.length')==1,'Balanced journal posts to the actual learner ledger')
    jid=page.evaluate('ledgerlabPreview.model().state.journals[0].id');app.get_by_label('Accounting workspace',exact=True).select_option('bank');app.locator(f'[name="bank-{bank["id"]}"]').select_option(jid);app.locator(f'[data-local=match][data-id="{bank["id"]}"]').click();page.wait_for_function('(id)=>!!ledgerlabPreview.model().state.bankMatches[id]',arg=bank['id']);check(page.evaluate('(id)=>ledgerlabPreview.model().state.bankMatches[id]',bank['id'])==[jid],'Bank Match selected persists the selected journal IDs')
    app.locator(f'[data-local=unmatch][data-id="{bank["id"]}"]').click();page.wait_for_function('(id)=>!ledgerlabPreview.model().state.bankMatches[id]',arg=bank['id']);check(not page.evaluate('(id)=>!!ledgerlabPreview.model().state.bankMatches[id]',bank['id']),'Unmatch removes the match without deleting the posting')
    app.get_by_label('Accounting workspace',exact=True).select_option('payables');app.locator('[data-local=capture-select]').first.click();invoice=app.locator('[data-local=capture-post]').get_attribute('data-id')
    for s in app.locator('.lc-capture select[name^="Invoice account"]').all():s.select_option('1200')
    app.locator('[data-local=capture-post]').click();page.wait_for_function('(id)=>ledgerlabPreview.model().state.journals.some(j=>j.sourceId===id)',arg=invoice);check(page.evaluate('(id)=>ledgerlabPreview.model().state.journals.some(j=>j.sourceId===id)',invoice),'Invoice capture posts against the exact source document')
    app.locator('[data-local=capture-post]').click();expect(app.locator('[data-local-status]')).to_contain_text('already recorded');check('already recorded' in app.locator('[data-local-status]').inner_text(),'Duplicate invoice capture is blocked visibly')
    app.get_by_label('Accounting workspace',exact=True).select_option('career');task=app.locator('[data-task]').first;tid=task.get_attribute('data-task');task.locator('summary').click();task.locator('[data-local=task-draft]').click();page.wait_for_function('(id)=>!!ledgerlabPreview.model().state.career.submissions["2025-07|"+id]',arg=tid);check(page.evaluate('(id)=>ledgerlabPreview.model().state.career.submissions["2025-07|"+id]?.status',tid)=='draft','Formal role-deliverable draft saves through the career engine')
    app.locator('[data-local=forecast-toggle]').click();app.locator('[data-local=save-forecast-draft]').click();page.wait_for_function('!!ledgerlabPreview.model().state.career.forecasts["2025-07"]');check(page.evaluate('ledgerlabPreview.model().state.career.forecasts["2025-07"]?.status')=='draft','13-week forecast draft saves through the career engine')
    app.get_by_label('Accounting workspace',exact=True).select_option('close');app.get_by_label('Close / reopen reason').fill('Attempt incomplete close');app.locator('[data-local=close-month]').click();page.wait_for_function('!ledgerlabPreview.model().saving && !!ledgerlabPreview.model().error');check(not page.evaluate('!!ledgerlabPreview.model().state.career.closed["2025-07"]'),'Month close cannot bypass unfinished processing')
    app.get_by_label('Accounting workspace',exact=True).select_option('settings');app.locator('[name=notebook]').fill('Reconcile payroll before authorising payment.');app.locator('[data-local=save-notes]').click();page.wait_for_function('ledgerlabPreview.model().state.notes==="Reconcile payroll before authorising payment."');check(page.evaluate('ledgerlabPreview.model().state.notes')=='Reconcile payroll before authorising payment.','Notebook Save is functional')
    with page.expect_download() as dl:app.locator('[data-local=backup]').first.click()
    dl.value.save_as(OUT/'browser-case-backup.json');backup=json.loads((OUT/'browser-case-backup.json').read_text());check(len(backup['journals'])==2 and len(backup['desktop']['files'])>=1,'Full case backup includes journals and saved workbooks')
    check(not errors,'No uncaught browser errors in workbook, desktop or accounting workflow')
    close(app);check(page.locator('[data-window=accounting]').count()==0,'Accounting window title-bar close removes the accounting window')
    # Uncertain save acknowledgement must not close a draft.
    w,nid=workbook(page);enter(w,'B6','909');page.evaluate('ledgerlabPreview.dropNextAcknowledgement()');close(w);page.get_by_role('dialog').get_by_role('button',name='Save & close',exact=True).click();expect(w).to_be_visible();check(page.evaluate('(id)=>ledgerlabPreview.read().state.desktop.files.some(f=>f.id===id)',nid),'Lost acknowledgement fixture really saved the file in the backend')
    check('could not be saved' in page.locator('.pc-toast').inner_text(),'Failed Save & close leaves the window open with an explanation')
    check(cell(w,'B6').inner_text()=='909','Uncertain save preserves the editor draft')
    page.evaluate('ledgerlabPreview.session.load()');expect(w.locator('.pc-editor-status')).to_contain_text('changed elsewhere')
    w.locator('[data-action=reload-file]').click();page.get_by_role('dialog').get_by_role('button',name='Reload saved',exact=True).click();check(cell(w,'B6').inner_text()=='909','Explicit Reload saved recovers an uncertain new-file save')
    close(w);check(page.locator(f'[data-window="{nid}"]').count()==0,'Recovered clean window closes normally')
    # Repeat clean close on task tabs including minimized windows and background windows.
    for i in range(5):
        page.locator('.pc-taskbar [data-action=drive]').click();exp=page.locator('[data-window=explorer]');exp.locator('[data-action=new-window]').click();new=win(page);id=new.get_attribute('data-window')
        if i%2:new.locator('[data-window-action=min]').click()
        page.locator(f'[data-close-task="{id}"]').click();check(page.locator(f'[data-window="{id}"]').count()==0,f'Taskbar close removes window reliably on repeat {i+1}')
    # Final representative sheet screenshot.
    page.evaluate("ledgerlabPreview.desktop.newWorkbook('bank')");w=win(page);w.locator('[data-window-action=max]').click();page.screenshot(path=str(OUT/'workstation-spreadsheet.png'))
    check(w.locator('[data-sheet]').count()==5,'Bank template contains recon, statement, cashbook, learner TB and guidance sheets')
    small,small_errors=setup(browser,800,700);small.locator('.pc-workbench [data-action=new-sheet]').click();sw=win(small);check(sw.locator('[data-window-action=close]').is_visible(),'Window close control remains reachable on an 800px screen');close(sw);small.get_by_role('dialog').get_by_role('button',name='Discard changes',exact=True).click();expect(sw).to_have_count(0);check(small.locator('.xl-workbook').count()==0,'Small-screen dirty close completes without trapping the user')
    check(not errors and not small_errors,'No uncaught JavaScript errors in final and smaller-window checks')
    (OUT/'browser-verification.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'errors':errors+small_errors,'harness':'Chromium set_content; real DOM and session commands, memory storage fallback'},indent=2))
    print(f'PASS: {len(checks)} workstation browser assertions.',flush=True);browser.close()
