#!/usr/bin/env python3
"""Chromium acceptance for navigation, available-evidence search and review response safety.
Run with standalone HTML, generated workday fixture JSON, and an output directory.
"""
from pathlib import Path
import json, os, sys
from playwright.sync_api import sync_playwright, expect
HTML=Path(sys.argv[1]); FIX=json.loads(Path(sys.argv[2]).read_text()); OUT=Path(sys.argv[3]); OUT.mkdir(parents=True,exist_ok=True)
checks=[]
def ck(value,label):
    assert value,label
    checks.append(label);print(f'PASS {len(checks)} {label}',flush=True)
def idle(page): page.wait_for_function('!ledgerlabPreview.model().saving')
def open_search(page,query=''):
    page.locator('[data-action="global-search"]').click()
    page.locator('#ledgerlab-global-query').fill(query)
    return page.locator('.pc-command-palette')
def review(page):
    page.evaluate('ledgerlabPreview.desktop.openApp("review-notes")')
    return page.locator('[data-window="review-notes"]')
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1500,'height':1000},accept_downloads=True)
    page=context.new_page();page.set_default_timeout(10000)
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content(HTML.read_text(),wait_until='domcontentloaded');page.wait_for_function('!!window.ledgerlabPreview')
    ck(page.locator('.pc-navigation [data-section]').all_text_contents()==['Today','Work','Close','Reports','Files','Learn','Settings'],'Seven primary workspace sections')
    ck(page.locator('.day-header').is_visible(),'Today remains the first working window')
    page.locator('[data-section=work]').click()
    ck(page.locator('.pc-start [data-app=ledger]').is_visible(),'Work menu exposes existing accounting applications')
    page.locator('[data-section=close]').click()
    ck(page.locator('.pc-start [data-action=review-notes]').is_visible(),'Close menu exposes review responses')
    page.locator('[data-action=start]').click()
    page.locator('[data-action=global-search]').focus();page.keyboard.press('Control+k')
    ck(page.locator('.pc-command-palette').is_visible(),'Ctrl+K opens search')
    page.keyboard.press('Escape')
    ck(page.locator('.pc-command-palette').count()==0,'Escape closes search')
    ck(page.evaluate('document.activeElement.dataset.action')=='global-search','Escape restores prior keyboard focus')
    search=open_search(page,'PAY-2025-07')
    ck('0 results' in search.locator('[role=status]').inner_text(),'Future payroll evidence is excluded from search')
    search.locator('input').fill('TB-OPEN')
    ck('TB-OPEN' in search.locator('[data-search-result="0"]').inner_text(),'Exact source is first result')
    search.locator('input').press('Enter')
    ck(page.locator('.pc-command-palette').count()==0,'Enter opens selected result')
    ck(page.locator('.pc-window iframe').count()>0,'Search opens real source document viewer')
    open_search(page,'1000')
    page.locator('.pc-search-results button').filter(has=page.locator('.pc-search-kind',has_text='account')).first.click()
    ck(page.locator('.pc-inspection').is_visible(),'Account result opens read-only ledger inspection')
    ck(page.evaluate('ledgerlabPreview.model().state.journals.length')==0,'Searching does not create learner postings')
    page.evaluate('ledgerlabPreview.desktop.openDaily("2025-07-welcome")')
    day=page.locator('[data-window=workbench]')
    day.locator('.day-purpose summary').click()
    ck('Expected output' in day.locator('.day-purpose').inner_text(),'Task explains expected output without auto-answering')
    day.locator('[data-day-action=paired]').click()
    visible=page.locator('.pc-window:visible').evaluate_all('(els)=>els.map(el=>{const r=el.getBoundingClientRect();return {x:r.x,width:r.width}})')
    ck(len(visible)==2,'Evidence and assignment are opened together')
    ck(max(v['x'] for v in visible)>=min(v['x']+v['width'] for v in visible)-2,'Paired windows do not overlap at desktop width')
    page.screenshot(path=str(OUT/'02-evidence-and-work.png'))
    ck(page.evaluate('ledgerlabPreview.model().state.journals.length')==0,'Split-view shortcut never posts automatically')
    w=review(page);w.locator('[data-review-task="2025-07-welcome"]').click()
    text='I reconciled the inherited source evidence and documented outstanding queries for the finance owner.'
    w.get_by_label('Preparer response',exact=True).fill(text)
    w.get_by_label('Review stage',exact=True).select_option('cleared')
    w.locator('[data-review-save]').click()
    ck('underlying saved work' in w.locator('[role=alert]').inner_text(),'Cannot clear an incomplete assignment')
    ck(w.get_by_label('Preparer response',exact=True).input_value()==text,'Rejected clearance retains written response')
    w.get_by_label('Review stage',exact=True).select_option('prepared');w.locator('[data-review-save]').click();idle(page)
    ck('Review response saved' in w.inner_text(),'Prepared response saved through real session commands')
    ck('Response history (1)' in w.inner_text(),'Saved response history visible')
    ck(not page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Acknowledged review save clears dirty flag')
    saved=page.evaluate('ledgerlabPreview.model().state')
    ck(any(f['id']=='UF-review-notes-2025-07' for f in saved['desktop']['files']),'Review response included in normal backup state')
    fresh=context.new_page();fresh.set_content(HTML.read_text(),wait_until='domcontentloaded');fresh.wait_for_function('!!window.ledgerlabPreview')
    restored=fresh.evaluate('(state)=>ledgerlabPreview.session.save({type:"importBackup",state})',saved)
    ck(restored['ok'],'Backup import restores the review-note state through actual command validation')
    rw=review(fresh);rw.locator('[data-review-task="2025-07-welcome"]').click()
    ck(rw.get_by_label('Preparer response',exact=True).input_value()==text,'Restored response appears in another tab')
    fresh.close()
    submission=dict(FIX['welcome']);submission['status']='submitted'
    result=page.evaluate('(submission)=>ledgerlabPreview.session.save({type:"saveDailySubmission",submission})',submission)
    ck(result['ok'],'Correct underlying submission accepted')
    w=review(page);w.locator('[data-review-task="2025-07-welcome"]').click()
    w.get_by_label('Review stage',exact=True).select_option('cleared');w.locator('[data-review-save]').click();idle(page)
    ck('Cleared (training check)' in w.locator('[data-review-task="2025-07-welcome"]').inner_text(),'Passing task can be cleared as a training check')
    submission['note']+=' Additional supported conclusion.'
    page.evaluate('(submission)=>ledgerlabPreview.session.save({type:"saveDailySubmission",submission})',submission)
    ck('Changes requested' in w.locator('[data-review-task="2025-07-welcome"]').inner_text(),'Changed work reopens earlier clearance')
    w.get_by_label('Preparer response',exact=True).fill(text+' Follow-up recorded.')
    w.locator('[data-review-task]').nth(1).click()
    ck('Save or discard' in w.locator('[role=alert]').inner_text(),'Switching tasks cannot lose a draft')
    page.locator('[data-close-task="review-notes"]').click()
    dialog=page.locator('.pc-modal[role=dialog]').last
    ck(dialog.is_visible(),'Closing a dirty review asks for a decision')
    dialog.get_by_role('button',name='Cancel',exact=True).click()
    ck(w.get_by_label('Preparer response',exact=True).input_value().endswith('Follow-up recorded.'),'Cancel retains the draft')
    page.evaluate('ledgerlabPreview.dropNextAcknowledgement()')
    w.get_by_label('Review stage',exact=True).select_option('prepared');w.locator('[data-review-save]').click();idle(page)
    ck(page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Lost save acknowledgement preserves dirty response')
    ck(w.get_by_label('Preparer response',exact=True).input_value().endswith('Follow-up recorded.'),'Lost acknowledgement preserves written content')
    page.evaluate('ledgerlabPreview.session.load()');idle(page)
    w=review(page);w.locator('[data-review-save]').click()
    ck('Another save changed' in w.locator('[role=alert]').inner_text(),'Unconfirmed saved revision cannot be overwritten blindly')
    w.locator('[data-review-discard]').click()
    ck(not page.evaluate('ledgerlabPreview.desktop.hasUnsaved()'),'Explicit discard loads current saved response')
    page.screenshot(path=str(OUT/'03-review-notes.png'))
    w.get_by_label('Preparer response',exact=True).fill('Preserve this draft when a different practice case replaces the active case.')
    page.evaluate('ledgerlabPreview.external({type:"startCareer",seed:42,startMonth:"2025-07",role:"financial-manager",scenario:"messy",daily:true,confirmation:"START TAKEOVER"})')
    page.evaluate('ledgerlabPreview.session.load()');idle(page)
    w=review(page)
    ck('Preserved review draft' in w.inner_text(),'Case replacement preserves orphaned draft for recovery')
    with page.expect_download() as download: w.locator('[data-review-download]').click()
    ck('Review-response-draft' in download.value.suggested_filename,'Orphaned review draft can be downloaded')
    w.locator('[data-review-discard]').click()
    page.set_viewport_size({'width':390,'height':844})
    open_search(page,'bank')
    r=page.locator('.pc-command-palette').bounding_box()
    ck(r['x']>=0 and r['x']+r['width']<=391,'Search dialog fits narrow viewport')
    page.screenshot(path=str(OUT/'04-narrow-search.png'))
    page.keyboard.press('Escape')
    page.set_viewport_size({'width':1500,'height':1000});open_search(page,'bank')
    page.screenshot(path=str(OUT/'01-search.png'))
    ck(errors==[],'No uncaught page errors')
    browser.close()
print(f'Workspace Chromium: {len(checks)} assertions passed.',flush=True)
(OUT/'results.json').write_text(json.dumps({'assertions':len(checks),'checks':checks,'page_errors':errors},indent=2))
