import {asOfDate,closePackDate,taskSchedule} from '../../lib/accounting/workday-calendar';
import {assessMonth} from '../../lib/accounting/month-assessment';
import {monthReviewHTML,monthReviewDocument,reviewStyles,filterReview} from '../../lib/accounting/month-review-view';
/** Browser-local accounting adapter. Uses the same validated commands as the production app. */
import {htmlEscape as e,downloadFile,financialStatementsHTML,journalCSV,trialBalanceCSV,payrollCSV,bankCSV} from '../../lib/accounting/exports';
import {trialBalance,profitAndLoss,bankReconciliation,bankAmount,subledger,journalError,progress,accountBalances,validateBackup} from '../../lib/accounting/engine';
import {ACCOUNTS,ACCOUNT_MAP} from '../../lib/accounting/accounts';
import {parseMoney,money,monthEnd} from '../../lib/accounting/money';
import {careerTasks,FORECAST_FIELDS,blankForecast} from '../../lib/accounting/career-work';
import {CAREER_MONTHS,careerKey} from '../../lib/accounting/career';
import type {Command,Journal,Line,SourceDocument} from '../../lib/accounting/types';
import type {CareerSubmission,ForecastWeek,CareerForecast} from '../../lib/accounting/career-types';
import {sourceDocuments,currentMonth,type DesktopModel} from '../../lib/desktop/files';
import type {DesktopHandle} from '../../lib/desktop/shell';
import {desktopDialog} from '../../lib/desktop/dialog';
type Bridge={activateMonth:()=>void;model:()=>DesktopModel;send:(command:Command)=>Promise<boolean>;desktop:()=>DesktopHandle;source:()=>string;setSource:(id:string)=>void};
const button=(a:string,label:string,attrs='')=>`<button type="button" data-local="${a}" ${attrs}>${label}</button>`;
const amountInput=(name:string,value='',label=name)=>`<input name="${e(name)}" aria-label="${e(label)}" inputmode="decimal" value="${e(value)}" placeholder="0.00">`;
const field=(label:string,name:string,value='',type='text')=>`<label>${e(label)}<input name="${e(name)}" aria-label="${e(label)}" type="${type}" value="${e(value)}"></label>`;
const table=(headers:string[],rows:string[][])=>`<div class="lc-table-scroll"><table class="pc-data-table"><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const accountSelect=(name:string,value='',eligible=ACCOUNTS)=>`<select name="${e(name)}" aria-label="${e(name)}"><option value="">Choose account</option>${eligible.map(a=>`<option value="${a.code}" ${value===a.code?'selected':''}>${e(a.code+' · '+a.name)}</option>`).join('')}</select>`;
export function createLocalAccounting(bridge:Bridge){
 const drafts=new Map<string,Record<string,string>>(),dirtyFields=new Map<string,Set<string>>();let rows=2,lastCase='';
 const controls=(target:HTMLElement)=>[...target.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[name]')];
 const keep=(view:string,target:HTMLElement)=>{const state:Record<string,string>={};for(const input of controls(target))state[input.name]=input.value;drafts.set(view,state);};
 const notify=(target:HTMLElement,message:string,bad=false)=>{const el=target.querySelector<HTMLElement>('[data-local-status]');if(el){el.textContent=message;el.classList.toggle('lc-error',bad);el.scrollIntoView({block:'nearest'});}};
 function clearSaved(c:Command){
  for(const fields of dirtyFields.values())for(const name of [...fields]){
    const clear=c.type==='postJournal'&&(/^(journal-|cash-class|Account |Debit |Credit |Contact |Memo )/.test(name))||
      c.type==='captureSourceInvoice'&&(/^(capture-|Invoice account )/.test(name))||
      (c.type==='matchBank'||c.type==='unmatchBank')&&name===`bank-${c.bankId}`||
      c.type==='saveNotes'&&name==='notebook'||
      c.type==='saveCareerSubmission'&&name.startsWith(`task:${c.submission.taskId}:`)||
      c.type==='saveCareerForecast'&&name.startsWith('forecast')||
      (c.type==='closeCareerMonth'||c.type==='reopenCareerMonth')&&name==='close-reason';
    if(clear)fields.delete(name);
  }
 }
 function render(view:string,target:HTMLElement,force=false){
  const m=bridge.model(),active=currentMonth(m),month=['career','close','overview','practice'].includes(view)?active:(m.reportingMonth??active),end=asOfDate(m.state,month),caseID=`${m.state.seed}|${m.state.career?.startedAt??''}`;
  if(caseID!==lastCase){if(lastCase){drafts.clear();dirtyFields.clear();rows=2;bridge.setSource('');}lastCase=caseID;}
  const signature=[view,month,m.state.journals.length,m.state.auditLog.length,bridge.source()].join('|');
  if(!force&&target.dataset.localSignature===signature)return;
  const openDetails=[...target.querySelectorAll<HTMLDetailsElement>('details[data-task][open]')].map(el=>el.dataset.task!);
  const previous=target.dataset.localView;if(previous)keep(previous,target);target.dataset.localSignature=signature;target.dataset.localView=view;
  const docs=sourceDocuments(m),monthly=docs.filter(d=>d.date.startsWith(month));let body='';
  const docButton=(d:SourceDocument)=>button('source',e(d.id),`data-id="${e(d.id)}"`);
  const sourceTable=(sources:SourceDocument[])=>table(['Source','Date','Type','Party','Title','Amount AUD'],sources.map(d=>[docButton(d),e(d.date),e(d.kind),e(d.party),e(d.title),money(d.total)]));
  const journalRows=()=>Array.from({length:rows},(_,i)=>`<tr><td>${accountSelect('Account '+(i+1))}</td><td>${amountInput('Debit '+(i+1))}</td><td>${amountInput('Credit '+(i+1))}</td><td><select name="Contact ${i+1}" aria-label="Contact ${i+1}"><option value="">No contact</option>${m.company.contacts.map(c=>`<option value="${e(c.id)}">${e(c.name)}</option>`).join('')}</select></td><td>${amountInput('Memo '+(i+1),'','Memo '+(i+1))}</td></tr>`).join('');
  const postForm=()=>`<section class="lc-card"><h3>Prepare a journal</h3><p>Enter your own coding and balanced amounts. Post bank settlements separately from invoices. Control accounts require a contact.</p><div class="lc-fields">${field('Journal date','journal-date',end,'date')}${field('Journal description','journal-description')}${field('Journal reference','journal-reference')}<label>Source document<select name="journal-source" aria-label="Journal source"><option value="">No linked source</option>${docs.map(d=>`<option value="${e(d.id)}" ${bridge.source()===d.id?'selected':''}>${e(d.id+' · '+d.title)}</option>`).join('')}</select></label><label>Cash flow class<select name="cash-class"><option value="operating">Operating</option><option value="investing">Investing</option><option value="financing">Financing</option></select></label></div><div class="lc-table-scroll"><table class="pc-data-table lc-journal"><thead><tr><th>Account</th><th>Debit AUD</th><th>Credit AUD</th><th>Contact</th><th>Memo</th></tr></thead><tbody>${journalRows()}</tbody></table></div><div class="lc-actions">${button('add-line','Add journal line')}${button('remove-line','Remove last line')}${button('post-journal','Post journal','class="lc-primary"')}<span data-journal-total>Debits 0.00 / Credits 0.00</span></div></section>`;
  if(view==='ledger'){
   body=postForm()+`<section class="lc-card"><h3>Posted journals · ${e(month)}</h3><div class="lc-actions">${button('export-journals','Export journal CSV')}${button('export-tb','Export trial balance')}</div>${table(['Date','Reference','Description','Debit AUD','Credit AUD','Action'],m.journals.filter(j=>j.date.startsWith(month)).map(j=>[e(j.date),e(j.reference),`<details><summary>${e(j.description)}</summary>${j.lines.map(l=>`${e(l.account+' '+(ACCOUNT_MAP[l.account]?.name??''))}: Dr ${money(l.debit)} / Cr ${money(l.credit)}${l.contact?' · '+e(l.contact):''}`).join('<br>')}</details>`,money(j.lines.reduce((s,l)=>s+l.debit,0)),money(j.lines.reduce((s,l)=>s+l.credit,0)),m.state.journals.some(x=>x.id===j.id)&&!m.state.journals.some(x=>x.reverses===j.id)?button('reverse','Reverse',`data-id="${e(j.id)}"`):'Inherited / reversed']))}</section>`;
  }else if(view==='payables'||view==='receivables'){
   const supplier=view==='payables',kinds=supplier?['Supplier invoice','Supplier credit note']:['Sales invoice','Credit note'],invoices=monthly.filter(d=>kinds.includes(d.kind)),selected=docs.find(d=>d.id===bridge.source()&&kinds.includes(d.kind)),sl=subledger(m.company,m.state,supplier?'supplier':'customer',end);
   body=`<section class="lc-card"><h3>${supplier?'Supplier invoice capture':'Customer invoice capture'}</h3><p>Select a source, verify tax and choose the posting accounts. Capturing does not pay or receive cash.</p>${table(['Source','Party','Date','Gross AUD','Capture'],invoices.map(d=>[docButton(d),e(d.party),e(d.date),money(d.total),button('capture-select','Open capture',`data-id="${e(d.id)}"`)]))}</section>`;
   if(selected){const sd=selected,sales=!supplier,contact=m.company.contacts.find(c=>c.name===sd.party&&c.kind===(sales?'customer':'supplier'));
    body+=`<section class="lc-card lc-capture"><h3>Capture ${e(sd.id)}</h3><p>${e(sd.party)} · ${e(sd.date)} · Net ${money(sd.net)} · Tax ${money(sd.tax)} · Gross ${money(sd.total)}</p><label>Contact<select name="capture-contact" aria-label="Invoice contact"><option value="">Choose contact</option>${m.company.contacts.filter(c=>c.kind===(sales?'customer':'supplier')).map(c=>`<option value="${e(c.id)}" ${contact?.id===c.id?'selected':''}>${e(c.name)}</option>`).join('')}</select></label>${table(['Line','Net AUD','Tax AUD','Posting account'],sd.lines.map((l,i)=>[e(l.description),money(l.net),money(l.tax),accountSelect('Invoice account '+(i+1),'',ACCOUNTS.filter(a=>a.type!=='equity'&&!a.control&&a.code!=='1000'))]))}<p>${sales?'Receivables':'Payables'} and GST controls are calculated from the source. Cost of sales and other related entries may still be needed.</p>${button('capture-post','Post source invoice','class="lc-primary" data-id="'+e(sd.id)+'"')}</section>`;
   }
   body+=`<section class="lc-card"><h3>${supplier?'Supplier balances':'Customer balances'} · learner subledger</h3><p>Control difference: ${money(sl.difference)}. Review source statements and open invoices, not just this total.</p>${table(['Contact','Balance AUD','Movements'],sl.contacts.map(c=>[e(c.contact.name),money(c.balance),`<details><summary>Open ledger detail</summary>${c.movements.map(x=>`${e(x.journal.date+' '+x.journal.reference)} · ${money(x.amount)}`).join('<br>')}</details>`]))}</section>`;
  }else if(view==='bank'){
   const rec=bankReconciliation(m.company,m.state,month),used=new Set(Object.values(m.state.bankMatches).flat()),eligible=m.journals.filter(j=>j.date<=end&&bankAmount(j)!==0&&!used.has(j.id));
   body=`<section class="lc-card"><h3>Bank reconciliation</h3><div class="lc-metrics"><span>Cashbook<strong>${money(rec.book)}</strong></span><span>Statement<strong>${money(rec.closingStatement)}</strong></span><span>Reconciliation difference<strong>${money(rec.reconciliationDifference)}</strong></span><span>Matched<strong>${rec.matched} / ${rec.rows.length}</strong></span></div><p>Select one or several ledger entries for a statement line. Amounts must agree exactly. A match is not a missing journal entry.</p><div class="lc-actions">${button('goto-ledger','Prepare missing entry')}${button('bank-workpaper','Open bank working paper')}${button('export-bank','Export statement CSV')}</div>${table(['Date / source','Description','Statement AUD','Ledger entries','Action'],rec.rows.map(r=>{const ids=m.state.bankMatches[r.id];return [e(r.date+' '+r.reference),e(r.description),money(r.amount),ids?ids.map(e).join('<br>'):`<select multiple size="3" name="bank-${e(r.id)}" aria-label="Ledger entries for ${e(r.id)}">${eligible.map(j=>`<option value="${e(j.id)}">${e(j.date+' '+j.reference)} · ${money(bankAmount(j))}</option>`).join('')}</select>`,button(ids?'unmatch':'match',ids?'Unmatch':'Match selected',`data-id="${e(r.id)}"`)];}))}<h4>Unmatched cashbook entries</h4>${table(['Date','Reference','Description','Amount AUD'],rec.unpresented.map(j=>[e(j.date),e(j.reference),e(j.description),money(bankAmount(j))]))}</section>`;
  }else if(view==='payroll'){
   const pay=m.company.payroll[month]??[],balances=accountBalances(m.journals,undefined,end);
   body=`<section class="lc-card"><h3>Payroll review</h3><p>Independent source register. Reconcile gross-to-net, employer costs and liability settlements. Dated teaching-case assumptions, not current statutory calculations.</p><div class="lc-actions">${button('payroll-workpaper','Create payroll workbook')}${button('goto-ledger','Prepare payroll journal')}${button('export-payroll','Export payroll register')}</div>${table(['Employee','Gross','Withholding','Deductions','Net','Super'],pay.map(p=>[e(p.name),money(p.gross),money(p.withholding),money(p.deductions),money(p.net),money(p.super)]))}<h4>Learner payroll controls</h4>${table(['Account','Description','Credit balance AUD'],['2110','2120','2130','2140','2150'].map(code=>[code,e(ACCOUNT_MAP[code].name),money(-balances[code])]))}</section>`;
  }else if(view==='reports'){
   const pl=profitAndLoss(m.journals,`${month}-01`,end);body=`<section class="lc-card"><h3>Management reporting and AFS</h3><p>Live learner ledger, not a worked answer. Unsigned teaching draft; prior-year signed statements and complete comparative income data are outstanding.</p><div class="lc-metrics"><span>Revenue<strong>${money(pl.revenue)}</strong></span><span>Gross profit<strong>${money(pl.grossProfit)}</strong></span><span>Net profit<strong>${money(pl.netProfit)}</strong></span></div><div class="lc-actions">${button('view-afs','Open draft financial statements')}${button('export-afs','Export draft AFS HTML')}${button('afs-workpaper','Create AFS preparation workbook')}${button('management-workpaper','Create management workbook')}${button('export-tb','Export trial balance CSV')}</div>${table(['Account','Description','Debit AUD','Credit AUD'],trialBalance(m.journals,end).filter(r=>r.debit||r.credit).map(r=>[r.code,e(r.name),money(r.debit),money(r.credit)]))}</section>`;
  }else if(['career','close','overview','practice'].includes(view)){
   const tasks=m.state.career?careerTasks(m.company,m.state,month).filter(t=>!m.state.workday||taskSchedule(t.id,month,m.state.career!.startMonth).release<=m.state.workday.today):[],p=progress(m.company,m.state);body=`<section class="lc-card"><h3>Your ${e(month)} close</h3><p>${p.completed} / ${p.total} processing work units correct across the released case. Figures are checked against independent scenario data. Narrative length is not proof of good judgement.</p><div class="lc-actions">${button('goto-ledger','Journal & ledger')}${button('goto-bank','Bank reconciliation')}${button('close-workpaper','Create close file')}${button('forecast-toggle','Open 13-week forecast')}</div></section>`;
   if(m.state.career&&(!m.state.workday||m.state.workday.today>=closePackDate(month)))body=`<style>${reviewStyles}</style>${monthReviewHTML(m.company,m.state,assessMonth(m.company,m.state))}`+body;
   if(m.state.workday&&m.state.workday.today<closePackDate(month))body=`<section class="lc-card"><h3>Work from today’s assignments</h3><p>PC date ${e(m.state.workday.today)}. Full month review opens on ${closePackDate(month)}, when the closing evidence arrives. Only formal deliverables requested so far are shown below.</p>${button('today','Open Today / daily tasks')}</section>`+body;
   for(const task of tasks){const saved=m.state.career?.submissions[careerKey(month,task.id)];body+=`<details class="lc-card" data-task="${e(task.id)}"><summary><strong>${e(task.title)}</strong> · ${e(saved?.status??'Not started')}</summary><p>${e(task.brief)}</p><p>Evidence: ${task.evidence.map(id=>button('source',e(id),`data-id="${e(id)}"`)).join(' ')}</p><div class="lc-fields">${task.figures.map(f=>`<label>${e(f.label)} (AUD)${amountInput('task:'+task.id+':figure:'+f.id,saved?.figures[f.id]!==undefined?(saved.figures[f.id]/100).toFixed(2):'',f.label)}</label>`).join('')}</div>${task.responses.map(r=>`<label>${e(r.label)}<small>${e(r.guidance)}</small><textarea name="task:${e(task.id)}:response:${e(r.id)}" rows="4">${e(saved?.responses[r.id]??'')}</textarea></label>`).join('')}<label>Evidence IDs, comma-separated<input name="task:${e(task.id)}:evidence" value="${e(saved?.evidence.join(', ')??'')}"></label><div class="lc-actions">${button('task-draft','Save draft',`data-id="${e(task.id)}"`)}${button('task-submit','Submit for numerical checks',`data-id="${e(task.id)}" class="lc-primary"`)}</div></details>`;}
   body+=`<section class="lc-card"><h3>Close and release</h3><p>Close runs the existing processing, bank, deliverable and forecast gates. It does not bypass unfinished work.</p>${field('Close / reopen reason','close-reason')}<div class="lc-actions">${button('close-month','Check and close active month')}${button('advance-month','Release next month')}${button('reopen-month','Reopen active month')}</div></section>`;
  }else if(view==='settings'){
   body=`<section class="lc-card"><h3>Your local case</h3><p>Saved in this browser, not uploaded to the hosted app. Use a backup before changing case or browser. The backup includes saved journals, matches, workbooks and deliverables, not unsaved editor drafts.</p><div class="lc-actions">${m.state.career&&!m.state.workday?button('enable-daily','Enable day-by-day mode for this case'):m.state.workday?button('today','Open Today / PC date'):''}${button('backup','Download full case backup')}${button('restore','Restore case backup')}</div><label>Practice notebook<textarea name="notebook" rows="8">${e(m.state.notes)}</textarea></label>${button('save-notes','Save notebook','class="lc-primary"')}</section><section class="lc-card"><h3>Start a different takeover</h3><p>This replaces the local case only after confirmation. Download your existing backup first.</p><div class="lc-fields"><label>Start month<select name="start-month">${CAREER_MONTHS.map(v=>`<option ${v==='2025-07'?'selected':''}>${v}</option>`).join('')}</select></label><label>Role<select name="start-role"><option value="financial-manager">Financial manager</option><option value="financial-accountant">Financial accountant</option></select></label><label>Handover<select name="start-scenario"><option value="messy">Messy handover</option><option value="supported">Supported handover</option></select></label></div>${button('start-career','Start new local case')}</section>`;
  }else if(view==='knowledge'){
   body=`<section class="lc-card"><h3>How to work this desk</h3><p>1. Read the handover and released source evidence.</p><p>2. Process invoices, settlements and journals. Use the source ID so the ledger and evidence remain traceable.</p><p>3. Match bank movements and prepare reconciliations. Source data is independent; a balanced journal is not necessarily correct.</p><p>4. Reconcile payroll, control accounts and estimates. Use Working papers / Templates for linked-sheet schedules.</p><p>5. Draft management accounts, cash forecasts and AFS. Submit the requested deliverables from Finance desk.</p><p>6. Resolve close checks, close the month, then release the next month. Future actuals remain withheld.</p><p>The browser worksheet is not Microsoft Excel: 500 rows × 52 columns, 8 sheets, documented functions only, no VBA, pivots or full Office compatibility.</p><div class="lc-actions">${button('goto-career','Open finance desk')}${button('templates','Browse working-paper templates')}</div></section>`;
  }else{
   const map:Record<string,{title:string;accounts:string[];pattern:RegExp;template:string}>={assets:{title:'Assets, depreciation and leases',accounts:['1500','1510','1520','1530','2520','2530'],pattern:/FA-|ASSET|LEASE|DISPOSAL/i,template:'assets'},inventory:{title:'Inventory, counts and NRV',accounts:['1200','1210','5000','5010','5020'],pattern:/STOCK|COUNT|INVENTORY|NRV/i,template:'inventory'},provisions:{title:'Provisions and estimates',accounts:['2400','2410','2150','6700','6710'],pattern:/LEGAL|WARRANTY|CLAIM|LEAVE/i,template:'accrual'},tax:{title:'Tax control review',accounts:['1400','1600','2200','2210','2600','2610','6800','6810'],pattern:/GST|TAX|BAS/i,template:'afs'},audit:{title:'Evidence and review file',accounts:[],pattern:/HANDOVER|MEMO|LEGAL|TAX|EVIDENCE/i,template:'close'}};
   const area=map[view];body=`<section class="lc-card"><h3>${e(area?.title??'Source documents')}</h3><p>Open the source evidence, prepare your supporting workbook and post or submit the result using the linked accounting screens. Files are evidence, not automatic postings.</p><div class="lc-actions">${button('goto-ledger','Prepare journal')}${button('goto-career','Prepare formal deliverable')}${area?button('area-workpaper','Create supporting workbook',`data-template="${area.template}"`):''}</div>${area?.accounts.length?table(['Account','Description','Debit / (credit) AUD'],trialBalance(m.journals,end).filter(r=>area.accounts.includes(r.code)).map(r=>[r.code,e(r.name),money(r.debit-r.credit)])):''}${sourceTable(area?docs.filter(d=>area.pattern.test(d.id+' '+d.title)):monthly)}</section>`;
  }
  target.innerHTML=`<div class="lc-workspace"><header><div><small>LOCAL FINANCE WORKSTATION · AUD · ${e(month)}${m.state.workday?' · PC '+e(m.state.workday.today)+' · Reports through '+e(end):''}</small><h2>${e(({ledger:'Journal & ledger',bank:'Cash and banking',payables:'Accounts payable',receivables:'Accounts receivable',reports:'Financial reporting'} as Record<string,string>)[view]??'Harbour & Co. finance')}</h2></div><div>${m.state.workday?button('today','Today'):''}${button('backup','Backup case')}${button('discard-forms','Discard accounting drafts')}</div></header><p role="status" data-local-status>Saved journals and submissions use the accounting engine. Spreadsheets do not post to the ledger.</p>${body}</div>`;
  if(previous===view)for(const id of openDetails){const detail=target.querySelector<HTMLDetailsElement>(`details[data-task="${CSS.escape(id)}"]`);if(detail)detail.open=true;}
  const draft=drafts.get(view);if(draft)for(const input of controls(target))if(draft[input.name]!==undefined)input.value=draft[input.name];
  const val=(name:string)=>target.querySelector<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(`[name="${CSS.escape(name)}"]`)?.value??'';
  const command=async(c:Command,success:string)=>{keep(view,target);const ok=await bridge.send(c);if(ok){clearSaved(c);render(view,target,true);notify(target,success);}else notify(target,bridge.model().error||'Save not confirmed. Keep your draft, reload saved state and check before retrying.',true);return ok;};
  target.oninput=(event)=>{const name=(event.target as HTMLInputElement).name;if(name&&!name.startsWith('start-')){const set=dirtyFields.get(view)??new Set<string>();set.add(name);dirtyFields.set(view,set);}keep(view,target);if(view==='ledger'){try{let debit=0,credit=0;for(let i=1;i<=rows;i++){debit+=parseMoney(val('Debit '+i)||'0');credit+=parseMoney(val('Credit '+i)||'0');}target.querySelector('[data-journal-total]')!.textContent=`Debits ${money(debit)} / Credits ${money(credit)} · Difference ${money(debit-credit)}`;}catch{target.querySelector('[data-journal-total]')!.textContent='Enter valid amounts with no more than two decimals.';}}};
  target.onchange=event=>{
   const el=event.target as HTMLInputElement;if(!el.matches('[data-review-passed]')){if(el.name&&!el.name.startsWith('start-')){const fields=dirtyFields.get(view)??new Set<string>();fields.add(el.name);dirtyFields.set(view,fields);keep(view,target);}return;}
   const panel=el.closest<HTMLElement>('.mr-panel')!;filterReview(panel,panel.querySelector<HTMLInputElement>('[data-review-search]')?.value??'',el.checked);
  };
  const inputHandler=target.oninput;
  target.oninput=event=>{const el=event.target as HTMLInputElement;if(el.matches('[data-review-search]')){const panel=el.closest<HTMLElement>('.mr-panel')!;filterReview(panel,el.value,!!panel.querySelector<HTMLInputElement>('[data-review-passed]')?.checked);return;}inputHandler?.call(target,event);};
  target.onclick=async event=>{
   const review=(event.target as Element).closest<HTMLElement>('[data-review-action]');
   if(review){
    if(bridge.model().saving){notify(target,'A save is in progress. Keep the current draft until it completes.',true);return;}
    const action=review.dataset.reviewAction!;
    if(action==='work'){bridge.activateMonth();bridge.desktop().openApp(review.dataset.view!);return;}
    if(action==='source'){bridge.desktop().openFile('DOC:'+review.dataset.id!);return;}
    if(action==='check'){render(view,target,true);notify(target,'Saved work checked. Nothing was posted, closed or advanced. Unsaved fields are not included.');target.querySelector('.mr-panel')?.scrollIntoView({block:'start'});return;}
    if(action==='export'){const m=bridge.model(),report=assessMonth(m.company,m.state);downloadFile(`LedgerLab-month-feedback-${report.month}.html`,monthReviewDocument(m.company,m.state,report),'text/html');notify(target,'Feedback downloaded. It covers saved work at the time of this export.');return;}
    if(action==='submit'){
     const choice=await desktopDialog(document.getElementById('desktop')!,'Submit saved month for review?','Only saved postings, matches, deliverables and forecasts are marked. Unsaved forms and workbook cells are excluded. This reveals case answers and records feedback assistance. It does not post corrections, close the month or release the next month.',[{id:'cancel',label:'Cancel'}, {id:'submit',label:'Submit saved work',primary:true}]);
     if(choice==='submit'){const ok=await command({type:'submitMonthReview'},'Month review saved. Open each review area for missing work, your amounts, case answers and correction guidance.');if(ok)target.querySelector('.mr-panel')?.scrollIntoView({block:'start'});}
     return;
    }
   }
   const el=(event.target as Element).closest<HTMLElement>('[data-local]');if(!el)return;const a=el.dataset.local!,id=el.dataset.id??'';if(bridge.model().saving){notify(target,'A save is in progress. Let it complete before another action.',true);return;}
   try{
    if(a==='source'){bridge.desktop().openFile('DOC:'+id);return;}
    if(a.startsWith('goto-')){bridge.desktop().openApp(a.slice(5));return;}
    if(a==='templates'){bridge.desktop().openExplorer('Working papers/Templates');return;}
    if(a.endsWith('-workpaper')){bridge.desktop().newWorkbook(a==='area-workpaper'?el.dataset.template!:a.replace('-workpaper',''));return;}
    if(a==='today'){bridge.desktop().openDaily();return;}
    if(a==='discard-forms'){if(await desktopDialog(document.getElementById('desktop')!,'Discard unsaved accounting forms?','This discards every unsaved accounting form draft, including drafts on other accounting tabs. Saved postings, responses and workbooks are unchanged.',[{id:'cancel',label:'Cancel'},{id:'discard',label:'Discard accounting drafts'}])==='discard'){drafts.clear();dirtyFields.clear();target.dataset.localView='';render(view,target,true);}return;}
    if(a==='enable-daily'){if(bridge.desktop().hasUnsaved())throw Error('Save or discard all drafts before enabling daily mode.');if(await command({type:'enableWorkday'},'Daily mode enabled. Existing saved work is preserved; the PC date advances enough to keep already-used evidence visible.'))bridge.desktop().openDaily();return;}
    if(a==='backup'){downloadFile('LedgerLab-local-case-backup.json',JSON.stringify(bridge.model().state,null,2),'application/json');notify(target,'Backup downloaded. It contains saved work, not unsaved editor drafts.');return;}
    if(a==='add-line'||a==='remove-line'){keep(view,target);rows=Math.max(2,Math.min(30,rows+(a==='add-line'?1:-1)));render(view,target,true);return;}
    if(a==='capture-select'){bridge.setSource(id);drafts.delete(view);target.dataset.localView='';render(view,target,true);target.querySelector('.lc-capture')?.scrollIntoView({block:'start'});return;}
    if(a==='post-journal'){
     const lines:Line[]=[];for(let i=1;i<=rows;i++){const debit=parseMoney(val('Debit '+i)||'0'),credit=parseMoney(val('Credit '+i)||'0'),account=val('Account '+i);if(!account&&!debit&&!credit)continue;lines.push({account,debit,credit,...(val('Contact '+i)?{contact:val('Contact '+i)}:{}),...(val('Memo '+i)?{memo:val('Memo '+i)}:{})});}
     const journal:Journal={id:'USR-'+(globalThis.crypto?.randomUUID?.()??Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)),date:val('journal-date'),description:val('journal-description'),reference:val('journal-reference'),module:'Manual journal',lines,...(val('journal-source')?{sourceId:val('journal-source')}:{}),cashClass:val('cash-class') as Journal['cashClass']};const error=journalError(journal,bridge.model().company);if(error)throw Error(error);
     if(await command({type:'postJournal',journal},'Journal posted. Balances, reports and close checks now use it.')){drafts.delete(view);target.dataset.localView='';render(view,target,true);notify(target,'Journal posted successfully.');}return;
    }
    if(a==='capture-post'){
     const doc=sourceDocuments(bridge.model()).find(d=>d.id===id)!;if(!doc)throw Error('Source unavailable.');const sales=doc.kind==='Sales invoice'||doc.kind==='Credit note',credit=doc.kind==='Credit note'||doc.kind==='Supplier credit note',contact=val('capture-contact');if(!contact)throw Error('Select a customer or supplier.');
     const line=(account:string,amount:number,debit:boolean,itemId?:string):Line=>({account,debit:debit?Math.abs(amount):0,credit:debit?0:Math.abs(amount),...(itemId?{itemId}:{}),...(account==='1100'||account==='2000'?{contact}:{})});
     const lines:Line[]=doc.lines.map((l,i)=>{const account=val('Invoice account '+(i+1));if(!account)throw Error('Choose an account for every source line.');return line(account,l.net,sales?credit:!credit,account==='1200'?l.itemId:undefined);}).filter(l=>l.debit||l.credit);if(doc.tax)lines.push(line(sales?'2200':'1400',doc.tax,sales?credit:!credit));lines.push(line(sales?'1100':'2000',doc.total,sales?!credit:credit));
     await command({type:'captureSourceInvoice',documentId:id,journal:{id:'CAP-'+(globalThis.crypto?.randomUUID?.()??Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)),date:doc.date,description:doc.title,reference:doc.id,module:sales?'Sales':'Purchases',sourceId:doc.id,lines}},'Source invoice posted. Duplicate capture is blocked; bank settlement remains separate.');return;
    }
    if(a==='match'){const select=target.querySelector<HTMLSelectElement>(`[name="bank-${CSS.escape(id)}"]`)!;const ids=[...select.selectedOptions].map(o=>o.value);await command({type:'matchBank',bankId:id,journalIds:ids},'Statement line matched to the selected journal entries.');return;}
    if(a==='unmatch'){await command({type:'unmatchBank',bankId:id},'Bank match removed. No journal was deleted.');return;}
    if(a==='reverse'){const reason=val('journal-description');if(!reason.trim())throw Error('Enter your reversal reason in Journal description and the effective Journal date above.');if(await desktopDialog(document.getElementById('desktop')!,'Reverse journal?',`Reverse ${id} on ${val('journal-date')}? The original is retained.`,[{id:'cancel',label:'Cancel'},{id:'reverse',label:'Reverse journal'}])==='reverse')await command({type:'reverseJournal',journalId:id,date:val('journal-date'),reason},'Reversal posted; original journal retained.');return;}
    if(a==='view-afs'){bridge.desktop().openFile('LIVE:afs:'+month);return;}
    if(a.startsWith('export-')){const m=bridge.model(),kind=a.slice(7),data=kind==='tb'?trialBalanceCSV(m.journals,end):kind==='journals'?journalCSV(m.journals.filter(j=>j.date.startsWith(month))):kind==='bank'?bankCSV(m.company,month):kind==='payroll'?payrollCSV(m.company,month):financialStatementsHTML(m.company,m.state,'2025-01-01',end);downloadFile(`LedgerLab-${kind}-${month}.${kind==='afs'?'html':'csv'}`,data,kind==='afs'?'text/html':'text/csv');return;}
    if(a==='save-notes'){await command({type:'saveNotes',notes:val('notebook')},'Notebook saved.');return;}
    if(a==='task-draft'||a==='task-submit'){const task=careerTasks(bridge.model().company,bridge.model().state,month).find(t=>t.id===id)!;const submission:CareerSubmission={taskId:id,month,status:a==='task-submit'?'submitted':'draft',figures:{},responses:{},evidence:val(`task:${id}:evidence`).split(',').map(s=>s.trim()).filter(Boolean),updatedAt:new Date().toISOString()};for(const f of task.figures){const raw=val(`task:${id}:figure:${f.id}`);if(raw.trim())submission.figures[f.id]=parseMoney(raw);}for(const r of task.responses)submission.responses[r.id]=val(`task:${id}:response:${r.id}`);await command({type:'saveCareerSubmission',submission},a==='task-submit'?'Deliverable submitted. Numerical checks passed; written judgement still requires human review.':'Deliverable draft saved.');return;}
    if(a==='close-month'){await command({type:'closeCareerMonth',reason:val('close-reason')},'Active month closed. Release the next month when ready.');return;}
    if(a==='advance-month'){await command({type:'advanceCareerMonth'},'Next month released. Change the reporting month selector to review it.');return;}
    if(a==='reopen-month'){await command({type:'reopenCareerMonth',reason:val('close-reason')},'Active month reopened.');return;}
    if(a==='forecast-toggle'){if(bridge.model().state.workday&&bridge.model().state.workday!.today<closePackDate(month))throw Error('The formal month-end forecast opens on '+closePackDate(month)+'. Use today’s weekly cash working paper first.');renderForecast(target,month,bridge,command);return;}
    if(a==='start-career'){
     const startMonth=val('start-month'),role=val('start-role') as 'financial-manager'|'financial-accountant',scenario=val('start-scenario') as 'messy'|'supported';if(!bridge.desktop().canLeave())return;
     const choice=await desktopDialog(document.getElementById('desktop')!,'Replace this local case?',`Start ${startMonth} with a ${scenario} handover? Download your saved-case backup first. This does not change the hosted app.`,[{id:'cancel',label:'Cancel'},{id:'start',label:'Start new local case'}]);if(choice==='start'){await command({type:'startCareer',seed:bridge.model().state.seed,startMonth,role,scenario,daily:true,confirmation:'START TAKEOVER'},'New takeover started.');}return;
    }
    if(a==='restore'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const file=input.files?.[0];if(!file)return;if(file.size>3_000_000)throw Error('Backup exceeds 3 MB.');const state=JSON.parse(await file.text()),error=validateBackup(state);if(error)throw Error(error);if(!bridge.desktop().canLeave())return;if(await desktopDialog(document.getElementById('desktop')!,'Restore saved case?','This replaces the browser-local case, including its saved workbooks. Export your current backup first.',[{id:'cancel',label:'Cancel'},{id:'restore',label:'Restore case'}])==='restore')await command({type:'importBackup',state},'Backup restored.');}catch(error){notify(target,(error as Error).message,true);}};input.click();return;}
   }catch(error){notify(target,(error as Error).message,true);}
  };
 }
 return Object.assign(render,{hasUnsaved:()=>[...dirtyFields.values()].some(v=>v.size>0)});
}
function renderForecast(target:HTMLElement,month:string,bridge:Bridge,send:(c:Command,s:string)=>Promise<boolean>){
 const saved=bridge.model().state.career?.forecasts[month]??blankForecast(month),host=document.createElement('section');host.className='lc-card lc-forecast';target.querySelector('.lc-forecast')?.remove();
 host.innerHTML=`<h3>13-week cash forecast · ${e(month)}</h3><p>Enter positive receipts and payments in AUD. The close engine checks completeness, not the realism of your assumptions.</p>${table(['Week',...FORECAST_FIELDS.map(f=>f.label)],saved.weeks.map((week,i)=>[String(i+1),...FORECAST_FIELDS.map(f=>amountInput(`forecast:${i}:${f.id}`,(week[f.id]/100).toFixed(2),`${f.label} week ${i+1}`))]))}${field('Minimum cash reserve','forecast-minimum',(saved.minimumCash/100).toFixed(2))}<label>Assumptions<textarea name="forecast-assumptions">${e(saved.assumptions)}</textarea></label><label>Actions and stress response<textarea name="forecast-actions">${e(saved.actions)}</textarea></label>${field('Forecast evidence IDs, comma-separated','forecast-evidence',saved.evidence.join(', '))}${button('save-forecast-draft','Save forecast draft')}${button('save-forecast-submit','Submit forecast')}`;
 target.querySelector('.lc-workspace')!.append(host);host.scrollIntoView({block:'start'});host.onclick=async event=>{const a=(event.target as Element).closest<HTMLElement>('[data-local]')?.dataset.local;if(!a?.startsWith('save-forecast'))return;event.stopPropagation();const val=(name:string)=>host.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${CSS.escape(name)}"]`)!.value;try{const forecast:CareerForecast={month,status:a.endsWith('submit')?'submitted':'draft',minimumCash:parseMoney(val('forecast-minimum')||'0'),weeks:saved.weeks.map((_,i)=>Object.fromEntries(FORECAST_FIELDS.map(f=>[f.id,parseMoney(val(`forecast:${i}:${f.id}`)||'0')])) as ForecastWeek),assumptions:val('forecast-assumptions'),actions:val('forecast-actions'),evidence:val('forecast-evidence').split(',').map(s=>s.trim()).filter(Boolean),updatedAt:new Date().toISOString()};await send({type:'saveCareerForecast',forecast},'Forecast saved. Numerical totals are not a guarantee of forecast quality.');}catch(error){const status=target.querySelector<HTMLElement>('[data-local-status]')!;status.textContent=(error as Error).message;status.classList.add('lc-error');}};
}
